### ISSUE TITLE
August Task Checklist for Reviewing REDCap

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1286]
Need to make a REDCap Checklist for reviewing projects/instruments on GitHub
- [x] Write up a draft
- [x] @ritahitching will review and get it up in markdown

**Comment by ritahitching** [comment]
@lijenn do you have a working draft of the review checklist for RedCap that you can share?  
I can then start creating a .md file?
thanks

**Comment by staceypark** [comment]
@lijenn @ritahitching I'm not sure why it sounds like there is a version  of this that is not already a Markdown file? 

Jenn, where is the "draft" being created? And why is this a two-person two step process?

> Need to make a REDCap Checklist for reviewing projects/instruments on GitHub
> 
> * [ ]  Write up a draft
> * [ ]  @ritahitching will review and get it up in markdown

**Comment by lijenn** [comment]
@lijenn @ritahitching I was going to post a working draft here. I believe the task was delegated to the both of us. I believe it may also be helpful for both of us to review it and add onto it as both of us have REDCap reviewing tasks and can add on any details and tips that one or the other may have missed.

In that case, it does it make sense to just get a draft started as both of you mentioned. Here is what I have so far. Everything could be more more specified and go more into detail:

REDCap Project Review Checklist

Getting on REDCAP
- Provide brief instructions here on how to log in to REDCap or refer to map?

Project Review
1. Double check you are looking at the right project 
- project name could be slightly different than what it should reflect -> update the project name if needed
- some projects may not exist, but the measures can be copied over from another previous project (i.e R01 MTL Blue Baseline project can be used to create a R01 MTL Red Baseline project)
- [Place holder for instructions to copying a project here; should we refer them to the training guide if they forget or do not know how?]

2. Project instruments: This is where measures are located. These should be reflected and match what is in the final grant document.
- Locate the proper grant documents in the TeamPSD shared drive
- Look and compare that the measures from the grant documents are reflected in the corresponding REDCap project (i.e R01 measures are in R01 projects and not in IIR projects) 
- Look for typos and other misc. errors
- Look for outdated MTL language and update to current language (i.e QI, TAS, etc)

3. Team PSD Style
- Enable the Project and the corresponding instrument(s) as a survey
- Make sure Team PSD logos, font, colors, are correctly incorporated based on the project

Tips
- add common mistakes or tips here

**Comment by ritahitching** [comment]
@lijenn thank you. I'll create a .md file and make a pull request.
File location to be [here](https://github.com/lzim/teampsd/tree/master/resources/training_guides/redcap) 

@ritahitching

**Comment by staceypark** [comment]
@ritahitching @lijenn Next time, Jenn create the checklist and then send a pull request to Rita who can review and edit there.

**Comment by ritahitching** [comment]
@lijenn thanks for starting the RedCap New Project Checklist.

- [ ] The new draft RedCap checklist file [here](https://github.com/lzim/teampsd/tree/rita_2020_04_08_redcap_checklist_project_review/resources/training_guides/redcap)
- [ ] I will expand on your initial section headings and make add some additional tips
- [ ] I will upload the  LucidChart map on how to create a RedCap New Project map as a gif once @staceypark approves it.

**Please clarify**
- [ ] Do we want to add screenshots of the review process to the checklist?  
- [ ] Are we making the assumption that the user has full access rights already granted prior to commencing the review? 

Currently in my branch **rita_2020_04_08_redcap_checklist_project_review**

**Comment by ritahitching** [comment]
@lijenn and @staceypark 
- [ ] I have updated the RedCap Check list  [here](https://github.com/lzim/teampsd/tree/rita_2020_04_08_redcap_checklist_project_review/resources/training_guides/redcap)
- [ ] I inserted links to the VA Recap Training and uploaded a link to a draft image of the RedCap Lucidchart map.
- [ ] I made a pull request to merge this checklist to the master - tracked on issue #1297 - there will likely be future changes to the checklist as team PSD folks use it.

**Comment by staceypark** [comment]
@ritahitching  @lijenn Putting comments for pull request #1297 here:

RedCap checklist:
1. This checklist does not have enough detail. Remember, the audience for this checklist is "anyone on the team." Not necessarily, people that have been trained. There needs to be more detail and orientation with the instructions. 

For example, if I were to explain commenting, I would specifically say, "look for the green button at the bottom right of an issue thread that says "Comment" as opposed to "comment on the issue".

2. The checklist has many spelling errors. Please spellcheck before sending the next pull request.

RedCap map:
1. Does not follow the template. Please review the shapes and colors. Dark red is used to connect to a new map. The end of the flowchart should be a pill shape instead of a rectangle.
2. Instruction flow order needs to be reviewed.  For example, you can't create a VA RedCap account without already being at the VA RedCap website. Try out the instructions in the order that you have them and see if you can follow it in order.
3. Need instructions on how to create a full project - including instruments and user roles. Instead of leading up to the "project button". This map should allow someone to create a full survey on their own.

**Comment by ritahitching** [comment]
@lijenn do you want to chat briefly about this today? thanks

**Comment by ritahitching** [comment]
@staceypark thanks for feedback on RedCap map.  I'm moving comments to #682 and revise.
@lijenn has reviewed the template and did not encounter any problems with the instructions, but I'll add more steps.
thanks

**Comment by staceypark** [comment]
@ritahitching thanks for trying to cross-ref the correct issue and moving the comments. I wasn't sure where you guys were tracking the map.

Could you edit your comment to say #622? #682 is the r21 Group Modeling Building manuscript

**Comment by ritahitching** [comment]
@staceypark done 
> @ritahitching thanks for trying to cross-ref the correct issue and moving the comments. I wasn't sure where you guys were tracking the map.
> 
> Could you edit your comment to say #622? #682 is the r21 Group Modeling Building manuscript

**Comment by lijenn** [comment]
checklist is completed, just needs to be reformatted in pull request number 129 on lzim/mtl by 9/25.
