### ISSUE TITLE
8/7: Team PSD Bookdown Manual: Define standards for headers within .md files & checklist for standardizing format of .md files

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#1364]
Hypotheses:
- Headers of the Bookdown Manual and additional Resources/Guides should include most crucial information to know first that is necessary for orientation to Team PSD and the 2.0 Process
- Week 2/3 MVP & Prototyping:
QIICS and newest onboarding members described that platforms such as MS Teams, GitHub, and the 2.0 process are either the most difficult to understand and/or needs better contextual information. 

--------------------------------
**Define how to use a Level 1-5 headers in a standard way &  checklist for how to review existing resources**

- [ ] Checklist for how to review existing resources to conform to a consistent TeamPSD style and standard use of Markdown for the manual
- [ ] Define how to use a Level 1-5 headers in a standard way
- [ ] YAML will be removed when knitted and Level 1 Header needs to be the first item in each of the documents
- [ ] NOTE: Consitent w/the #hqhuddle week of 4/20/2020 we'll keep YAML headers in the GitHub original source material, they are removed when knitting using .Rmd 
- [ ] Review of the specific documents that are in the manual (between Rita, Jenn, Jane, & Debbie).
- [ ] Team PSD members can use an RProject for knitting "teampsd_bookdown.rproj"
- [ ] Ultimately, we we also add the bookdown RProject to Team PSD in "teampsd_manual" folder.

**Comment by lzim** [comment]
Thanks @ritahitching and @lijenn 

I edited the **title** according to the **SOP** and add the _MTL_ resource, in this case: **Team PSD Manual**

**Comment by ritahitching** [comment]
FYI @lijenn 

Cross reference
- [ ] Issue #1192 Team PSD Manual
- [ ] Issue#1364 5/15 task Team PSD Bookdown Manual: Define header level standards & checklist for review of online resources

**Comment by lzim** [comment]
@ritahitching and @lijenn 

Hi 👋 Just checking to make sure that you know that my goal is that we'll have **Team PSD** specific rules (i.e., examples) for standardizing the **Team PSD Manual** as a book, to go with the generic descriptions of heading levels that @ritahitching posted above.
- The top has to be H1.

So, it might be something like

# H1: Team PSD Manual
## H2: Processes & Platforms
### H3: Lucid 
#### H4: Checklist for Scheduling Meetings

Or, something like that?
That's what I'm hoping folks will think through, the **Team PSD Manual** specific rules to replace all of the generic information in the right hand 3 column of the table above.

**Comment by ritahitching** [comment]
@lzim thanks for feedback - I created 2 tables for the **headers** for **Team PSD Manual** and **Team PSD Documentation**

FYI @lijenn 

# Size of headers options

## Team PSD Manual

Header Size | Description | Markdown Code | When to use | Location | Number of instances
:-- | :-- | :-- | :-- | :-- | :--
H1 | Largest | # | Team PSD Manual | Top of document | 1 max
H2 | Medium | ## | Team PSD Project Management | Throughout | As needed for Section headings
H3 | Small | ### | Team PSD Processes & Platforms | Throughout | As needed for Subsection headings
H4 | Smaller | #### | Team PSD Resources | Throughout | As needed for Subheadings
H5 | Smallest | ##### | Example LucidMeetings | Throughout | As needed for Subsection headings
Standard | Written Text |   | Example LucidMeetings Checklist | For all text | For all other text


## Team PSD Documentation

Header Size | Description | Markdown Code | When to use | Location | Number of instances
:-- | :--| :--| :--| :-- | :--
H1 | Largest | # | Title of document | Top of document | 1 max
H2 | Medium | ## | Section headings | Throughout | As needed for Section headings
H3 | Small | ### | Subheadings of Sections | Throughout | As needed for Subsection headings
H4 | Smaller | #### | Subheadings of Subsections | Throughout | As needed for Subheadings
H5 | Smallest | ##### | For individual Headings | Throughout | As needed for Subsection headings
H6 | Written text |   | For documentation writing | For all text | For all other text

**Comment by lzim** [comment]
Morning @ritahitching @branscombj @dlkibbe @lijenn ☕ 

This doesn’t follow the TOC of #1192, unless you would like to make recommendations to further reorganize the manual for the team to consider (??). 📖 
- Also, we confirmed in our SOP that recording this detail here in the TASK card is problematic for **verifying the #1192 requirements** for the **master document card** in one place. 
- So, I will post also post this on #1192.

Unless you are recommending a re-org, the **3 main sections of the manual** excerpted below would all be the same header level (as they are in my original TOC, and as column headers in the Table that we’ve been reviewing to go with the TOC on #1192)
- That is was I showed in **my example above** as well from 3 days ago, these 3 main section would likely **H2** if the title “**Team PSD Manual” is *H1.**
- NOTE: _However, my question for @anthonycpichardo about this, is whether this list should actually all be H1 based on how the Bookdown knit works - can you let us know?_
A. Project Management 
B. Processes & Platforms
C. Resources

Then, we what need, as I said in my comment above was **Team PSD** S**specific rules for organizing any manual document in the same way.** 
—-
REMINDER: **The problem this task is meant to solve is that the documents being knit together in the manual all apply the H1-H6 headers in their own unique ways “as needed” (like your table says) and there is no guidance available to define how they should be applied so the Team PSD manual is effective for learners.**
- So, @ritahitching using my example above, what would define the **effective standard use** of sub headers across all the documents in the **Team PSD Manual.**
- I think @branscombj and @dlkibbe if you reviewed the documents you would easily see what I mean, and could make recommendations that would standardize.
- We started with headers, but once that’s sorted out, we can also add **standard icons** or other visual standards that will make the manual easy to use.
—-

To provide even more detail that my example above, would the order be:
- H1 Team PSD [depending on Anthony’s answer]
- H2 Project Management _or_ Processes and Platforms _or_ Resources (would it say this? Or would it be broken down by organize the information effectively within the column)
- H3 **All Team PSD** vs **Facilitate Workgroup vs....(etc but this would be Workgroup level) 
- H4 Overall Flow **maps** for what we’re talking about
- H5 **Checklists**

Team PSD Manual | Top of document | 1 max
-- | -- | -- | —
H2 | Medium | ## | Team PSD Project Management | 
H3 | Small | ### | Team PSD Processes & Platforms | 
H4 | Smaller | #### | Team PSD Resources |

I’m also not sure that we need _any_ columns that describe what Header and Subheaders generally are (e.g., “smaller”), just the Team PSD rules that we can use to clean up the manual documents so that they can be reviewed, trained on, and understood all together as a book (manual).

**Comment by ritahitching** [comment]
So, @ritahitching using my example above, what would define the effective standard use of sub headers across all the documents in the Team PSD Manual.

# Size of headers options Team PSD Manual
Header Size  | Markdown Code | When to use | Location | Number of instances
:--  | :-- | :-- | :-- | :--
H1  | # | Team PSD Manual | Top of document | 1 max
H2  | ## | Team PSD Project Management  or Team PSD Processes & Platforms or  eam PSD Processes & Platforms| Throughout | As needed for Section headings
H3  | ### |  Example LucidMeetings| Throughout | As needed for Subsection headings
H4  | #### | Checklist Lucidmeetings | Throughout | As needed for Subheadings
H5  | ##### |  Written Text | For all text | For all other text

**Comment by anthonycpichardo** [comment]
>Unless you are recommending a re-org, the 3 main sections of the manual excerpted below would all be the same header level (as they are in my original TOC, and as column headers in the Table that we’ve been reviewing to go with the TOC on #1192)
That is was I showed in my example above as well from 3 days ago, these 3 main section would likely H2 if the title “*Team PSD Manual” is H1.
NOTE: However, my question for @anthonycpichardo about this, is whether this list should actually all be H1 based on how the Bookdown knit works - can you let us know?
A. Project Management
B. Processes & Platforms
C. Resources

Hi @lzim @ritahitching @lijenn  The chapters are knit individually and then become the book, meaning every markdown document that we include will be it's own Chapter with it's own H1 header at the top.

Rita (hope i'm not putting words in your mouth) and I discussed and are making the recommendation that we go through the resources that we would like to include and consolidate documents into a larger more complete Chapter for their topics. i.e. Markdown documents related to Github get consolidated and become the "GitHub Chapter" as opposed to "Creating an Issue" and "making a pull request" being separate chapters.

Rita's outline above shows the recommendation for what the Table of Contents document would then look like.

**Comment by ritahitching** [comment]
Discussion HQ next steps
- [ ] Template on how to use headers for individual documents (e.g. see and say guide examples)
- [ ] Suggest possible consolidation of individual markdown files into chapters

**Comment by ritahitching** [comment]
# Team PSD Project Management￼
## Chapter 1: Learn About Team PSD
Explanation of Team PSD, principles, vision, mission, purpose, workgroups, members, roles, org chart,
### 1. 1 About Team PSD
- Guiding Principles
- Vision & Mission
- Org chart
### 1. 2 Team PSD Workgroups
- VAPOR
- EES
- Facilitation
- Co-investigators
- Qant
- Qual
###  1.3 Team PSD Collaboration
- NC-PTSD
- OMHSP
## Chapter 2: Team PSD Workgroups
Explanation of Team PSD workgroups
2.1 ### VAPOR Workgroup
Explanation and details of VAPOR role within Team PSD, VAPOR members
2.2 #### VAPOR Members
- Donald DC Barlow
-  Leroy Edwards
-  Ren Kramer
-  Erik Ontiveros
- Tammy Thompson
2.1.3 #### VAPOR Meetings
Explanation of specific details of Team PSD and VAPOR monthly meeting
2.2. EES
2.2.1 ### EES Workgroup
Explanation and details of EES role within Team PSD, EES members
#### EES Members
- Casey Grysen
- Fawn Powell
#### EES Accreditation & TMS

2.3 Facilitate

## Chapter 3: Team PSD Collaboration
Explanation and details of PSD collaborating centers
### - NC-PTSD
### - OMHSP
#### Members of NC-PTSD
- Craig Rosen
- Shannon Wiltsey Stirman

**Comment by lzim** [comment]
> Please see a visual example of the use of the headers for the Team PSD Manual
> 
> # Team PSD Project Management￼
> ## Chapter 1: Learn About Team PSD
> Explanation of Team PSD, principles, vision, mission, purpose, workgroups, members, roles, org chart,
> 
> ### 1. 1 About Team PSD
> * Guiding Principles
> * Vision & Mission
> * Org chart
> 
> ### 1. 2 Team PSD Workgroups
> * VAPOR
> * EES
> * Facilitation
> * Co-investigators
> * Qant
> * Qual
> 
> ### 1.3 Team PSD Collaboration
> * NC-PTSD
> * OMHSP
> 
> ## Chapter 2: Team PSD Workgroups
> Explanation of Team PSD workgroups
> 
> ### 2.1 VAPOR Workgroup
> Explanation and details of VAPOR role within Team PSD, VAPOR members
> 
> #### 2.1.2 VAPOR Members
> * Donald DC Barlow
> * Leroy Edwards
> * Ren Kramer
> * Erik Ontiveros
> * Tammy Thompson
> 
> #### 2.1.3 VAPOR Meetings
> Explanation of specific details of Team PSD and VAPOR monthly meeting
> 
> ### 2.2 EES Workgroup
> Explanation and details of EES role within Team PSD, EES members
> 
> #### 2.2.1 EES Members
> * Casey Grysen
> * Fawn Powell
> 
> #### 2.2.2 EES Accreditation & TMS
> 2.3 Facilitate Workgroup
> 
> ## Chapter 3: Team PSD Collaboration
> Explanation and details of PSD collaborating centers
> 
> ### 3.1 NC-PTSD
> #### 3. 1. 2 Members of NC-PTSD
> * Craig Rosen
> * Shannon Wiltsey Stirman
> 
> ### 3.2 OMHSP

**Comment by lzim** [comment]
@ritahitching  @branscombj @dlkibbe @anthonycpichardo @staceypark 
- I edited the title based on coaching from @lijenn that the key idea of defining standards for **_within_ the existing set of Team PSD manual .md files** would be clarifying.
- I think it will also really help to focus on producing the **_how to_ instructions for divvying up the .md files so folks can apply the standardization rules** to all of them (after the standardization decisions are finalized by the group).

Thanks all! Very exciting 🏎️

**Comment by ritahitching** [comment]
Hi All
@lzim @anthonycpichardo @anazariz @branscombj @dlkibbe @lijenn @staceypark 

I'd appreciate your insightful thoughts and helpful ideas on the draft documents below defining how to use Level 1-5 headers in a standard way & the companion checklist for how to review existing resources.  Will you please review the following:

- [ ] Draft guide for all TeamPSD documents that defines how to use a Level 1-5 headers in a standard way  [available here](https://github.com/lzim/teampsd/blob/rita_2020_04_27_issue_1364/resources/bookdown/header_style_guide.md) 

**While you review please consider:**

1. Does the choice of headers make sense?
2. Are the examples given sufficient to provide a guide on choice of header?
3. Are the examples of 'before' and after' using the style guide helpful?
4. Any helpful /unclear parts?
5. Any edits / additions?
6. Alternatives to current layout or content?

- [ ] Draft checklist for all TeamPSD documents that defines how to review existing resources [available here](https://github.com/lzim/teampsd/blob/rita_2020_04_27_issue_1364/resources/bookdown/style_guide_document_checklist.md)

**While you review please consider:**

1. Does the checklist make sense?

2. Are there any missing sections?

3. What other information/links may be useful?

4. Any helpful /unclear parts?

5. Any edits / additions?

6. Alternatives to current layout or content?

**Comment by ritahitching** [comment]
Questions:
What to do when we only have very scant content?
What to do when files only have images and no text??
Why is  YAML needed?



|Header|	Markdown code|	Use|	Reasoning |
| ------------- | ------------- |------------- | ------------- |
|YAML headers|Markdown|	Every document|	|
|H1	|.#.	  | Use for document title                     | |
|H2	|.##.	  | Use for document sub section headers       | |
|H2	|.##.	  | Use for titles of maps	                   | |
|H1	|.#.	  | Use for new title in a longer document	   | |
|H3	|.###.  | Use for numbered steps 	                   | |
|H4	|.####.	| Use for general text you want to hi-light	 | |

**Comment by ritahitching** [comment]
@lijenn this is issue is blocked by the #1192 and the MVP process.
I recommend we keep this issue open.

**Comment by dlkibbe** [comment]
@lijenn @branscombj and @dlkibbe reviewed the David Anson rules list. We have listed below the rules that would likely need to be included in the Markdown Linter. Let us know your thoughts. Thanks.
MD004
MD005
MD007
MD009
MD010
MD011
MD012
MD018
MD019
MD020
MD021
MD022
MD023
MD024
MD025
MD026
MD027
MD028
MD029
MD030
MD032
MD033
MD034
MD035
MD036
MD037
MD039
MD042
MD044
MD045
MD047

**Comment by lijenn** [comment]
Thanks Debbie & Jane for those rules!

**1. While looking through the rules, I noticed the majority actually relate more to how we use Markdown as a team.** 

For example, MD039 - Spaces inside link text:
It is linting for this spaces within the brackets of texts being used for hyperlinks.

It would lint for anyone that uses Markdown hyperlinks like this:
` [ Google ](https://www.google.com/) ` turns into [ Google ](https://www.google.com/) 

and force them to conform it to writing it like this:

` [Google](https://www.google.com/) ` turns into [Google](https://www.google.com/) 

However, those spaces within the brackets won't change the outcome of the hyperlink since it still produces the hyperlink to Google the exact same way. 

I'm wondering if we would want to include such rules that would **force folks to write in a certain style of Markdown**.
This is leading me to think if a Markdown guide should be created based on these restrictions or if rules like so should be more flexible and not include them as the outcome is the same. 

In that way, any Markdown guide we find online could be used, as long as the output being produced is the same. This may lead to some discrepancies/odd looking markdown code based on the user, but maybe we should think about this.

**Hypothesis/Assumption:**
- Do rules will need to match with the Team’s current understanding and use of Markdown? How would this be affected by having a Markdown guide or "googling for yourself" how to do write something in Markdown?
(e.g MD004 There are multiple ways to make a bullet list, but forcing a certain rule in the markdown linter to lint for a certain markdown style may cause issues if not everyone uses markdown the same way)

**2. Rules & Style guide will need to be consistent in how we want the sections like in the TeamPSD Manual output via GH Actions Bookdown**  
Notice Ch. 2, 3, 4 are sectioned off differently based on the how markdown is coded in their guides, see chapters at https://lijenn.github.io/teampsdprototype

Markdown file Chapters on lzim/teampsd
Ch. 2: https://github.com/lzim/teampsd/blob/master/resources/training_guides/teampsd_guiding_principles.md
Ch. 3: https://github.com/lzim/teampsd/blob/master/resources/training_guides/github/new_file.md
Ch. 4: https://github.com/lzim/teampsd/blob/master/resources/training_guides/github/github_guide.md

We may want to see how Markdown files outputs look like on Bookdown and think about the markdown style guide/template depending on the types of Markdown files we have (e.g. training guides, vingettes, see/say guides, etc. and what to ignore if we want to ignore files) while also simultaneously thinking of the linter rules..

May be related to #1370 SOP & Checklist for using Bookdown

**Comment by branscombj** [comment]
@lijenn  I think @dlkibbe and i were assuming that those were not optional styles but required code for producing the given formatting, so the linter would find incomplete coding instances.

**Comment by lijenn** [comment]
@branscombj @dlkibbe No worries! I just realized how it might sound that way in the documentation of the rules.md for the linter...

I ended up testing some of the rules (I just copied the coding instance they mentioned in the rules into a github comment just to see the output by previewing it) and some rules with the **Rationale** (it's the section that comes at the very end of each rule) **saying**: Violations of this rule can lead to improperly rendered content, **actually still renders properly**...

e.g. [md005-inconsistent indentation for list items at the same level](https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md005---inconsistent-indentation-for-list-items-at-the-same-level):

```
* Item 1
  * Nested Item 1
  * Nested Item 2
   * A misaligned item
````

&

```
* Item 1
  * Nested Item 1
  * Nested Item 2
  * An aligned item
````
Both of these still give the same output, despite the slight indentation, that MD005 is saying could cause rendering/output issues.

But it's okay regardless since we can choose the rules that we do want to include. 
I think the **next step** is that we should actually see if what they are saying in the rules.md will lead to improper coding or will not. 

Because we will definitely **want the rules that do catch improper markdown coding** so all our markdown files render properly. But for **rules that seem optional/force Markdown users to code in a forced style**, maybe we will want to think that through depending on a **Markdown Guide for TeamPSD**.

**Comment by lijenn** [comment]
#1192 TeamPSD 2.0 Manual 

1. Introduction
Rationale: Introduce the purpose of this manual, explain who it is for, what purpose does it serve, why it is here, & what is here. Could essentially be the README.md file.

2. TeamPSD SOP/Guiding Principles
Rationale: Understanding team governing rules and values come first to set a tone for the team and workflow.

3. Team PSD Team/Workgroups
Rationale: Orients to different types of workgroups and representative leads of workgroups.
Could we refer to https://mtl.how/teams?

4. (#1426) MS Teams (note: some functions not available in VA teams)

Rationale: Orient to our main communication platform to learn how to comments/questions answered in real time from the team or partners.

5. Lucid Meetings (to be phased out with VA MS Teams, should we still include this?)
Rationale: Understand how the teams functions their workflow around existing meetings. 

6. GitHub + ZenHub
    - TeamPSD 2.0 Organizational Flow Map
    - List of Repositories
    - Project Trackers
    - ZenHub Flow + Map
    - Documentation Flow Map
    - Files (style convention, add, edit, delete)
    - Templates for files and issue cards (lzim/teampsd)
    - Communicate with Markdown
    - Create an Issue
    - Create a Branch
    - Make a Commit
    - Open/Merge a Pull Request

Rationale: I know the team rules, who is a part of the team, how to communicate with the team. 
Where do I go to start viewing tasks/how do I make contributions? Start with the hub platform that centers our workflow.

TBD for the remaining chapters? I think the above for 1-6 may be the most critical for general orientation at the moment.
7. OSF
8. Zotero
9. ....

**Comment by lijenn** [comment]
Headers were defined for teampsd manual, following the 3 level headers shown in Bookdown and use of verb + noun for chapter titles and subsections.
