### ISSUE TITLE
MTL Technical Manual

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1478]
## 1. Link to the document, add relevant team members to the card, and add workflow decisions.
- [ ] mtl.how/manual

## 2. Link to issues that must be edited in the document in the **issue_tracker** and **feature_tracker.** _(use the # for the link to the issue)_
- [ ] #1802 add error message and screenshot to admin section 

### dev-test-prod qa cycle
wk2
- [x] QA DEV: Stacey and Jenn - First draft of MTL Manual and bookdown guide #1734
bookdown guide: https://github.com/lzim/teampsd/blob/gh-pages/README.md
mtl manual: https://mtl.how/manual
**Edit chapters structure to include guides directly**

> Decision re: #1478
> 1. mtl.how/manual 
> 
> 2. MTL Red
> 2.1 learner
> 2.1.1 session01_see + teams cheatsheet
> 2.1.2 session02_see + data cheatsheet etc.
> 2.1.3 session03_see
> ...
> 2.2 facilitator
> 2.2.1 session01_say
> 2.2.2 session02_say
> 2.2.3 session03_say
> ...
> 2.3 admin
> 
> 3. MTL Blue
> 3.1 learner
> 3.1.1 session01_see
> 3.1.2 session02_see
> 3.1.3 session03_see
> ...
> 3.2 facilitator
> 3.2.1 session01_say
> 3.2.2 session02_say
> 3.2.2 session03_say

- [ ] QA TEST: decided at hq_workgroup on 2/4/2021 that we will train on this next week at hq_workgroup.
- [ ] QA PROD: Jenn to add guide as a chapter to the Team PSD manual at https://mtl.how/teampsd_manual

wk3 
- [ ] Jane - QA Test MTL Manual #1679

wk4
- [ ] MTL Facilitate Meetign - QA PROD

Related issues:
- [ ] #1624 VA Teams cheatsheet
   Blocked by - [ ] #1705 Co-planning documents on teams/sharepoint
- [ ] #1798 update facilitator cheatsheet
     - Document card is #1523 facilitate cheatsheet 

## 3. Team Review
- [ ] Fidelity - check with Lindsey
- [ ] Data UI - check quant_workgroup
- [ ] Sim UI - check with model_workgroup and/or sim_workgroup

## 4. Review and Open Pull Requests _(use the # for the link to the pull request)_
- [ ] Check the draft for typos
- [ ] Check or open a pull request for the document edits

## 5. Review and/or Update Graphics
- [ ] Screenshots
- [ ] Gifs
- [ ] Logos/Icons
- [ ] Links

## 6. Dependencies
- [ ] Make sure that any edits you make that need to be added to **depend_product** are tracked (e.g., _MTL Video_)

## 7. Close Pull Requests
- [ ] Request review and/or close open pull requests for the document

**Comment by lijenn** [comment]
MTL Manual TOC draft from Jane:
@staceypark 

1. Background
a. The problem
b. The need
c. The solution (briefly)
2. Development
a. Values throughout
b. Scientific grounding, theory
c. Process of development, ongoing development
d. Versions/variations
e. Funding sources
3. Overview
a. Structure, timing, mechanics, communications
b. Facilitation approach, goals, mechanics of co-facilitation
c. Participation who, how many, expectations
4. Facilitation
a. Tools/resources
b. MTL Blue at-a-glance guide Phase/Session title/learning objectives/MTL Video links
c. MTL Red at-a-glance guide Phase/Session title/learning objectives/MTL Video links (?)
d. Fidelity
5. Platforms
a. GitHub
b. Teams
c. Data UI
d. Menu
e. Sim UI
f. Epicenter
g. TMS
6. Accreditation
a. Professions supported
b. Requirements
c. Process
d. Make-up/extra review with videos
7. Help
a. Participant questions – who/what/how
b. Facilitator questions – who/what/how
8. Further study
a. MTL products (papers, posters, presentations)
b. Additional readings/external background resources
9. Research
a. R-21
b. IIR
c. R-01
10. Acknowledgements 
11. References

**Comment by staceypark** [comment]
@branscombj Thanks for working on this! @lijenn shared this with us and it looks like a great start.
 Could you clarify the difference between the content in 4a (tools/resources) and 5 (platforms)?

**Comment by staceypark** [comment]
@lzim @lijenn @branscombj 
Following the plan for  *MTL* technical manual vs. *MTL* fidelity manual, here's a new TOC draft for the technical manual:

1.0 Introduction - Short blub on purpose, how to use manual, etc.

2.0 Learner
2.1 MTL Red vs. Blue map
2.2 MTL Blue at-a-glance guide with
- Phase
- Session title
- learning objectives
- SEE guide link
- MTL Video links
- Resources
2.3 MTL Red at-a-glance guide 
- Phase
- Session title
- learning objectives
- SEE guide link
- MTL Video links
- Learner-only Resources

3.0 Facilitator
3.1 MTL Blue at-a-glance guide with
- Phase
- Session title
- SAY guide links
- Facilitator-only Resources
3.2 MTL Red at-a-glance guide 
- Phase
- Session title
- SAY guide links
- Facilitator-only Resources

4.0 Admin
3.1 MTL Blue at-a-glance guide with
- Phase
- Session title
- Admin-only Resources
3.2 MTL Red at-a-glance guide 
- Phase
- Session title
- Admin-only Resources

**Comment by lzim** [comment]
This looks good to me @staceypark

**Comment by lzim** [comment]
@lijenn and @staceypark 

Given that we expect that will, be separate "Books" should we start two separate document cards?

"MTL Facilitator Manual"
"MTL Technical Manual"

I've edited the title to reflect, which this one is.

**Comment by staceypark** [comment]
note: for most recent instructions 3/4 see main card on this document
