### ISSUE TITLE
Nov epic wk?? Add Reset buttons to the facility.xlsx workbook

### ISSUE THREAD

**Issue by anazariz** [lzim/teampsd#1582]
### Check off requirements to verify progress through feature_tracker.
- [x] 1. **DEFINE in work_breakdown**
  - [ ] a. **what & why** - **written definitions of requirements** in a **numbered checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** requirement definitions an **existing team meeting.**
  
Add reset buttons to the vizDiag, vixEnc, vizHF, vizMeas tabs with functionality similar to their respective Data UI counterparts.  

  Task Cards:
  #
---
- [x] 2. **DESIGN** in **operations_to_do** and **research_to_do**
  - [ ] a. **what & why** - **_MVP_ of design** of requirements in a **algorithm map, wireframes or design** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** design **asynchronously** or an **existing team meeting.**

Design was verified between @lijenn and @anazariz as well as asynchronously within the Teams/Quant WG during the week of 11/9/20. 

The buttons should:
1-reset the location of the chart
2-reset the graph area within the chart 
3-reset the filters to their startup (when the workbook is initially opened. This means that even if the filter items were changes by clicking on the chart lines, they should be replace with their original filter items
4- charts should not cover the buttons
5-there needs to be consistency between the 4 tabs in terms of the the charts are located, their proper width and height

  Task Cards:
  #
---
- [x] 3. **DEVELOP** in **under_development** 

#1518 - Complete

  Task Cards:
  #
---
- [x] 4. **TEST in functional_test**
  - [ ] a. **what & why** - **TEST requirements** using **testing_checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** via TEST **asynchronously** or an **existing team meeting.**
  
Completed by @anthonycpichardo 
Completed by @lijenn 

  Task Cards:
  #
---
- [x] 5. **PROD in done**
  - [ ] a. **what & why** - **_DOCUMENT_ feature** using **document_tracker** for the **5 D's.** 
  - [ ] b. **date & who** -  **DELEGATE**
    - [ ] **describe_learners** [Jenn & Rita]
    - [ ] **detail_facilitators** [Jane & Debbie]
    - [ ] **document_team** [Anthony]
    - [ ] **disseminate_scientists_va** [Anthony]
    - [ ] **depend_products** [hq & ees]
  
  Task Cards:
  #

Propagation completed on 11/20/20
---
- [ ] 6. **closed** - fully documented, trained and ready for the next release.

**Comment by anazariz** [comment]
@anthonycpichardo this ticket needs to be closed please.
