### ISSUE TITLE
February 

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1651]

**Comment by lzim** [comment]
**8AM Workgroup Leads 2/22/21**

- [x] **sim_ui_workgroup** @jamesmrollins & @lijenn working on #1591 as most urgent
- [x] **new issues** are increasing.
- [x] **ANDON** (S.A.C.) - @ dd to Team PSD Manual
- [x] **All Hands to 10AM** on Tuesdays @staceypark tomorrow and moving forward
- [x] **tt_teampsd email** ...rethink this **user** - in **mar_epic** on wk1, wk2, wk3, wk4 (Schedule of all _MTL Teams_ that week) @lijenn #1737
- [x] **Decision re hq_workgroup:**  
- _Fx end of week review & set up next week:_ 
- 11AM quant_operations - 
- 12:30PM cross-cutting section hq_workgroup 
- 1:30 hq_huddle 
- [x] **Decision:** **"CDW O.H.I.O as Foundation" for Stories 1, 2, 3 - R01, R21**
- **Staff Turnover** - Dependencies (slack capacity); Libby as Health Economist said she had a HERC data source (wk1 mar_epic - but @anthonycpichardo will ask Libby about what HERC would use for this...cc quant_workgroup.
- [x] **Story 1** **monthly (?) training time** - Team members cross-cover - Send people to when their skills are keep up with asynchronous/synchronous...mar_epic 8AM Workgroup @dkngenda

**Comment by lzim** [comment]
**8AM Workgroup Leads 2/22/21**

- [ ] **R01 quant_workgroup** will close COB 2/22 - LZ PROD QA 2/23
- [ ] **R01 Protocol** @lijenn will work to get the example for supplements to @lzim @staceypark on 2/23
- [ ] @lzim will work on this on Wed 2/23

**Comment by anthonycpichardo** [comment]
**2/25/2021 HQ Meeting Agenda**
- [ ] mtl_operations#3 - Missing RN Data and SW Phone Grid in Data UI
- [ ] Where is the Team Folder Request coming in from? Is it a team folder request or access to another team's folder?
- [ ] Team folder **permissioning issues** where users who have been added **can't access the folder**
- [ ] We'd like the ability to **change where access requests get sent** - preferably mtl.help  (folder to be determined)
- [ ] We may re-engage Ash's Outlook prototype
- [ ] R01 Protocol Paper
- [ ] R21 method approval
- [ ] Authorship App Update
- [ ] David taking over Story 1 during the March epic
- [ ] Story 6 Development with Contractors

Stacey + Jenn
- [ ] - Facilitator Fidelity Ratings
- [ ] - Provider Surveys
- [ ] - Provider List from 570 (missing permissions)
- [ ] - MTL Manual 
- [ ] - Set up of Emails Draft

**Updates**
- [x] James has done some work on stories 7 & 8
