### ISSUE TITLE
wk2 due 2/9: Data SEE/SAY Guides (Red Part 1 & 2, Blue S2 & 3)

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1678]
Update all see say data guides based on the facility and data testing from Quant and James.
Note: All resources need to be done by 2/9 - we are going over data at Facilitate meeting & LZ going over resources with Kansas City (Blue)
   - will they want to see SIM?

David's feedback:
 - [x] Update s2 gif to not display all the folders in visn 21 palo alto site.
  
James's feedback:
### mtl_red_part_1_say.md

- [x] 1. bullet 3 states: "A web version of Excel will open on your screen, showing your facility's data in charts."

What actually happened:  A directory in BISL is displayed which indicates a 663_facility.xlsb file is displayed.

 - [x] 2. bullet 2 states: "If you do not see a team folder, request a team folder above."  

Observation:  It is not clear what "folder above" means. On first entry into the system, there wouldn't be a team folder, or is someone else creating it?  Is it created when the team goes through co-planning?

 - [x] 3.  Time Stamp - Team Learning Priorities - Script for Session 2, table needs to be fixed.

 - [x] 4.  "If the data is not loading or showing incorrect facilities/clinics, here's how to refresh" refresh procedure is not consistent with actual dialogue in spreadsheet.  

-  The second bullet indicates a "control" selection will be in the "Unhide" menu.  The only two selections presented in the spreadsheet were "drop down" and "Hidden."

- I think the problem is the first bullet instruction says, "To refresh your facility file's data, right click on any tab at the bottom of the Excel spreadsheet and select **Unhide..."  I think the user must actually navigate to the "Control" worksheet tab, select a facility in cell C2 on the top of the worksheet and click the "Refresh" button on the top of the page. Revealing the hidden tab is a function of the Propogate button according to the instructions on the worksheet. 

 - [x] 5.  We have been working in the beginning of the Say guide in the splashpage.  Then we transition back to BISL and then to the Data UI file.  Consider a more solid transition.  

-  Add "Go to BISL (or SharePoint Online).  Scroll to your team folder at the bottom of the page. Open the data_ui folder and open your data_ui file in Excel."

 - [x] 6.  Regarding #4. Go to the ClinicSelection tab. Use columns C-H . . . 

-  Third bullet says, "Note that this will pull all clinics used in the last two years (including de-activated clinics: denoted by "ZZ"). You can see the de-activated clinics in column I."  Consider, "Note that this will pull all clinics used in the last two years, including de-activated clinics (denoted by a "ZZ" prefix). You can also see the de-activated clinic's inactivation date in column I."

- Forth bullet says, "Follow the instructions in Box A2."  Consider, "Follow the instructions in cell A2." Or - draw a box around the cell and keep the "box" language.  The word "cell" is used in the two bullets that follow bullet 4

Note:  Consider color coding the buttons in cells B3 through B6.  It took me a few minutes to find the "add all" button.  Also consider capitalizing the names of the buttons in the instructions in cell A2. Also, consider left-justifying the cell and bulletizing the instructions in A2, it will be easier to read.

### mtl_session02_say.md

 - [x] 1.  Under #2, bullet 2, says, "Team files are in team folders. If you do not see a team folder, request a team folder above."  Where is above?

 - [x] 2.  Under #2, is says, "There are two types of View options at the bottom of the spreadsheet. __________________ (Team Lead's name) Will you please click through them, so we can see what each displays?"  What view options? Do we mean to say, "There are two views available in each worksheet, a graph and a table." Or, "There are data view options available in the tabs at the bottom of the spreadsheet." 

 - [x] 3. Under heading "All data is sortable and filterable so that the team can transparently see how the charting you do all day becomes VA data." 

- Regarding # 2, "For each "viz" chart, you can filter on location and clinic name (upper left) to zoom in to the clinic or VISTA clinic/"grid". (During intersession prep facilitator should fill-in the rankings of the highest priority viz that should be emphasized during the team meeting. Follow the team's lead "live" during the meeting, but be prepared.)."  

- The options on the chart are "divisioname" and "locationname" and are inconsistent with " . . . location and clinic name (upper left) . . ." 

 - [x] 4. Under "If the data is not loading or showing  . . ." this needs to be corrected.

 - [x] 5. Under heading, "To create a fresh data UI file, go through Steps #3-5."

- Regarding #4. Go to the ClinicSelection tab. Use columns C-H . . . 

- Third bullet says, "Note that this will pull all clinics used in the last two years (including de-activated clinics: denoted by "ZZ"). You can see the de-activated clinics in column I."  Consider, "Note that this will pull all clinics used in the last two years, including de-activated clinics (denoted by a "ZZ" prefix). You can also see the de-activated clinic's inactivation date in column I."

- Forth bullet says, "Follow the instructions in Box A2."  Consider, "Follow the instructions in cell A2." Or - draw a box around the cell and keep the "box" language.  The word "cell" is used in the two bullets that follow bullet 4

 - [x] 6.   Time Stamp - Team Learning Priorities - Script for Session 2, table needs to be fixed.

**I also recommend we go through a lint process together after I delete the heading punctuation rule.  It may speed up our editing process if I can share my lessons learned with you.**
