### ISSUE TITLE
march_2021

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1707]

**Comment by staceypark** [comment]
**To be discussed Monday at WG Leads for March Epic:**
- [ ] Authorship App Update
- [ ] How does teams chat integrate with shared mtl help inbox permissions

**Comment by lijenn** [comment]
@anthonycpichardo #1808  to look at security differences for bugs:
- [ ] VA GH enterprise
- [ ] Private Repos (mtl_team_tracker) --> issues here will show up in the ZenHub board

- [ ] Security features for GH organizations for collaborations/mentees

**Comment by staceypark** [comment]
3/15 8am Workgroup leads:
- #1807 we are iceboxing this for now
- #1802 @anthonycpichardo working on this week
- #1691 moved to april epic
