### ISSUE TITLE
april_2021

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1764]

**Comment by lzim** [comment]
**April (wk1)**

- [x] More resumes have been received - Discuss at Team Time.
- [x] Story Mapping 1,2,3,4, Retreat this afternoon.
- [x] Story 5 - Communication w/BISL
- [x] Story 6 - Liberty starts this week.
- [x] Lindsey has Stanford interview at 1:30PM.
- [x] Facilities - Testing and mtl.help@va.gov schedule review - Nazarizadeh, Afshin  will test this week's site.
- [x] R01 Survey & Manuscript
- [x] MTL Facilitation Manual
- [x] Please schedule 1:1s on Thursdays after hq-workgroup
- [x] No later than 1:1 need all proposals for research funding.
- [x] Need to prepare for next week's co-I meeting.
- [x] Email Lindsey for vacation time, send it to timekeeper (PAVIR/VA), put it in mtl.help@va.gov & mtl.info@va.gov
- [x] #1691 - Major Emphasis for Manuscripts
Rollins, James M. (Praxis Analytix LLC)  will complete this week and provide reviewer card to Lindsey.

**Comment by lzim** [comment]
**April (wk1)**

8AM workgroup

- [x] ZenHub Reports
- [x] Velocity by workgroup
- [x] All Stories 
- [x] Stories 1 & 4

_If you're leading a story, please update the story before the workgroup meeting it will be discussed below:_

**Cleaned up w/standing meetings and Issue #s.**
Story 1 & Story 4 - team_time on Tuesday
Story 2 & Story 3 - with Anthony during his time this week.
Story 5 - Briefly Ash's update quant_operations on Thursday
Story 6 - Support Workgroups at 2PM on Wednesday
Story 7 & 8 - Sim UI Workgroup

STORY 1 & STORY 4: "Co-Author a Published Team PSD Manusccript" If we align the 10 steps of our manuscript tracker  (https://mtl.how/manuscripts) with sprints in 6 month roadmap it ensure that manuscripts will be regularly subumitted.  STORY 4: "QA/GH Standards in Team PSD Manual"  deliver sprints on time without stress.  Each grant has 3 cardsin the https://mtl.how/documents
Column 4:
dissemination_va_scientists
Compliance(steps 1-6)
Analysis(steps 7a, 7b)
Dissemination(step 8) The second part of dissemination is covered in OSF, manuscript_tracker, etc.]
 
5 MAJOR GRANTS
1.R21(research)
2.R01(research)
3.IIR(research)
4.SAMSHA(system of care, education not research)
5.HEAL(pending)
 
Compliance Steps 1-6 are needed before any research commences.
Grant-Specific Aims
Clinical Trials Registration(if CRT)
IRB
ORD
DART
All of steps 1-5 are renewed annually for progress. Any changes have to be submitted for review.
 
Analysis
Steps 7a & 7b are "prior work" categories needed before any manuscripts can be submitted.
 
7a. R Notebook - [ ] a. How to use Notebook (packages, etc.) - [ ] SQL -> R Data Prep & manupulation - [ ] Study Design (site selection, operational definition, covariates, baseline data, etc. - [ ]quant:Aim Descriptive Statistics;qual:coding - [ ]quant:Aim Measurement Analyses (EHR issues, psychometric properties of surveys or scales);qual:codebook refine (inductive/deductive) - [ ]quant:Aim Inferential Statistics;qual:coding analysis
- [ ] Planned exploratory analyses
- [ ] Post hoc analyses
7b. GitHub Branchfor each Grant.
 
Dissemination
8. OSF Project for each grant 
for each conference presentation  for each manuscript)

Step 9- All relevant manuscripts from any grant build from all of these resources. 
https://mtl.how/manuscripts
https://mtl.how/authorship

**Comment by dkngenda** [comment]
April (wk4 )

Workgroup leads 8:00 am:

- We don't want to see an issue sitting in "needs triage column" of the mtl.how/bugs tracker. (unless it comes through overnight.
- We should all be leading the 8am workgroup meetings on Monday.
- Everyone should be familiar with the board so as to cover for each other.

**Bug tracker**

# 1887:
- Providers not showing up in the data UI. Providers not in the same sta3n facility
-  This kind of data was not planned. It will require a structural change in the data. 
- This will be a feature request since we will be required to shown data at sta6a. Currently it's at sta3a.
- @anazariz  will create a ticket as a feature request. Associate the issue with the starter card.
- card moved to validated actions (ranked)
#1841 
- This is a feature and will be completed next week by @lijenn 
# 1806:
- Bug resolved already.
# 1691
- @jamesmrollins will sort it out before end of the day. i.e needs to be reorganized for each experiment recreation.
#1868
- Will be discussed at facilitated workgroup on 20th 
#1864 
- Image looks much more crisp. Issue is closed
- 
**Feature tracker:**
#1282 
- Review the card on Wednesday research.
#396
@lijenn 
- Need to update the 9 clicks at the top. 
- This needs to be completed before session 5 (second week of May)
- Title needs to be updated.
#323
- Needs to be brought up during  Qual WG meeting.

#1023 
- CRM being handled with a different set of cards.
- We will need a mastercard of open issue related to CRM
- This card will be closed and anything CRM related moved to #1299
#1242 
- Need to be reviewed on Quant WG on Wednesday.
-  Needs to be addressed together with 1241,1242, 1282
#1276 
- No current LSV current requirements.
- Needs to be closed. No outstanding LSV requirements.

**Decision:** Individuals to identify Other stale tickets on feature tracker close them

**Comment by staceypark** [comment]
4/22 hq meeting

mtl.how/bugs
#1887 - put into icebox & feature_tracker
#1905 - need clarification from Lindsey 
#1913 - Jenn has provided order of impacted sites to fix. Ash will investigate.
#1903 - David & Jenn will test Friday 4/23


ZenHub reports
- cumulative flow: new issues are rising but we've increased our rate of closure to match
- control chart: last 10 issues ~3.5 weeks to close

**Comment by dkngenda** [comment]
4/26 Workgroup leads

**Bugs:**

**Comment by staceypark** [comment]
## hq 4/29
### bugs
#1868 
#1935 - this will affect the monday team meeting. Jenn & Stacey have not run into this issue. 


## next week's meetings: 
### 5/4 facilitate meeting - Review how to run team data table and shape expectations that this is NOT an HQ task, but part of each facilitator's workflow to know how to do.
