### ISSUE TITLE
wk1_may-epic: Prepare r21_psy_jccp Chart Comparisons

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#1964]
Prepare side-by-side comparisons between Sim UI model outputs against those reported in the tt3 report for team 1 of the r21_psy_jccp.

- [x] Validate team data consistency between tt3 report and Team Data file.
- [x] Recreate experiment in Sim UI using tt3 report values.
- [x] Identify variables for comparison from tt3 report and prepare a report with side-by-side comparisons of data.
- [x] Analyze information and determine if results are consistent.

**Comment by jamesmrollins** [comment]
Hi @staceypark and @lzim 

## Results
- Results **do not appear consistent** between legacy data and new model.
- While graph curve shapes are consistent, the magnitude of scales is significantly different (see diagram below).
- The team data is confirmed to be correct, judging from the values reported in the OSF report and the team data file used for this study.  Although "New Patient Start Rate" is not a listed value on the legacy team data table.
- The experiments have been recreated, including QHFD text in the PROD instance for this team.  They can be easily deleted if desired.

![image](https://user-images.githubusercontent.com/30132017/117067718-39108300-acdf-11eb-96af-b5850e83571e.png)

[psy model analysis copy.pdf](https://github.com/lzim/teampsd/files/6423888/psy.model.analysis.copy.pdf)

## Original Model Comparisons
- I loaded up the psy_v18_2018_11_06 model to see if the results matched what is in the OSF report.  I found differences there too, versus what is reported in OSF.  There may be an older model in @tomrust ' archive that may produce the desired results.

![image](https://user-images.githubusercontent.com/30132017/117070480-a40f8900-ace2-11eb-8bf3-f1cc9f5a89cd.png)

![image](https://user-images.githubusercontent.com/30132017/117070804-1aac8680-ace3-11eb-891a-14712f118af9.png)
