### ISSUE TITLE
june_2021

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1966]

**Comment by lijenn** [comment]
**Bug Tracker:**
- @anazariz and @staceypark tested and closed #2019 
SPReferrals Tab in Data UI and Team Data Table
   - **Related: #2032: SP Module in SIM giving errors**, we have not tested have real team data with SP floor parameter sets (documentation to be tracked in #648). 
      - We opened up the SPParams tab in the team data table for SP referrals for MH and JB's team, C11-D15:
      - ![image](https://user-images.githubusercontent.com/59668647/121042389-7d70c200-c768-11eb-97f4-1bd28665bc81.png)
      - Story: How to not lose Veterans from PC to GMH or any of the other flows where a patient could flow to. There are few episodes of care.
      - Time between someone is registered as a high risk flag and stepping to a different level of care, this will be a low flow of the system in SP module to continue continuity of care. 
   - This led to a re-thinking of the logic for the SIM and SP module. 
   - **Column D: Episode Count - When the model produces the Value/Constant parameters, Episode Counts were not counted --> noisy/infrequent data.**
   - Column D Episode Count shows how frequently the Column C Value/Constant is occurring.
      - ![image](https://user-images.githubusercontent.com/59668647/121044272-3edc0700-c76a-11eb-9b7a-a00c8e9fea1e.png)
     - SP Params has Column D - trying to count the times and define distribution of how people flow across care (think about Amazon product rating system).
    - #2019 Tracking the GMH/SMH selection: We need to update the data UI as well for the team to the new working one as well as the new team data table that is produced. 
    - C34 has a Value/Constant as 0, but the definition requires it to be at least 0.1, James noted that he got a floating point error when running this file in the Sim.
    - ![image](https://user-images.githubusercontent.com/59668647/121052349-26bab680-c76f-11eb-8cf8-a44c6df0d197.png)
       - **Episode of Care Gap Threshold - Need to be discussed thoroughly between Facilitators and Team Lead:**
       - If a veteran hasn't come in 9 months, it's a new episode of care. 
          - Normal if PC/PCMHI.
          - Highlighted Definitions: ![image](https://user-images.githubusercontent.com/59668647/121053859-a39a6000-c770-11eb-9d01-c6c63a4bdcfa.png)
          - By definition, the median is below or under the 50%. For a PCT team for example, this would be described as: Half of their patients are above and half are below for my PCT team. And At the 75th percentile, it takes 27 weeks for them to go from high to low in PC/PCMHI, 37 weeks for GMH, and 25 weeks for SMH. 

- NOTE: **Values versus Constant language in Team Data Table** - need to re-visit use of Constant in Column C of SPParams tab in Team Data Table @lzim @branscombj @staceypark @lijenn @anazariz 

- #2033:

**Comment by lzim** [comment]
**hq_workgoup 6/10/21**

**Bug Tracker** https://mtl.how/bugs
- [ ] #2032 - James will promote tomorrow to Sim UI. Jenn posted a comment
- [ ] Nazarizadeh, Afshin will create an issue card for his portion of the Data UI 0.10 work.

**Comment by dkngenda** [comment]
**workgroup_leads 6/14**

#2054 - Sim UI Responsive Design https://mtl.how/manual 

- Document in MTL Manual 
- Train at Facilitate Workgroup.

**Comment by dkngenda** [comment]
**Feature tracker:**

Trackers are plural - bugs, features, documents, manuscripts

- [ ] #2016 - Remove default  part of v19 of nevermore
- [ ] #2015 - ICEBOX - We decided not to develop this outside of Power BI development effort.
-  #1899 - Closed as inconsistent with the logic of the SPReferrals tab to have PC/PCMHI listed in the dropdown.
 
- [ ] #2065 Support Workgroups Jane - Column D of SPParams tab populate w/"NA" rather than leave it blank.
      - #2065 - In the Team Data Table, there is no query for cells D34-45. It is clearer to have "NA" in these cells for facilitators to be clear that there isn't supposed to be any data there.

- [ ]  Story 2 - #1613 jun_epic List in order of priority when they'll be developed.
- [ ] David add authorship_app to feature tracker - new supports and testing for asynchronous work

**Calendar**
 - Green = coplanning
 - Purple = prep
- Red = Live red
- Blue - Live blue

**Comment by lijenn** [comment]
HQ Workgroup Thurs. 6/24:

https://mtl.how/bugs 
1. #2083
@staceypark and @lijenn will provide additional detail on this bug ASAP so that @jamesmrollins may be able to communicate it to DEV since it's Hiren's Friday.

2. ANDON and propagations

**ANDON**
**Scope (S)**
- Impact by time
- Don't forget prep

**Alert (A)** - Tues **facilitate_workgroup**
Prep fresh data

**Communicate (C)** 
- Fresh "clinics" (domain expertise, local expertise) for their prep
- v18 -> v19 of Nevermore 3 bugs
#2016, #2066, #2065

- Jenn - 1 team ~30 minutes
Data UI - "viz" tabs "data" tabs
Team Data Table

- **Lindsey/QIICs - 1 ~1.5 hrs**
Data UI Clinic Selection & Team Data Table

**SCOPE OF THE WORK**
4 active NIH teams
5 non-active NIH teams
14 co-planning
23 * 30 = 16 hours of work to get things refreshed everywhere after an ANDON.

**Comment by staceypark** [comment]
For missing Jan-Jun viz & data Enc:

#2089  - Resolve missing encounters in Facility file

@anazariz Once this issue is fixed, ping @lijenn and @staceypark on #2090 for Test QA.
Then propagate in this order:
1. Marcia's site where the issue was first identified
2. All other facilities engaged in this wave
3. Ping @lijenn @staceypark on #2098 for PROD QA
4. Rest of the country
5. Ping @lijenn @staceypark on #2098 for PROD QA.
6. We will also see if this resolves the issue of mismatched encounter data between dataUI and facility file identified by Marcia.
 
For missing MM Params on Marcia/Debbie's site #2097 
- Marcia and Debbie think it is because there are no prescribers among the providers on the team.

Next Steps:
1. Stacey & Jenn will work on updating the testing QA routines for the monthly facility and dataUI propagation (#626, #627)
2. Ash will propagate facility (#2091, qa #2092) and dataUI on July 1st (#2094, qa #2095)
3. Re-Produce dataUI & team data table for NIH Sites (#2049)
4. SPParams Kansas city (#2093)
