### ISSUE TITLE
july_2021

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1993]

**Comment by lijenn** [comment]
wk2 jul_epic 8am WG Meeting 7/12;

- Howard OOO until Wed.
- Ash is out sick

Next Steps to Resolve migration from legacy Data UI to Power BI:
- See comment in 8am WG meeting from @lzim  at 8:43am to see list of partners we are reaching out to help us with the data UI.

Ash is out sick today and will continue with focusing on migration from legacy platfrom to Sharepoint Online & Power BI.
- De-bugging - Review w/Bug Tracker. Bugs have prevented propagation of national data.
- Co-planning VA Sites - Found that 4/1 was the last update of national data.
- 9 NIH sites Data UI & Facility file may not be current through end of June, but don't have working data tools.

#manuscriptmonday
- David L. uploaded the systems thinking exemplars; GMB manuscript.
- Debbie Methods, Lindsey Intro, Dexter count of all the feedback acceptance.
- Jane may be open to a manuscript
- Timeline - Stacey
- Authorship App - David N. to fix Stacey's testing.

Bugs:
- #2115 
- @anazariz did you submit the YourIT helpdesk ticket for what you assessed to be a CDW issue? As a reminder, please put it into teampsd > help_desk_tickets once you do
- @staceypark will crosswalk facilities with missing HF data with Cerner rollout sites

Features:
- #2107 - We will move forward with the co-popup despite 508. We will allow concurrent pop-ups on the Sim for all the models.
- #2110 & #743 - Move forward with checking the QHFD text by default.
- #2104 - Discuss at SIM UI Wed. 7/14

**Comment by lijenn** [comment]
Discussed Thursday 7/15 HQ Workgroup:

Bug Tracker:
- #2119 - Data UI bug seems to be resolved by turning auto-save.
@lijenn 
   - In terms of documentation it needs to go into:
- [ ]        - data UI propagation
- [ ]        - data UI propagation QA
- [ ]        - SEE guide
- [ ]        - SAY Guides facilitator and learner Red & Blue guides
- [ ]        - data cheatsheet
- [ ]        - Provide guidance on Sharepoint Online
- [ ]        - "Data UI Propagation.docx" File #626 mtl.how/documents
- [ ]        - Facility file #627 "Splashpage_monthly_update_readme.docx"

**Comment by dkngenda** [comment]
7/16/2021

**Calendar**

- Kansas City Issue: Lot of hours of rework with Kansas. 
    - Still finding missing data for May and June in facility file (might also be the case for data UI?). (Data might be in sunset tables?)
    - We have all the 589 data in all other VA dashboard so the issue is the query. 
    - No progress so far on query.  
    - For more details check 7/16/2021: RE: MTL: hoping to arrange a brief meeting.
    -  MTL data UI seems to be consistent with PCT dashboard.
    - Differences in values between the MTL data UI measures and PCT measures (or other VA dashboard) is not because of invalid of data but a difference in definition of cohort measures. MTL looks at what happens within 3 months after a patient starts while other dashboard might be looking at what happens to a patient over a longer period. _MTL emphasis is on patient flow_
    - Increased fluency will reduce stress (is it a bug or not?).
    - Prep- meeting is the common source of expensive rework. Need to clearly communicate to facilitators of this meeting ahead of time to avoid expensive rework. This might affect AIM 3 of IIR grant (i.e cost of running MTL).

**Comment by anazariz** [comment]
wk3 jul_epic 8am WG Meeting 7/22;

Discussed at HQ

#2115
@dkngenda  is working on  - @anazariz setup David with copies of the 4 tables Enc, Meas, Diag, and HF so that the production tables are not impacted when David runs portions of the code (with these renamed tables). 

#2140
@anazariz created the card for the PBI Selection tab card. Progress will be added to this card.

**Comment by anazariz** [comment]
wk4 jul_epic 8am WG Meeting 7/26

Agenda
1. bugs (David) - https://mtl.how/bugs
2. features (Lindsey) - https://mtl.how/features
3. manuscripts (Stacey) -

https://mtl.how/manuscripts

#2115 Ngendahimana, David K.  testing
589 facility case file
Pulled the last data of HF entry before 06-01-2021
Produced the Splash Mothership again

Next Steps:
David will now review Team PSD > quant_workgroup > final_data files

"Data UI" Nevermore v23 online .xlsm >
Turn on the Developer Tab in Excel (to mix of VBA & SQL that runs the HF query)
https://mtl.how/document #626 & #627 Nazarizadeh, Afshin  These instructions need to be in "Data UI Propagation"

### Looked at the bugs first

#2139

David analyzed the reasons for vizHF chart cutoff in Facility 
David will now inspect the Data UI to see the difference between the two. Data UI does pro 
Ash walked David through how to turn on the Developer menu in Excel

So the task is to compare DATA UI vizHF and Facility vizHF to see what the differences are. 

@staceypark 
Turning on Develop Tab on Excel for the first time:FileOptionsCutomize RibbonMain Tabs categorySelect "Developer" on the right sideOk (Ash to add these to issue cards 626 and 627)

**We will ask for CDW team's help is David's analysis does not produce results.**

#2093
Decided to skip since it was discussed on Thursday

#2102
Decided to skip since it was discussed on Thursday
References #1961 and #2112

#2132
@jamesmrollins - in test (has a test card - will be tested this week)

@lzim discussed with @jamesmrollins the requested feature: "the ability to pull up your saved dialog, Jane came up with a better idea to just have the name produced by your selections..."

@lijenn 
Jane's featue request for automatic naming: NEXT VERIFY DATE: feature_req definition Automatic simulation naming · Issue #2134 · lzim/teampsd (github.com)
NEXT VERIFY DATE: feature_req definition Automatic simulation naming · Issue #2134 · lzim/teampsd
Check off requirements to verify progress through feature_tracker. 1. DEFINE in work_breakdown a. what &amp; why - written definitions of requirements in a numbered checklist on the master_feat...
