### ISSUE TITLE
aug_2021

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2120]

**Comment by lzim** [comment]
### hq_workgroup wk4 jul_epic

**August Epic - Weekly Sprint Planning** - Lead, support
 
- [ ] **Special Issue: Stacey (manuscripts overall) & David (analyses) & Lindsey (hopefully, writing most of the time)**
wk1
wk2
wk3
wk4
wk5

- [ ] **Hiring: Stacey & Lindsey & David**
wk1
wk2
wk3
wk4
wk5

- [ ] **Onboarding Meghana: Stacey & David**
wk1
wk2
wk3
wk4
wk5
 
- [ ] **Co-planning: Jenn & Lindsey**
wk1
wk2
wk3
wk4
wk5

- [ ] **Dynamics UAT: Jenn & Stacey**
wk1
wk2
wk3
wk4
wk5

- [ ] **Scheduling/Purchasing Resources/ADM Funds: Jenn & Stacey**
wk1
wk2
wk3
wk4
wk5

 
- [ ] **Story 13: David & James (James could lead, need to co-determine with them**); support on specific tasks from hq and Anthony; Lindsey working on help from PERC and w/the Detail (more updates expected by COB today).
wk1
wk2
wk3
wk4
wk5

#### Other August Tasks

- [ ] Email Emily Evans about union notification - Stacey
- [ ] Complete Stanford OTL - Stacey
- [ ] Coordinating with co-investigators about HEAL grant re-submission - Lindsey 
- [ ]  Record facilitate videos that were requested - Lindsey 
- [ ] Get VISN System Specialists going on MTL Videos 
- [ ] Cost aims - Stacey & Libby & David
- [ ] Set up RedCap data pipeline/workflow - David

**Comment by lzim** [comment]
### hq_workgroup 7/29/21

**DECISIONS:**

- [ ] Ash, David & Stacey - Transition planning for Research ORD databases and CDW on B02 Research Server on Monday.
- [ ] Return to Story 13 Power BI on Tuesday - We may want to bring to team_time Power BI questions that we have for Ash using the files created today and put in Team PSD > quant_workgroup > power bi.

**Comment by lzim** [comment]
### 8AM Workgroup Leads

**Monday** - quant_workgroup Videos, Documentation and Training
- [ ] **Review a the documentation #626 & 627 - Run the July propagation for VA sites** 
- [ ] **Research: CDW, ORD databases, ensuring access and documentation of the code.**

**Comment by lzim** [comment]
**hq_workgroup 08/05/21**

_Facilitator Fidelity Ratings_ Should we track substitutions?
DECISION: Yes #2163

**#214 Research - R Notebook for every grant; Data pipeline** (23 points)
- [ ] Provider Survey (RedCap)
- [ ] Facilitator Fidelity (RedCap)
- [ ] Cost Aim (ZenHub)

- [ ] Authorship App (Shiny Server) #212

**Comment by lzim** [comment]
**8AM Workgroup Leads**

- [ ] #2167 - Data are now shared in individual worlds, and syncing Epicenter and GitHub.
- Removing the Team Data Menu is a big change, but recommended to avoid conflicts among users.

**Comment by lzim** [comment]
### hq_workgroup 8/12/21

#### Special Issue
- [ ] research/212 authorship app @dkngenda 
- [ ] working titles #2180 @lzim

**Comment by lijenn** [comment]
Monday 8am WG on 8/16:
- LZ is out on Mon & Fridays until the end of aug_epic (she is in office every Tues-Thurs., 6 total days).
- LZ out wk1 sept_epic.

**PRINCIPLES from HQ last Thursday:**
1. Hub Board by weekly sprint, every week but the first.
2. Set up the next monthly epic wk4 hq_workgroup.
3. Review the monthly epic & wk1 spring at first 8AM of the month.
standing workgroup meetings - start by opening the weekly sprint for that workgroup.
If we open the board at 8AM and it's not up to date. We'll pick this up at this workgroup_meeting.

**mtl.help operations workgroups**
- https://mtl.how/bugs
- https://mtl.how/features
- weekly sprint for that workgroup

**mtl.info research workgroups**
- https://mtl.how/manuscripts
- weekly sprint for co-I_workgroup

**WEEKLY SPRINT**
Anchoring conversations in showing/documenting on "the board."

**Points, Sprints & Pipelines:**
- We average ~ 80pts/Epic.
- If we are triaging cards (e.g. moving a card from aug_epic to the sept_epic):
    - adjust the 9-clicks
    - and move the card from the Priority Epic to Upcoming Epic.
    - update the weekly sprint
- Sprints: Remove all previous sprints if it was not worked on during that week, update the sprint that the card is being worked on.
- David: How will ZenHub count Days to Completion with the Sprint removal?
- Stacey: To get a more accurate Days to Completion, we need to focus on accurately scoping and prioritizing cards sitting in Priority Epic.
Move cards from Priority Epic into the proper pipeline and always keep sprints up to date.

**bug_tracker:**
- #2178 - @lijenn to help with testing.
- #2177 - Fixed and closed!

**feature_tracker**
Feature Tracker:
- Only keep epic in the title name for due date if they are not being worked on/not scoped out.
- #1299 to track Liberty work, will close by end of aug_epic since Go_live is Sept.
- #396 closed and new effort for oct_epic is in #2183
- #2130 - @jamesmrollins to clean up and update this feature card 
- #2112 - @jamesmrollins to also review and clean up this feature card
- @dkngenda to move issue cards that can be on lzim/teampsd repo and not lzim/research (e.g. Power BI cards can be on lzim/teampsd, keep research cards only on research repo)

**manuscript_tracker**:
- Reminder that we will need to scope out our work for the special issue manuscript

**CRM UAT:**
- @hsnyder2 working on updating the UAT guide to incorporate testing for the Notes feature (e.g. If you are are the session detail for S7, grab S7 template in the Files tab of facilitate_wg channel and update the notes/check boxes)
- 2 items in guide that were in dev. is being worked on/done
- These features will be updated in the QA instance tmrw morning.
- @hsnyder2  will post the exact time in the UAT Thread in facilitate_wg channel

**Comment by staceypark** [comment]
## 8/23 Monday 8AM WG

### OOO
- LZ out Monday and Friday this week, and all next week

### mtl.how/bugs
- #2185 - @jamesmrollins fixed the issue @staceypark identified where zeroes are being identified as BC. In PROD.
- #2178 - will update to PROD with larger release at EOM

### mtl.how/features
- #2187 - review scope and decision at wed sim_ui workgroup meeting
- #2130 - review priority order at wed sim_ui workgroup meeting

### mtl.how/manuscripts
- re-test authorship app during manuscript monday meeting 

### CRM
- Request for restriction/double check pop up for facilitators to not accidentally complete admin tasks
  - @apisano0920 clarified that the d365 app right now is not distinguishing what are admin vs. facilitator tasks in the checklist. Liberty will need to add fields for the d365 app to distingue the tasks.

**Comment by staceypark** [comment]
# 8/30 Workgroup Leads

### 9/1 Wednesday
- Meghana first day 
- UAT Go Live 

### Meetings
- [ ] Monday interview w/RA
- [ ] 8/31 Tues Facilitate meeting UAT testing
- [ ] 9/1 Wed Quant Research - Setup data pipelines teampsd/#2170; research/#219; research/#218; bug & feature tracker on lzim/research repo research/#229
- [ ] 9/2 Thurs Quant Operations - Setup VINCI workspace research/#228

**Comment by lijenn** [comment]
## 9/2 HQ:
Note: We are out on Monday due to Labor Day.
David is out next Thursday.
- We created a https://mtl.how/research_bugs and https://mtl.how/research_features tracker
- We are 83% done from closing out issues for wk5 of aug_epic, with remaing cards set to close.
- Is @lzim able to delete the extra workspace on ZenHub without deleting the original/existing workspace??

**Comment by lzim** [comment]
@staceypark and @lijenn 
Can you remind me, do we close the epic card?
Or, does that mess with all our data?
