### ISSUE TITLE
wk4_aug_QA_test: SIM UI Features - Multiple Issues July Epic Release

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#2121]
# QA Check Instructions

- See the conditions below.  Set these conditions prior to validating the simulation feature.
- The issues are referenced for your convenience.  When offering feedback, be sure to reference the issue number and condition (i.e., Regarding condition 1 (#2106))
- Offer QA feedback in this thread.
- Be sure to consider any documentation that may be required to be created or updated.

## Conditions

1. Given a team set up that includes _ind and _team sharing the same root with a saved experiment with simulation reset, from a _team session. (#2106)
2. Given a team set up excel spreadsheet from CRM. (#1968) (#2104)
3. Given an AGG session that requires Balanced Mode discussion and comparison. (#2107)
4. Given a sim session that requires discussion around a chart that has percentages as a unit of measure. (#2117)
5. Given an experiment that is saved in a _team group (#2105)

### Condition 1 (reference issue #2106)

- [x] The saved experiment is listed in Experiment Maintenance dialogue in the _ind world.
- [x] The saved experiment is listed in the Experiment section of a new simulation session.
- [x] The saved experiment is available for display in the compare experiments dropdown in the Outputs and Text section.
- [x] The charts display the experimental variable values appropriately.

### Condition 2 (reference #1968 and #2104)

- [x] From the Dashboard/Team Setup/Add/Drag-n-drop dialogue, the excel spreadsheet is uploaded.
- [x] The team is setup using the root provided by the spreadsheet combined with _team and is available in the team listing.  _Please note the test CRM xlsx download did not contain a team vision, so this feature is not coded yet._
- [x] Roles in the team setup are correctly assigned.
- [x] The clinical roles are available and correct on the Team Roster.
- [x] Each individual was a their own world in the _ind group.
- [x] A shared facilitator world is setup with the _shared group.  The group has cofacilitators assigned along with @lzim, @staceypark, @lijenn and @jamesmrollins standard assignees.  
- [x] The shared group is available from the dashboard team dropdown under the team root name.
- [ ] Drag-n-drop instructions are included in the Team PSD manual. 

### Condition 3 (reference #2107)

- [x] Both the base case (BC) and the "i" information (i) popups are displayed simultaneously for all experimental variables that have a BC popup (CC/MM/AGG).
- [x] The base case popup has a portrait orientation for easy comparison with Team Data Table.

### Condition 4 (reference #2117)

- [x] When viewing any chart in any module, the chart displays a "%" sign for all dmnl variables.

### Condition 5 (reference #2105) 

~- [ ] An experiment that has been saved and the sim reset, is available in all _ind, _team and _shared groups that share the same team root name.~
@lijenn is adding new qa tests since we've updated this feature to be only 1 directional to prevent confusion among Learners and Facilitators seeing a ton of experiments and the ability to identify which experiments are Team experiments versus their own world experiments.
- [x] 1 directional: Team groups experiments show up in Ind and Shared groups (text and variables all show up)
- [x] Ind and Shared group experiments do not show up in each other's worlds and the Team world
- [x] Able to easily identify experiments with the same name and determine which experiments are theirs

**Comment by lijenn** [comment]
Hi @jamesmrollins, 2 questions:

1. **For Condition 1** - #2106
I can't seem to get this feature to work in my test team world "jenn_shared_world_test" with how we currently name our team data table files (i.e. it worked when I had a test team data table file named "jenn_shared_world_test.xlsx" but not the below.
- Does the feature account for the bolded part here in a team data table file's name?
    - jenn_shared_world_test_**all_without_SP_2021_04_26.xlsx**

2. **For Condition 2** - Specifically #1968 
Is there a button or visual indicator from the Dashboard/Team Setup/Add/Drag-n-drop dialogue to drag-n-drop an excel sheet for the team setup? Not seeing anything new here:
![image](https://user-images.githubusercontent.com/59668647/126340195-a168fa8c-3d84-4b37-89bf-1a4ee31d6124.png)

**Comment by jamesmrollins** [comment]
Hi @lijenn.  This QA Test isn't scheduled until next week, so many of the features you are testing are not available yet.

**Comment by lijenn** [comment]
Need to fix regarding:

Condition 4 (reference #2117)
- [ ]  When viewing any chart in any module, the chart displays a "%" sign for all dmnl variables.

Found a dmnl in AGG for MM - Work Pressure:
![image](https://user-images.githubusercontent.com/59668647/127535996-cbe8bd77-1c29-4df2-b285-0fef06dca99e.png)

**Comment by lijenn** [comment]
### Feedback and Qs for Condition 2 (reference #1968 and #2010)

**1. Can we rename or change the language for the drag-n-drop for Team Set up?**
Worried Team Data might be referred to as the Team Data Table file since they sound similar. 
What about something like this so it matches the blue header's name:
   - "Drag your exported Team Setup file from the CRM HERE" or even just
   - "Drag your Team Setup file HERE"
![image](https://user-images.githubusercontent.com/59668647/127919856-ce76ad1a-bf39-4323-91f3-914e30c93856.png)

**2. Can we add an indicator to let the user know that their file was added in the drag-n-drop?**
Currently, when I drag my exported file to the area, it does not tell me that I have successfully put a file there.
At the least, I'd at least like to see the name of the file that I uploaded, something like this:
![image](https://user-images.githubusercontent.com/59668647/127920999-c7a38e93-a922-40ec-89f9-747c3d5205ef.png)

**3. Possible Future Release - Any way we can upload more than 1 Team Setup file to set up more than 1+ team at 1 go?**
Could look something similar to this pic:
![image](https://user-images.githubusercontent.com/59668647/127921262-a891b4b5-ca4c-4bf7-8b36-52633485c000.png)

**4. Unable to "Edit" or view the team created from the export unless I click "Add" another team first.**
- See attached excel file that I used to test this condition. I took the sample export file that you had revised to include the columns needed for the Sim UI. I just changed the name of the team and added myself and Stacey as Facilitators and changed our roles, added your praxis email as Team Member, and added your VA email as Team Lead.
- I cannot view the team that I just created from the export unless I click "Add" first to add another team. I exit the "Add" new team and then I am able to view the exported team from the "Edit" button.
- I also noticed that once the file is finished exporting, I get this error in the console:
![image](https://user-images.githubusercontent.com/59668647/127923296-17cb4a9c-921c-445e-8e98-4026d5f023b3.png)

**5. Not all members from the exported file are added.**

Only you seem to show up?
Could it be related to the console error from 4., might have something to do with Stacey and me and the worlds assigned to us in Test?
![image](https://user-images.githubusercontent.com/59668647/127923618-58480a04-b17e-4451-9ff9-ffd46f98d612.png)

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire .  Please take a look at the feedback above from the UAT.  This is reference to issue #1968 and #2110.  @lijenn makes a good observation and improvement suggestions: 

- [ ] Provide feedback when a file is uploaded and ready for transport, 
- [ ] Change the dialogue to say "Drag your team setup file here" 
- [ ] we should incorporate before release by the end of this week.

I like the multi-file upload idea as well, but I will create an issue card to track that separately.  We have to conserve hours between now and the end of the fiscal year.

More feedback to follow tomorrow.

**Comment by lijenn** [comment]
Thank you @jamesmrollins! Unfortunately I'm still experiencing a variety of bugs with the export.

Otherwise, I have checked everything else that looks good besides these that need fixes:

### Condition 3 (reference #2107)
- [ ] Both the base case (BC) and the "i" information (i) popups are displayed simultaneously for all experimental variables that have a BC popup (CC/MM/AGG).

**Cannot open the (i) and (BC) pop-ups simultaneously for Learning Mode header in CC & MM:**
![image](https://user-images.githubusercontent.com/59668647/128447622-8199dcbd-d073-4665-a479-425a79b3482a.png)
![image](https://user-images.githubusercontent.com/59668647/128447885-ce264c57-3da1-4137-92f0-6c719df44832.png)

----------------------------------------------

For reference, this is the **team root for the feedback below: 123_jenn_issue2121_attempt2**

### Condition 1 (reference #2106)
I'm not sure if the qa check boxes reflect this feature? I might be mistaken since I thought #2106 is purely related to the team data table file showing up in all _team, _ind, and the _shared worlds. But the test cases all refer to experiments.

If the qa checks are referring to the team data file, I am still experiencing the same bug I got with Lindsey's and Nearhoof's ind worlds documented here, where deleting a file from individual world, deletes from all of the other member's individual worlds. 

And vice versa, uploading the team data table file in 1 individual world will add to all the other member's individual worlds.
See condition 5 below as adding the team data table file was also a part of that process.

### Condition 5 (reference #2105)
- [ ] An experiment that has been saved and the sim reset, is available in all _ind, _team and _shared groups that share the same team root name.

Having some trouble this one, below were the steps I took to test this:
1. I first set up 2 experiments in the _team world after adding in the Team Data Table file.
2. I did not see the Team Data Table file get auto-added into the _shared or _ind worlds.
3. I add the team data table file to Debra's _ind world.
4. I start a new session in the _ind world and do not see the 2 experiments in the blue Experiment dropdown header.
5. I run and then save and reset an experiment in the _ind world, then I see the 2 experiments from the _team world + the exp. I just ran:
![image](https://user-images.githubusercontent.com/59668647/128451330-1df8bc64-f528-429b-b6df-557ba147ff80.png)
6. I check the other _ind worlds and they now all have the team data table file auto-uploaded and all 3 experiments in the Experiments drop down and the Experiment Maintenance section.
   - Question: Did we want experiments from _ind worlds to show up in other member's _ind world? I thought we just wanted to have _team world experiements show up in _ind and _shared worlds. 
7. I delete the team data table file from one of the _ind worlds, this deletes the team data table file for all the other _ind worlds too.
8. No effects on _shared world. Team data table is not automatically added. 
Tried recreating step 3-5 for shared world and the experiments from the _team world (and _ind world, though I don't know if we want these to show up) still do not show up:
![image](https://user-images.githubusercontent.com/59668647/128451951-cb50dc5a-5508-43bb-b1c2-85bc7123198d.png)

Let's touch base tomorrow please!

**Comment by jamesmrollins** [comment]
## Findings from Joint User Acceptance Testing with @lijenn 8/6
@hirenp-waferwire

- [ ] Please confirm that saving an experiment anywhere within a _team, _ind, or _shared group will result in the experiment saving with all world of all groups sharing the same root.
- [ ]  we need to add the experiments to the dashboard dropdown.

![image](https://user-images.githubusercontent.com/30132017/128568213-df5dd36f-1ec4-475c-96b7-d4d520c6c4e9.png)

- [ ] Experiments do not call up text when loaded

![image](https://user-images.githubusercontent.com/30132017/128568406-4ae1bee0-db55-4737-9ae8-d92e31b7d65d.png)

![image](https://user-images.githubusercontent.com/30132017/128568543-7305e412-7be9-4f83-9f51-b599f2de7f93.png)

![image](https://user-images.githubusercontent.com/30132017/128568454-05c9f2f3-1ddc-452c-b490-f57735885d88.png)

- [ ] When an individual deletes or changes a team data name in the Team Data Dropdown Maintenance menu affects all dropdowns. Can we limit the changes to affect only that group_world?  **This is also happening in PROD and needs to fixed straight away straight away through break-fix.** Reference #2167

![image](https://user-images.githubusercontent.com/30132017/128569172-7c47176a-9d7d-45a6-a292-3c5ca33d0b56.png)

- [ ] See feedback in the thread above from @lijenn for other issues with feature upgrades.

**Comment by jamesmrollins** [comment]
Comment from WG Leads meeting 8/9.  

## Regarding the cached state of a user session
1. Will the small changes in the AGG model somehow disrupt a current, un-reset user session?
2. Is there a way to set up a test environment that will validate whether the update will mess up a user session?

**Comment by jamesmrollins** [comment]
@lzim @staceypark @lijenn 

## Results from Meeting with DEV Regarding Saved Experiments and Cached Sessions

1. **Any change to a variable name invalidates previous experiments (but we have workaround - see below).**  The name is the critical element of the variable as all code mapping is dependent on that name.  If a variable name is changed in any way, it will corrupt the mapping. 
2. We don't have the ability to import experiments from one server to another.
3. However, as a general rule there would be no testing required if we follow rule number one.
4. **Any post run, non-reset sessions will need to be saved and reset before we migrate TEST to PROD.** This way, when the session is loaded, it uses the new model fresh.  

## Workaround
1.  To be able to use experiments that our study participants have already saved and want to use, we are going to hard code the ability for the AGG model to read both the legacy and new variable names in the experiment data file. The user should not have an issue reading legacy experiments.
2. This can always be a workaround, but its complexity is directly proportional to the number of variables changed.   

## Lessons Learned
1.  @jamesmrollins needs to do offer more resistance to changing variable names!  This has happened multiple times and I really need to stop letting this happen - I am embarrassed 😣
2.  We should better coordinate release with PREP and TEAM meeting schedules (as we discussed earlier).
3.  Our planning should assume a save and reset of all active sessions prior to a release. This will be a good use of our News and Andon Alert systems. 
4.  The above does not apply to BreakFix.

**Comment by jamesmrollins** [comment]
## Regarding number 1 below
- We will need to coordinate the 29 August release to PROD, by having all users save and reset their sessions. 
- We should use the Andon alert system to alert users to the coming change and provide instructions.

> Comment from WG Leads meeting 8/9.
> 
> ## Regarding the cached state of a user session
> 1. Will the small changes in the AGG model somehow disrupt a current, un-reset user session?
> 2. Is there a way to set up a test environment that will validate whether the update will mess up a user session?

## Regarding AGG Experiments Saved Prior to Release to PROD
- @hirenp-waferwire will provide code that will read pre-release experiments with old "User Use Team Data" switch and accept the setting value for the new "User Balanced Mode" variable name.
- This will enable all legacy experiments to be used in the new release.

**Comment by lijenn** [comment]
Done and in Prod, thanks!
