### ISSUE TITLE
sep_2021

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2182]

**Comment by jamesmrollins** [comment]
Comments transferred from issue #2130 

## hq_workgroup 9/9

- [ ] By end of meeting finalize communication plan w/Liberty about UAT.
- [ ] #manuscriptmonday Sign up for office hours, Circulate by Wed COB the week before.
- [ ] Tech Lead Behavior Interview at 10AM Tuesday
- [ ] Tech Lead Behavior Interview today

**Wed Support WG:**

- [ ] Let James, Matt know they don't need to attend since we are still focusing on SIM UI

**Thurs Quant:**
- [ ] Keep focus on story 13 Power BI

**ZenHub Board:**
**1. Cumulative Flow**
   - We've closed around 1100 issues over a year or ~90 issues a month
   - operations bug & feature trackers are shared across a larger set of team members (i.e. facilitators contribute cards to this as well) than the ZenHub board
   - We had a dramatic increase in bugs (green line/New Issues) over the past few months.
   - ![image](https://user-images.githubusercontent.com/59668647/132771940-1b989418-bfa8-445c-866d-fc37bd3c2139.png)

**2. Control Chart**
    - We take on Average 45.7 days to close cards
   - Note the arrows which represent Outliers
   - We've closed around 1100 issues over a year or ~90 issues a month
   - Over the last year, 50% of issues were closed in 16 days or less.
   - We've moved 660 issues from new to closed or ~2400 points (~200 points/month)
![image](https://user-images.githubusercontent.com/59668647/132771240-3de28d46-b9fc-4783-996c-aa3ec4ab1674.png)
![image](https://user-images.githubusercontent.com/59668647/132771180-b39f8eb0-ddb0-4205-ba07-f92529b0e165.png)

**3. Burndown Report**
   - Shows how many points we scoped and are completing by sprint & milestone
   - This sprints report:
      - ![image](https://user-images.githubusercontent.com/59668647/132772425-5a71bf85-c47a-46ec-8e0b-08103631f99d.png)

**TeamPSD repositories:**
- mtl (public): this is where we send our learners and have our "production" level resources
- teampsd (public): "works in progress" repository where the majority of our operations work is hosted
- research (private): we cannot post manuscript/analyses related work publicly as journals will flag us for this, and this is our protected scientific ideas
- team_tracker (private): we do not want our notes about the teams doing our quality improvement project available to the public 
    - Dynamics CRM is meant to replace this

**Comment by lzim** [comment]
**8AM Workgroup Leads 9/13/21**

**Items for discussion from the Board*
- [ ] [wk2 sep_epic: UAT Usability Feedback - Filtering on the Activity Widget in Dashboard (related to 7.2) #2232](https://github.com/lzim/teampsd/issues/2232)
- [ ] [wk3 sep_epic randomize survey measures #2136](https://app.zenhub.com/workspaces/team-psd-workspace-5e4ac9bd8d388dfba6d9aef5/issues/lzim/teampsd/2136) @mnallajerla could work with @staceypark on this.
- [ ] [wk1 sep_epic: MTL VA Red Pre/Post Emails w/ Partner, Build, Apply #1176](https://app.zenhub.com/workspaces/team-psd-workspace-5e4ac9bd8d388dfba6d9aef5/issues/lzim/teampsd/1176) @mnallajerla could work with @lijenn on this.
- [ ] [wk1 sep_epic facilitator fidelity surveys for VA Red#2160] (https://app.zenhub.com/workspaces/team-psd-workspace-5e4ac9bd8d388dfba6d9aef5/issues/lzim/teampsd/2160)

**Comment by lijenn** [comment]
sep_epic

**8AM Workgroup Leads** 
- Lindsey to review the components of the R01 annual reports.

**Comment by lijenn** [comment]
sep_epic at **9/20 8AM Workgroup Leads**:
- [ ] Lindsey to review the components of the R01 annual reports.
- [ ] Tech Lead/SQL Programmer: DECISION to pause on the search 
- [ ] @lzim will talk to PAVIR recruiting about the post and whether to close or modify.
- [ ] @dkngenda focus on pulling 8 NIH year 1 EBP reach aim 1a/1b.
- [ ] We'll focus on progress reports & manuscripts for the next 5 weekly sprints.
- [ ] QA TEST - Park, Stacey D.  Aim 2 providers surveys


**Tues. Facilitate Workgroup**
- [ ] Fidelity Ratings (namely Tuesday team w/ Debbie & Claire and Thursday team w/ Jane and Marcia)
- [ ] Coplanning
- [ ] Go-Live updates

**Comment by mnallajerla** [comment]
**9/23/21 HQ Meeting** 

**ANDON #2257:**   

**AGG Group**  @jamesmrollins 
- Keep Data UI for Groups 1/6 calculate and time in hours. Rationale = standardize the fact that 1 hour provider time could have up to 6 veterans. 
- Change SIM UI from .25 to 1 hour 

_Will look like more group for active teams because the change is being made in the SIM._ 

**AGG Adjunctive** @dkngenda 
- Change Data UI from .25 hr to 1 hour
- Keep SIM UI at 1 hour. 

_Ok to change now because it won't impact any teams_

**Comment by lzim** [comment]
**For Discussion Monday 8AM Workgroup Leads**

Top Priority Monday Morning - 4 NIH Teams Provider Survey
- [ ] Survey no arm in randomization
- [ ] Lindsey will look in mtl.info to start crafting a message.

- [ ] Determining how to get Jeff up to speed on how we use Data UI
- [ ] Timelines for Data Collection (try to resolve asynchronously if we can)
- [ ] VA Red SAY guide - QA

**Comment by mnallajerla** [comment]
Monday 8 AM Work Group Leads 9/27/21

**Feature Release:** 

- New feature for saving simulation. 
- Also reinforces the idea that experiments need to be saved as they progress

**New Standing Meeting @ 8AM on Wednesday**

- Slating time for a standing meeting on Wednesdays @ 8 AM to brainstorm, in-depth, issues that core group needs to discuss. 
- This will protect time at cross-cutting meetings like HQ, 8 AM Work Group Leads etc 

**Authorship App**

- @dkngenda to scope out issue task card to track prior work + cost cleanly 
- @staceypark - Scope out issue card for instructions on how app currently works + complete task
- To be reviewed/discussed at Manuscript Monday: how to manage prior work and subcategories, prospective vs retrospective data issue
- Follow up meeting at 2 pst today to discuss remaining items related to app
- By TeamTime on 9/28 - Have concrete instructions for authors and steps to move forward.
- TeamTime right now intended for co-editors 

**Dynamics**

- Get everything remaining done in 1-2 sprints 
- Support from Melanie and team during sustainment phase 

_Priorities:_ 
- Surveys getting sent out - First priority that is most time sensitive
- Authorship App 
- Getting Jeff up to speed
- Timelines for Data Collection
- VA Red SAY guide - QA

**Discussion on Meeting Efficiency**

- What is good use of meeting time? How can we move issues forward? 
- Anyone on staff being able to drive meeting efficiently 
- Using new standing meeting versus cross-cutting meetings for in-depth discussion and overflow brainstorm
- Goal isn't efficiency, but that we are using our time well
- Meetings are to align on priorities 
- Everyone being able to be proactive about driving meetings and holding space

**Comment by lijenn** [comment]
## 8AM Workgroup Leads
- [ ] @lijenn to ping Facilitators to update Facilitator Availability Poll, review on Monday

## MM
- [ ] @dkngenda: Present result section writeup plan (tables and writeup) from IS and AJCP guidelines

## Facilitate WG
- [ ] Discuss Coplanning, Sim UI, D365 Task set up team and groups

## Coplanning 1B on Tuesday
- [ ] @jeffhoerle will: Go ahead and pursue the two fixes you outlined for aligning the ICD10 code & descriptions. Can you give us a time/scope estimate of points for each of these fixes?

## Overflow Meeting
- [ ] @dkngenda Cover R01 Aim 2 Provider Survey

## Quant Wednesday
- David: Think critically what should be in the paper to make the reader understand- they will have similar questions that we had

## Support WG
- Jeff's demo will not be on Wed, but Thurs. 10/7

## SIM UI 
- On the books and could cancel unless @jamesmrollins has something to discuss

Updates:
- We are starting MTL Hawaii :)
   - Internal meetings on Thurs. 10/7 & 10/21
