### ISSUE TITLE
Compliance Master Tracker 

### ISSUE THREAD

**Issue by mnallajerla** [lzim/teampsd#2394]
**B. Compliance skills working to address across the team:**
- [ ] Need to develop interdiscipilnary fluency.
- [ ] Need to be teaching each other how to double-check each other's work an learn new skills.
- [ ] We have a unique role studying a quality improvement initiative (so we have provided extensive coverage of our need to clarify what is Research and Operations).

**C. Tracking our Compliance Documents & Steps**
- [ ] Compliance related steps/documents - see it's state.
- [ ] Compendium or "Binder" of every relevant compliance step/documentation for each grant.
- [ ] Each team member should read and be familiar (sign off) on the IRBs/DART.
- [ ] Make amendment to remove former team members
- [ ] Add Meghana to VINCI project corr. site

**_Internal review and preparation for annual renewals._**

**D. Set up Dependency Chains:**

**IRB will need to be updated:**
R21
R01
IIR

**DART will need to be updated:**
R21
R01
IIR

**VINCI once we have IRB/DART:**
R21
R01
IIR

**Progress Reports (OASC, DSMB)**
IIR
R01
SAMSHA

**Federally registered trials**
R01
IIR

**Union notification, etc.**

FYI: @dkngenda

**Comment by lzim** [comment]
I believe this is covered by the README.md and can be closed.
