### ISSUE TITLE
jul_epic: Story C DEV QA -  Review UAT Guide and Crossref bug_tracker, Document Task Checklist Workflow, Set up existing Wave 2 groups and teams 

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2566]
Story C DEV QA -  
- [ ] Review UAT Guide and Crossref bug_tracker
- [x] ~Migrate D365 UAT Guide to MTL Manual~   (would recommend we stick with just having Facilitators use d365 for co-plan and live team workflow task checklists until we resolve bugs, task checklists is documented [mtl_how_3.0_facilitator_pre_session_post.md.pdf](https://github.com/lzim/mtl/blob/master/blue/session01/s01_facilitator/mtl_how_3.0_facilitator_pre_session_post.md.pdf).
- [x] Set up existing Wave 2 groups and teams

**Comment by lijenn** [comment]
#adjudication_memo: Hold on migrating to the manual, Jenn recommends and will review the UAT Manual first, identify workflows that are not working, and cross-ref issues back to the bug_tracker.

This will be our detailed list of what is working in D365 and what is not.
