### ISSUE TITLE
dec_epic story B: Merge updated DAX code and Data UI in GitHub and Team PSD Shared Folder

### ISSUE THREAD

**Issue by epearman** [lzim/teampsd#2774]
- [x] Changes made to Data UI DAX code for appointment supply calculations in the Team Agg Care Module across all encounter types except for Adjunct. #crossref #2743
- [x] Changes made to both Team Care Descriptions and Team Care Details for appointment supply. #crossref #2753 
- [x] Changes made to Team Care Descriptions and/or Team Care Details for missed appointment rate %. #crossref #2773

**Comment by epearman** [comment]
**Update Team PSD file records as a result of changes made to Data UI**
- [ ] Merge updated DAX code and Data UI in GitHub.
- [ ] Save all updated VISN reports and Master Data UI and DAX files in the Team PSD shared drive.

**Comment by epearman** [comment]
#crossref pull request #[464 ](https://github.com/lzim/research/pull/464) & #[465](https://github.com/lzim/research/pull/465)
