### ISSUE TITLE
Feature - Prototype for Recovery Flow Meters

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#2804]
**Discussed at sim_ui_workflow wk1 dec_epic**

@jamesmrollins 
@emilymetcalf114 
@epearman 

Please see this initial prototype for a visual interface that would provide real-time feedback on ranges in our primary _MTL_ units of pts/wk and appt/wk.

I will add additional details soon.

![image](https://user-images.githubusercontent.com/7454688/206310618-99a59c93-3f2e-41a0-a7a4-9f0a7a2b39e1.png)

**Comment by jamesmrollins** [comment]
@lzim @epearman @emilymetcalf114 

Pursuant to direction from @lzim to conduct an environmental scan for examples of system dynamics models being executed within Power BI, I found the following resources.

## Environmental Scan Results

1.  A YouTube video featuring Professor Jim Duggan regarding [System Dynamics Modeling with R.](https://youtu.be/pSbrsJ9EACU).
2. A GitHub repository [JimDuggan/SDMR](https://github.com/JimDuggan/SDMR) that features a program that will take a .mdl file and cover them to an executable R code.  However, the author did indicate that the results of the conversion will require some post-production review and fixing.
3. Dr. Duggan also penned a book [System Dynamics Modeling with R](https://www.amazon.co.uk/System-Dynamics-Modeling-Lecture-Networks/dp/3319340417/ref=sr_1_1?s=books&ie=UTF8&qid=1465684713&sr=1-1&keywords=system+dynamics+modeling+with+r), which I have purchased and will receive by 7 January.  The book and the repository go together.
4. I did not have an opportunity to investigate the production of custom dynamic graphics within Power BI.  However, I do believe that it will execute various types of scripts including Java and HTML.  However, these need to be verified. 
5. R code scripts can be run in Power BI.  YouTube offers many videos to explain how to do this.  [R Power BI Integration](https://youtu.be/ZHmmnNCd92w) was very informative with respect to using scripts to import and transform data.  There are also videos on using [R Visualizations](https://www.youtube.com/live/Klvybl642ug?feature=share).

## Next Steps

1.  Make a very simple model, run the model conversion to R and execute the script inside of Power BI.
2. Continue investigation regarding the development of custom dynamic visualizations (such as the one above).
3. Define feature benefit hypothesis and acceptance criteria for above traffic light visualizations.
4. Develop a Power BI data visualization prototype.

**Comment by jamesmrollins** [comment]
## Work Breakdown discussion - Traffic Light
		
- [ ] Assumption 1:  The traffic light will reflect current state results and future state results (may need to add a timeline)
  - Nope!
  - The traffic light will only reflect the **recommendation.**
  - First step is to provide a UI, where the facilitator, via dialectic with decision-makers, would hand enter the values into a graphic generator. 
  - The traffic light would be the cover page of the tt report.
- [ ] Assumption 2: Based on the TD profile, the machine will recommend settings.
  - Not now.
- [ ] Assumption 3: Based on recommendations, users can adjust settings or run recommendation verbatim.
  - Not now.  This would be a long term objective based on model functions like "balanced mode" and "learning mode" where the model makes adjustments to maintain most positive results.
- [ ] Mine data in case histories and analyze for patterns based on similar Team Data (TD) baselines (and hypothesis?).
  - Not now. 
- [ ] Determine the rubric for each traffic light color.  
  - Not right away.
- [ ] Determine the algorithm for evaluating current TD baseline of a given team, then recommending rubric informed settings and then doing the run.
  - Would be good to run all models at once to identify where to start for deeper exploration.
  - Setting recommendations could be generated by the model, see above. 

## Case history repository formation. 	**NOT DISCUSSED**
		
- [ ] What artifacts compromise the repo? Past sim ui experiments, TD profile and results in research aims?
- [ ] How do we identify trends and patterns? Do we have a gut-sense of this already, or do we want to employ some form of statistical inference or AI?

**Comment by jamesmrollins** [comment]
@lzim @epearman @emilymetcalf114 
[care decision meters and tt reports generator copy.pdf](https://github.com/lzim/teampsd/files/10449219/care.decision.meters.and.tt.reports.generator.copy.pdf)

FYI: @hirenp-waferwire 

## Wireframe for traffic lights (combined with tt Reports)

![Artboard 1](https://user-images.githubusercontent.com/30132017/213258805-0d4bacbb-3ffa-44df-a068-1dc18cd76cdc.png)

[care decision meters and tt reports generator copy.pdf](https://github.com/lzim/teampsd/files/10449283/care.decision.meters.and.tt.reports.generator.copy.pdf)

**Comment by lzim** [comment]
Discussed at 
**wk3 jan_epic support_workflow**
@jamesmrollins 
@emilymetcalf114 
@epearman 
@lzim 

"**Prototypes**" - **ADD Infographics**
**Decision meter reflects the recommendations based on the alternative scenarios/experiments run by the learner.** 
**Some of the requested infographics will reflect model initialization at time zero**. 

**Front-end user requirement:** 
_Why:_ Repackage and simplify the _MTL_ Menu process (MTL Blue PARTNER phase).
_How:_ Quick Infographic based way to identify the highest **leverage** priorities.

- [ ] **Backend requirements: Need to save the main model diagram initialization values.**
**_Current State:_** Right now all saving is based on a run, including the Base Case.

**Comment by jamesmrollins** [comment]
@hirenp-waferwire 

- [ ] Please refer to the attached wireframe for instructions regarding the development of this MVP.
- [ ] Develop the proposed wireframe in Test Slow.

**Comment by jamesmrollins** [comment]
2/13 8AM_workflow

DECISION:  
- [ ] Put the Recovery Flow Meter icon for popup on the Homepage, decision dashboard.
- [ ] The Recovery Flow Meter will save as an initial experiment value that can be picked up by a subordinate team within the Sim.

**Comment by epearman** [comment]
Discussed during **wk3 march_epic system_sme_support_worfklow** with @emilymetcalf114 , @dlounsbu, @hthrmarshand @epearman 

- [ ] **Feedback from David L:** is there a way to quickly clear all saved experiments and settings and start over. This would help facilitate the process of testing several different experiments before choosing the final experiments you want to show to the team. 

FYI: @jamesmrollins , @lzim

**Comment by jamesmrollins** [comment]
FOR:  @dlounsbu 
FYI: @epearman 

## How to clear select or all experiments from Home Page.

1. To clear all experiments, check the box shown in yellow below and then click "Delete."
2. To clear a specific experiment, click one or more boxes next to the desired experiment you wish to delete, then click "Delete."
![image](https://user-images.githubusercontent.com/30132017/226991148-bda8d9e3-fbf2-4fa3-a246-c9441ad17e24.png)


## Is there another place in the interface that you would like to be able to manage experiments?

**Comment by epearman** [comment]
#ajudicated_memo
-tracked **2023_jan_epic** efforts in #2949
-tracked **2023_feb_epic** efforts in #2950
-tracked **2023_mar_epic** efforts in #2950
