### ISSUE TITLE
2024_06 - Determine status and scope remaining in June Roadmap - Create a reports generator to support site reports

### ISSUE THREAD

**Issue by emilymetcalf114** [lzim/teampsd#2835]
Discussed wk2 jan_epic during _MTL blue_ session 12 prep with QIICs. Feature requests include:

- [ ] Default 6 result dashboard views up in each module are the default in the tt_report Select Reports menu. 
- [ ] Another useful feature would be to have the user selected views in the Results Dashboard be the defaults tt_reports.
- [ ] Select pages in the tt_report "Build the report you want."
- [ ] Select the text boxes across other worlds if when needed (shared world; team world) for the Alternative Experiments that have been run in multiple world

**Comment by jamesmrollins** [comment]
Go to [Traffic Light Prototype](https://github.com/lzim/teampsd/issues/2804#issuecomment-1387487488) for wireframes.

**Comment by jamesmrollins** [comment]
## Benefits Hypothesis

Often, the end user does not need all the details contained within the legacy tt1, tt2 or tt3 report. The current reports generator supports customization by allowing the user to select experiments and charts for the given report, but also includes QHFD, Team Data Tables and Definitions of Terms that may not be required for the user's needs.  Furthermore, the current reports do not include a way to include the Traffic Light infographic.

## Requirements

- [ ] Create a means for the end user to select each element of the tt reports (i.e., team data table, definitions of terms and others).
- [ ] Create a means for the end user to select the order in which the reports items are presented.
- [ ] Support a PDF download or print.
- [ ] Maintain the ability to export charts only.

## Wireframe

![image](https://user-images.githubusercontent.com/30132017/217960050-41f8bdae-c8ff-45a9-b528-49d5048a1133.png)

[tt Reports WIreframe.pdf](https://github.com/lzim/teampsd/files/10702316/tt.Reports.WIreframe.pdf)

**Comment by lzim** [comment]
@jamesmrollins 

@epearman
@jamesmrollins 
_Is there a status update from_ **support_workflow** _on this one?_ 

_Recommended Next Steps_: 
- [ ] @emilymetcalf114 - Produce for review the final tt3 report to teams that just wrapped up _MTL_ with @lzim & @jamesmrollins 
- [ ] @jamesmrollins & @lzim use review to refine the tt_reports wireframe MVP>
- [ ] @emilymetcalf114 & @epearman (see **wk2 feb_epic 8AM_workflow** agenda) - Evaluate data on tt reports, co-planning documents and surveys are being sent now using **Dynamics.**

**Comment by lzim** [comment]
### wk3 mar_epic

#### [Responses on sim_ui_workflow ](https://teams.microsoft.com/l/message/19:cd8c8a819f6041219bdf78ad0dd9b93b@thread.skype/1679350296840?tenantId=e95f1b23-abaf-45ee-821d-b7ab251ab3bf&groupId=1db500d5-0d01-4254-af42-ad3f78bafacd&parentMessageId=1679001363255&teamName=teampsd_vha&channelName=sim_ui_workflow&createdTime=1679350296840&allowXTenantAccess=false)

E**xcellent @jamesmrollins 🚀** 
Thank you so much! 
 
**Apologies we were short on time at 8am_workflow today to cover these.**
We are working on improving that as fast as we can!
 
**Re: #2835 - We'll review the tt_report wireframe w/#systems_smes tomorrow.** 
- [ ] I'll check to see if I have any questions to finalize call about review with #qiics too or not. 
	
**I would also like to review w/#systems_smes the TEST decision meter prototype at https://mtl.how/test** 
- [ ] @emilymetcalf114 and @lzim @dlkibbe @dlounsbu We'll record so you have #user_acceptance_testing

@jamesmrollins asked and 
@lzim  answered	 
	
> What is the desired point-of-entry for the tt report (i.e., the Dynamic Decision Dashboard, Facilitator Panel, both)?

@lzim Answer: First Screen for all users no matter login type.
Yes, Facilitator Panel.
Yes, Dynamic Decision Dashboard.
	
Return Question from @lzim 
_I think we may need to add/replace another icon on the main navigation to get to it from anywhere in the Sim UI. Recommendations?_
	 
>Will the consultative approach use the QHFD structure for comments, or do we need to add a more general "comments" or "observations" field?

- **tt_report needs to be 1-2 pages** without the PARTNER or BUILD phases that the Q/H/F/D support, which will be in our MTL external implementation facilitation approach.
	
#### For "modeling consultation services:" we need to be able to create "decision support" "recommendations" in the tt_report
- [ ] **open-ended list** of recommendations
- [ ] **open text** recommendations
	
#### Feature Request: the tt_report includes static images for key insights drawn from the
- [ ] "**dynamic decision dashboard**" - Key high volume states, and inflow <> outflow imbalances. 
- [ ] "**decision meters**" - Key recommended decision heuristics in pts/wk or appts wk for the site.
	
Feature Request: The "dynamic decision dashboard" creates a zoom in/out interactivity to track the scaling from
#### _Zoom in_
- **Common team care problems:** CC, MM, PSY, Team (AGG) Care (pts/wk or appts/wk)
	
#### _Zoom out_
- **Team (SP) Flow** - episodes of care (pts/wk)
- _Desired state_ **Team (SP) Flow** - facility/mo or visn/quarter aligned with MHOC
- _Desired state_ **Health Equity Sankey in Power BI** (facility/mo or visn/quarter) 
	
**DECISION:**
Remove "AGG" and "SP" in our 2024 MTL 4.0 release that includes all these modeling consultation and decision support features and health equity. 
	 
> We haven't determined how experimentation will work from the Dynamic Decision Dashboard, thus we don't have an algorithm for how we save experiments for all models, how the experiments are conducted once we drill down to a particular module, or how these might be assigned to a working group. So we could use ideas on how the interaction would look with a facility or VISN decision-maker and how their decisions would affect or relate to follow on work. 
	
#### REMINDER: Team PSD determine with #systems_smes because no other user group is modeling any more. No capacity building (BUILD) phase, just consultation.

### Next Steps - Finalize for Slide Deck/Guides

- **_Site leadership in the consultation model will ONLY see the items below_**
1. **Sharepoint & "Site Studies" (Story J)**
2. **Slide Decks of "Use Cases"**
3. **Decision Meter**s of new local decision heuristics
4. **Dynamic Decision Dashboard** - Review volume of pts and appts & inflow/outflow imbalances
5. **tt_report** - see above
6. In **power_bi - sankey** with facility/mo and visn/quarter
	
**So, these are all #systems_sme and #support_workflow answers we will review wk3 mar_epic (tomorrow)**
- [ ] #systems_sme - How we experiment
- [ ] #systems_sme - How we save experiments
- [ ] #support_workflow @emilymetcalf114  @epearman - How to assign users to groups in Forio Epicenter Sim UI

**Comment by lzim** [comment]
**Discussed at wk3 mar_epic sim_ui_workflow**

Based on conversation at **consult_facilitate_workflow** with **#qiic**
- [x] Determined 2 types of site visit reports are required.

_Next Steps:_
- [ ] @emilymetcalf114 Brief "heads up" report - get template from QIICs
- [ ] @lzim Email Cliff & Claire about the still to be finalized overall template.

**Comment by epearman** [comment]
closing this issue for the apr_epic, may_epic efforts will be tracked on #2937

**Comment by lzim** [comment]
wk1 2024_06 - _Not 100% what this card is tracking compared to other MTL 3.7 cards_

_Can you advise for our June Roadmap Event @ljmoody by chance?_

**Comment by ljmoody** [comment]
Hi @lzim,
Some of the tasks on this card are already in place or in the works. Others seem outdated (and predate my time on the team). _MTL_ reports generator is being tracked in the following open cards (and multiple closed ones, too). It's likely we may revisit the functionality and design aspects of the reports generator via these cards. As such, I'm closing this one. 
FYI: @jamesmrollins, @lijenn - _any issue with this action?_
- #3028, test
- #3033, train
- #2987, doc

**Comment by hnorthcraft** [comment]
#adjudicate_memo per comments above work tracked on other cards. marking as dup with 0SP
