### ISSUE TITLE
Master card: system_sme_prep slide decks and MTL packaging materials post-pivot

### ISSUE THREAD

**Issue by emilymetcalf114** [lzim/teampsd#2940]
Slide Decks @emilymetcalf114 #people_ops_workflow
@dlounsbu 
@dlkibbe 
@lzim 
#systems_sme_workflow

### 2023_apr_epic
- [ ] @emilymetcalf114 How to use the calendar #system_sme (3 pts) #cross-ref #2909
  - [ ] mtl.help@va.gov
  - [ ] QIIC consortia maps w/hyperlink to their sharepoint.
  - [ ] #cross-ref #2918
- [ ] @lzim & @emilymetcalf114 How to elicit the priority & clinic selection (3 pts) #cross-ref #2925
  - [ ] QA #cross-ref #2930

#### GAO or TJC Report from the QIIC Site Visit
- [ ] 2 paragraphs: Boiler plate of how to access MTL Red & MTL Blue follow-up - Sharepoint
  - [ ] 
- [ ] 2 paragraphs: Recommendations
- Standard very brief report ready made for inclusion with other communications e.g., report.
- 2 standard MTL paragraphs 
1. Brief boilerplate of how to access and use resources as well integrate them across OMHSP
e.g., MTL Red/Blue - Data UI - Resolve discrepancies between OPES and MHOC data with MTL Clinic Review.
2. A very brief summary of Data UI (red) or Sim UI (blue) recommendations for a site.

### 2023_may_epic
- [ ] How to prep participatory system dynamics insights consistent with OMHSP priorities, clinical expertise
  - [ ] Slides need links to the resources on every slide.
  - [ ] 
  - [ ] _MTL_ Red - #cross-ref #2926
    - [ ] QA  - #cross-ref #2929
  - [ ] _MTL_ Blue - #cross-ref #2927
    - [ ] QA  - #cross-ref #2928
- [ ] How to package those insights - Template from Cliff & Claire
  - [ ] footer note - link to definitions in the slide deck
  - [ ] _MTL_ Red  - #cross-ref #2931
    - [ ] QA - #cross-ref #2933
  - [ ] _MTL_ Blue  - #cross-ref #2932 
    - [ ] QA - #cross-ref #2934
- [ ] slide decks for QIICs to present to sites during site visits 
  - [ ] _MTL_ Red - QA #cross-ref #2939
  - [ ] _MTL_ Blue 

Align with the OMHSP #qiics and the field:

- mtl.help@va.gov - our primary way of communicating.
- < 1 mo lead time 
- < 1 mo of engagement
- NO PREP time for the #qiics - briefings and alignment 1 hr #consult_workflow at 12noon Eastern. 
- [ ] Use case slide deck #cross-ref #2907

#qiics are providing this to site visit
1. Brief summary of the visit and what to expect.
2. Formal report reviewed up the chain of command.

#systems_sme_workflow - modeling recommendation prep for the consults - Top 3 priorities
1. Use of staff time - productivity, clinic review, labor mapping (integrate w/LEAF), bookability, access
2. EBPs
3. MH Continuum of Care - Team Flow - episode of care, stepped care, measurement based care.

**Comment by lzim** [comment]
**#adjudicate_memo
#story_b**
- [ ] @emilymetcalf114  Let's discuss [#2940](https://github.com/lzim/teampsd/issues/2940) I see how you've broken up the Master Card into smaller cards and separated them into monthly epics consistent with the roadmap of user_story_maps for review by #mgmt_trio. 

**The proposed sequence may not get this done quickly enough for up to 8 sites (17% of our sites) reached out to between now and Memorial Day.** 
- [ ] The roles, requirement, milestones and deliverables at each step require specification to create an async/pull based workflow that maximizes flow.
- [ ] _Have you implemented [Weighted Shorted Job First (WSJF)](https://scaledagileframework.com/wsjf/) for your prioritization consistent with your SAFe training?_

FYI: 
@hthrmarsh 
@epearman

**Comment by epearman** [comment]
### Addendum to functional Requirements
Discussed **wk4 2023_apr_epic system_sme_workflow**

- [ ] @epearman add link to mtl.how/team and link to OMHSP QIIC SharePoint on the data UI landing page. 
- [ ] Links to resources used should be made available on each slide

**Comment by lzim** [comment]
this was was not the approach taken in the end. Closing with 0 story points
