### ISSUE TITLE
2023_wk4_oct_#story_b: QA Test : Conduct User Testing of Facility Sim UI Self Registration

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#2965]
## Conditions

- Given updated user interface available in Test-Slow and,
- A user with Facilitator priviledges and,
- A set of users provided by the CRM or by individual inputs, and
- Updated user documentation, and
- Updated Tutor Prompt.

## Tasks

- [ ] User can find and reference documentation
- [ ] Upon initial login, the Tutor Prompt points out the new feature.  
- [ ] By clicking links available on the Tutor Prompt, user is referred to reference documentation.
- [ ] User can successfully navigate to appropriate screen from the Facilitator dashboard.
- [ ] User can successfully choose the desired consult function and assign team members to the team.
- [ ] Upon navigation from the Facilitator Dashboard the Dynamic Decision Dashboard presents with correct group information.

**Comment by ljmoody** [comment]
Closing; tracking progress in #3026.
