### ISSUE TITLE
wk?_2024_apr_epic #story_t: As a Team PSD member, I need better meta data so I can find things on the platforms

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#2995]
## Definition of Done

- [ ] Gain consensus on metadata tags and use
- [ ] Develop a policy that governs how metadata is provided for artifacts stored on platforms.  The policy should:
   - Ensure that metadata is created in a consistent and accurate manner.
   - Manage metadata throughout its lifecycle.
   - Ensure that metadata is accessible to authorized users.
   - Ensure all Team PSD members use metadata in a responsible manner.
   - Provide a remedy for any metadata errors or inconsistencies.
   - Identify a data steward.
- [ ] Update the Team PSD glossary of terms.
- [ ] Recommend a cadence and workflow where metadata issues are discussed and resolved.

**Comment by ljmoody** [comment]
Adjusted this card point value to 0, closing this card as not planned.
