### ISSUE TITLE
2024_06 #story_l: Create a Test Checklist and Code Migration Procedure from 3.0 to 3.7

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#2997]
@lzim Please validate the below

- [ ] I don't think we need a full Test Version Release (the creates copies of mtl 3.0 Blue sessions, model files and such).  
- [ ] Recommend we handle it as a feature branch.
- [ ] Reserve version test release for full number release of 4.0, as it will likely involve more documentation and user testing.

## Condition

- [ ] 3.5 Main branch and gh-pages is complete

## Definition of Done

- [ ] Test release action updated for appropriate link replacements and find a replace terms.
- [ ] Reverse action to production updated for appropriate link replacements.

**Comment by jamesmrollins** [comment]
FYI: @lzim 
@lijenn @ljmoody We need to discuss this and determine if and when we will do this.  Test version release will do a link find-and-replace crawl through the entire repo through documentation we will likely not use in the new paradigm.

**Comment by lijenn** [comment]
@jamesmrollins This is a blocker for #3013, if we still need tutor prompts for the Dynamic Dashboard.
FYI @ljmoody

**Comment by jamesmrollins** [comment]
# Context and Benefit Hypothesis

There are changes to the model directory structure in Epicenter that is supporting features in MTL 3.7 that are not in 3.0.  3.7 parses group team data into folders named after the group in the Model directory. This allows the Sim UI to limit the view of participants to only their group information.  Furthermore, to maintain schedule, the PI is going to continue to build teams in 3.0. With these new and legacy teams, group team data files in 3.0 that will need to be migrated to the new structure. This mitigation strategy describes how the Sim UI Team will migrate from 3.0 to 3.7 while maintaining backwards compatibility. 

## Important Dates

- [ ] 5th week of April for final consult prep in 3.0.  NOTE: if migration can occur earlier, _the final teams could be prepped in 3.7_
- [ ] **GO Live** scheduled for 1st week of May.

## Checklist:

- [ ] **@tejaspesquare will update Break-fix to be an EXACT copy of PROD**.  This will provide us with a means of both arranging data into appropriate named folders and give us a venue to test whether the retrievals are working properly. 
- [ ] **@jamesmrollins will create legacy team folders in Breakfix.** We need to investigate as to whether GitHub may be the place to accomplish this transformation, because Epicenter does not have file management capabilities.
- [ ] @ljmoody and @lijenn will create a checklist of teams that require conversion.
- [ ] @ljmoody and @lijenn will create a function check checklist to test the implementation of new folders.
- [ ] @tejaspesquare will migrate the completed repository to PROD by the 3.7 implementation date.

**Comment by jamesmrollins** [comment]
3/25 Stand Up

- @tejaspesquare will check out how we can create folders by group ID. 
- Then Team Praxis can sort the legacy files into those folders.

**Comment by ljmoody** [comment]
Relevant question from @tejaspesquare to consider, decide, and respond to - see quoted comment below. 

- [ ] If we want to delete a team data file, should it be deleted for everyone in all teams/worlds, or just a specific world? 

> In V3.0 we don't have sub-folder concept & in 3.7 it has.
> We have to think of business rule to perform Delete action as because in current scenario file will be associated with individual group & possibly 2 or more groups will upload same name file but will have different locations. So, on delete which file supposed to be removed will cause for others. Could you please suggest.
> 
> ![image](https://github.com/lzim/teampsd/assets/124643236/dae64110-8db6-4ce2-a255-999785c91090)
> 
> Note: On this section we bring up (as per our conversation) all listed files from Epicenter. Also, we have filtered duplicate file if any.

**Comment by ljmoody** [comment]
Discussed at sim_ui_workflow 3/13/2024:

![image](https://github.com/lzim/teampsd/assets/124643236/2e96a28d-bc7a-4b94-8ac7-4060e99d14eb)

**Comment by ljmoody** [comment]
@lzim, please consider and provide guidance on:
- [ ] Should deleting a Team Data file in a shared or team world also delete for all users in all shared/team worlds -  or - just a specific world?
- [ ] Should uploading a Team Data file in a shared or a team world also auto-upload the file in team/shared world, too?

**Comment by lzim** [comment]
@ljmoody _Just checking: Are your questions on the right card re: MTL 3.0 to 3.7 migration?_

>  Should deleting a Team Data file in a shared or team world also delete for all users in all shared/team worlds - or - just a specific world?
>  Should uploading a Team Data file in a shared or a team world also auto-upload the file in team/shared world, too?

Unless there's something I'm missing...Yes and Yes for team and shared worlds. Individual worlds should operate on it's own. But do see my comment about uploading Team Data.
- [ ] If someone deletes a Team Data File in the shared or team world they are deleting it from shared and team worlds for all users of the shared and team worlds. This should not impact what is in individual worlds. 
- [ ] If someone uploads a Team Data File into a shared or team world, it should be available in team and shared worlds for all users of the shared and team worlds. This could be available in individual worlds too to save folks time. But, when someone uploads a Team Data file to an individual world, it should only be available to themselves _and all MTL administrators _ who may need to provide support.

Let me know if this answers the relevant scenarios. Thanks!

**Comment by lzim** [comment]
@lijenn - _Are we able to migrate the MTL 3.0 External Implementation Facilitation Manual to the new repo yet?_

@lzim created these short URLs going to these link locations:
- [ ] https://mtl.how/facilitation_manual -> https://lzim.github.io/mtl_3.0_facilitation/
- [ ] https://https://mtl.how/facilitation -> https://github.com/lzim/mtl_3.0_facilitation

**Comment by ljmoody** [comment]
@lzim, Thanks for your input above re: Team Data uploads to team, shared, and individual worlds. I do believe this addresses what we needed to know. 
Yes, I meant for that question to be on this card, as it has to do with Epicenter file structures and, thus, the migration from 3.0 > 3.7. Definitely a consideration for Dev to know and keep in mind as we make this transition.

fyi: @lijenn, @jamesmrollins, @tejaspesquare

**Comment by lijenn** [comment]
> @lijenn - _Are we able to migrate the MTL 3.0 External Implementation Facilitation Manual to the new repo yet?_
> 
> @lzim created these short URLs going to these link locations:
> 
> * [ ]  https://mtl.how/facilitation_manual -> https://lzim.github.io/mtl_3.0_facilitation/
> * [ ]  https://https://mtl.how/facilitation -> https://github.com/lzim/mtl_3.0_facilitation

I'm having trouble copying over the GitHub Action workflows, I'll try it a different way. May be a token issue.

**Comment by lijenn** [comment]
Discussed at Sim UI Stand Up on 4/3/2024:
- @tejaspesquare confirmed understand the following 2 decisions:

> @ljmoody _Just checking: Are your questions on the right card re: MTL 3.0 to 3.7 migration?_
> 
> > Should deleting a Team Data file in a shared or team world also delete for all users in all shared/team worlds - or - just a specific world?
> > Should uploading a Team Data file in a shared or a team world also auto-upload the file in team/shared world, too?
> 
> Unless there's something I'm missing...Yes and Yes for team and shared worlds. Individual worlds should operate separately. But do see my comment about uploading Team Data and admin access to that data file.
> 
> * [ ]  If someone deletes a Team Data File in the shared or team world they are deleting it from shared and team worlds for all users of the shared and team worlds. This should not impact what is in individual worlds.
> * [ ]  If someone uploads a Team Data File into a shared or team world, it should be available in team and shared worlds for all users of the shared and team worlds. This could be available in individual worlds too to save folks time. But, when someone uploads a Team Data file to an individual world, it should only be available to themselves _and all MTL administrators_ who may need to provide support.
> 
> Let me know if this answers the relevant scenarios. Thanks!

- Team Data files listed in Team Set Up in Admin Dashboard encounter problems with deletion, if the file name is the name, regardless of what World the team data file is in. Deleting the team data file will delete the file in _shared, _team, and _ind.
- @tejaspesquare suggests adding an extra column in in the Data column to reflect what world (shared, team, or ind) the data is in:
<img width="1115" alt="image" src="https://github.com/lzim/teampsd/assets/59668647/ea51d876-2d5d-4f01-bfb6-185bdd8d6bd5">

**Comment by lijenn** [comment]
Discussed Sim UI Stand Up 04/03/2024:

@tejaspesquare will be able to make the bugs in Break Fix (e.g., #3131) once the migration from Prod to Break Fix is completed. Will reach out to us next week for migration updates.

**Comment by lijenn** [comment]
Discussed 4/7 Sim UI Stand Up:
- @tejaspesquare mentioned the migration is expected to be completed this week and working on migrating TEST-SLOW to BREAK-FIX.

**Comment by tejaspesquare** [comment]
@lzim , @ljmoody , @lijenn: Upload & Delete Team Data file (Settings -> Data) is developed & code is moved to Test Slow.

Below is my Testing results on Test-Slow. Group Name - test14march 

Selecting _team file & Upload
![image](https://github.com/lzim/teampsd/assets/144898781/a1ac4d7f-69d1-4e78-9a24-140be88b1779)

File got uploaded into world/team ( i.e. _ind, _shared & _Team)  (Note: Checked file represents _team & _shared teams)
![image](https://github.com/lzim/teampsd/assets/144898781/cdeaf01d-c25c-47ba-88db-612dc6062ecf)

Uploaded file is also accessible to a Team Member
![image](https://github.com/lzim/teampsd/assets/144898781/291821f9-1e48-4712-9fcc-2e2b6d92a34e)
![image](https://github.com/lzim/teampsd/assets/144898781/1a053f42-390a-4fe8-b671-8fa575ac39ab)
![image](https://github.com/lzim/teampsd/assets/144898781/7bc8548c-d746-4b68-a5ca-e78d018bcd83)

Delete file belong to _team & _shared
Before Delete
![image](https://github.com/lzim/teampsd/assets/144898781/edcc04f1-b0b6-43e9-9f04-b8826ec3c77a)
 
After Delete, only _ind file is present 
![image](https://github.com/lzim/teampsd/assets/144898781/937cee40-51f7-4ddf-9d80-341a14c2edf3)

File is not available to a team member which was earlier accessible 
![image](https://github.com/lzim/teampsd/assets/144898781/b36fc024-33d7-49d7-b10e-9fff175059f3)
![image](https://github.com/lzim/teampsd/assets/144898781/eda659eb-c068-4d64-a42c-cbab0c65eea6)

**Comment by lijenn** [comment]
Discussed 4/10 Sim UI stand up:
- @lijenn is continuing to test the add/delete data file method as listed above in Test-Slow. Will also check Epicenter for data file upload and file structure for Test-Slow.

**Comment by jamesmrollins** [comment]
## 3/14 Stand Up

- Discussed experiment migration from 3.0 to 3.7. Data inputs and retrievals from database should be unchanged. However, all 3.0 related data will be sub-divided on the Experiment Maintenance Panel and associated dropdowns throughout the Sim UI.
- We will test this in Test Slow prior to deployment of 3.7 and not migrate via Test Breakfix.
- Decided that version 3.0 experimental data will be named "_MTL_ 3.0"

**Comment by jamesmrollins** [comment]
## 5/5 Stand Up

- [ ] @tejaspesquare will migrate from test slow to prod, once James validates the x-Waiver removal.
- [ ] Hide the Flow selection on dropdown.
- [ ] Hide, but continue development of Directives.
- [ ] James will update "i" information in MM Model and push to lzim/mtl/DEV.

**Comment by lzim** [comment]
#sim_ui_workflow
@jamesmrollins 
@lijenn 
@ljmoody 

_Is this card done?_ thanks!
