### ISSUE TITLE
#story_t_2023_wk2_nov_: As a Team PSD member, I need an up-to-date manual for reference

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#2999]
## Definition of Done
[**Reference Lucid #2999_team_psd_safe_workflows link**](https://lucid.app/lucidchart/0cd93668-a02d-4176-b97d-4f342985a57f/edit?invitationId=inv_3462b1a9-3207-4813-87e1-993924811a3f&page=0_0#)

- [x] Compare training_workflow channel documentation and videos to #2999_team_psd_3.0_workflows Lucidchart; update as necessary
- [ ] Ask SMEs about unknown/unclear posts from training_workflow channel.
  - [ ] [2/26/23 2023 Agilest SAFe 5.1 for Government Teams](https://teams.microsoft.com/l/message/19:d15133fbfb4d4c3a8c81701292b1890d@thread.skype/1676555978961?tenantId=e95f1b23-abaf-45ee-821d-b7ab251ab3bf&groupId=1db500d5-0d01-4254-af42-ad3f78bafacd&parentMessageId=1676555978961&teamName=teampsd_vha&channelName=training_workflow&createdTime=1676555978961&allowXTenantAccess=false) - Jenn to ask Lzim
  - [ ] [2/13/23 F2F Roadmap feb_epic](https://teams.microsoft.com/l/message/19:d15133fbfb4d4c3a8c81701292b1890d@thread.skype/1676336760477?tenantId=e95f1b23-abaf-45ee-821d-b7ab251ab3bf&groupId=1db500d5-0d01-4254-af42-ad3f78bafacd&parentMessageId=1676336760477&teamName=teampsd_vha&channelName=training_workflow&createdTime=1676336760477&allowXTenantAccess=false) 
  - [ ] [2/20/23 User-Centered Team PSD Workflows - User Personas](https://teams.microsoft.com/l/message/19:d15133fbfb4d4c3a8c81701292b1890d@thread.skype/1676923209290?tenantId=e95f1b23-abaf-45ee-821d-b7ab251ab3bf&groupId=1db500d5-0d01-4254-af42-ad3f78bafacd&parentMessageId=1676923209290&teamName=teampsd_vha&channelName=training_workflow&createdTime=1676923209290&allowXTenantAccess=false)
  - [ ] [3/13/23 Team PSD SAFe and #health_equity Minimum Viable Product](https://teams.microsoft.com/l/message/19:d15133fbfb4d4c3a8c81701292b1890d@thread.skype/1678747922278?tenantId=e95f1b23-abaf-45ee-821d-b7ab251ab3bf&groupId=1db500d5-0d01-4254-af42-ad3f78bafacd&parentMessageId=1678747922278&teamName=teampsd_vha&channelName=training_workflow&createdTime=1678747922278&allowXTenantAccess=false)
- [x] Review [recordings ](https://teams.microsoft.com/_#/FileBrowserTabApp/training_workflow?threadId=19:d15133fbfb4d4c3a8c81701292b1890d@thread.skype&ctx=channel) and map to chapters (may need help/checking)
  - **all meeting recordings in training_workflow listed by year on pink stickies (left-hand side of Lucidchart)**
  - **need approval for suggested videos in several sections**
- [ ] ?Rename generic-named recordings once they are mapped to correct chapter/sections, using file naming conventions.
- [x] Indicate chapters/sections yet to be written/completed
  - **stickies with black outline = content needed**
- [x] Compare #2999_team_psd_3.0_workflows Lucidchart to existing Team PSD Manual and update card colors in Lucidchart to indicate whether content is/is not in manual
- [ ] Incorporate #2995 - functional requirements re: metadata
- [ ] Incorporate NIH/VHA AI guidance/policy into manual, stemming from [this 6/26/23 meeting](https://teams.microsoft.com/l/message/19:09778e4391404920a8a20c7ef4ec3de3@thread.skype/1687793446171?tenantId=e95f1b23-abaf-45ee-821d-b7ab251ab3bf&groupId=1db500d5-0d01-4254-af42-ad3f78bafacd&parentMessageId=1670344725699&teamName=teampsd_vha&channelName=all_teampsd&createdTime=1687793446171&allowXTenantAccess=false)
- [ ] Confirm order of chapters & sections for v3.5
- [x] Create feature-gh-pages branch and update manual content (narrative & links from Lucidchart)
- [ ] Address, update, and fix existing broken links
- [x] Incorporate offboarding a team member checklist, provided by H Marsh [#709, 2023_aug_epic #portfolio: Update Team PSD Manual to include offboarding/close out](https://github.com/lzim/research/issues/709)
- [ ] Include standard **story point definitions** for each value stream in the manual
- [ ] Include the standard **story point scale** for each value stream in the Team PSD manual.

**Comment by ljmoody** [comment]
@jamesmrollins & @lijenn - I have questions related to PSD Manual videos mentioned in the [2999 Lucidchart](https://lucid.app/lucidchart/0cd93668-a02d-4176-b97d-4f342985a57f/edit?invitationId=inv_3462b1a9-3207-4813-87e1-993924811a3f&page=0_0#) that I hope you can help with. The first broad question is, **does the decision re: _not_ walking through technologies on videos, but pointing to evergreen locations, impact how I should proceed with incorporating these videos into the PSD Manual update?**

#### I am unable to access these:
- [ ] [4.6, Example 2](https://dvagov.sharepoint.com/sites/teampsd_vha/Shared%20Documents/all_teampsd/Recordings/TeamPSD%20Team%20Time-20230214_131344-Meeting%20Recording.mp4?web=1&OR=Teams-HL&CT=1687365226850), error message says “This site can’t be reached”
- [ ] [ 7.9 video](https://dvagov-my.sharepoint.com/personal/swapandeep_mushiana_va_gov/_layouts/15/AccessDenied.aspx?Source=https%3A%2F%2Fdvagov%2Dmy%2Esharepoint%2Ecom%2Fpersonal%2Fswapandeep%5Fmushiana%5Fva%5Fgov%2F%5Flayouts%2F15%2Fstream%2Easpx%3Fsw%3Dbypass%26id%3D%2Fpersonal%2Fswapandeep%5Fmushiana%5Fva%5Fgov%2FDocuments%2FRecordings%2FAccessing%2Bprovider%2Bsurvey%2Bdata%2Bwith%2BR%2Bnotebook%2D20210929%5F124540%2DMeeting%2BRecording%2Emp4%26ClientRender%3D1&correlation=5db8c0a0%2D3031%2De000%2D0349%2D8875d111ad54&Type=item&name=5f1a1ac0%2De986%2D4f4f%2D9463%2De77104f73c91&listItemId=51&listItemUniqueId=3a25111b%2D24cc%2D46a2%2D97d4%2D7ffb55e0cf31), error message says “You don’t have access.”; I’ve requested access, but haven't been granted that yet.
- [ ] [8.5.3 video](https://dvagov.sharepoint.com/sites/teampsd_vha/Shared%20Documents/facilitate_workgroup/Recordings/mtl_coplan_team_redcap_setup-20220502_170317-Meeting%20Recording.mp4?web=1), error message says “This site can’t be reached”

#### Where can I find info/videos associated with the following:
- [ ] Box to left of 4.2 sticky “mtl_facilitate team general MTL 2.4 New Chapter”: treatment is like a video including PI; but no video linked. Refers to MTL Chapter 2.4. What is supposed to be done with this? 
- [ ] 4.3 light gray box: is"wk5 may_epic support_workflow” referring to a video? If so, where can I find it? If not, what is expected to happen with this note? Please explain.  
What is "*Add 5.3 & 9.0” referring to—PSD manual (new or old order of chapters?) or MTL manual? And what is the expected treatment of this cross-referenced material? 
- [ ] 4.5 light gray box: is "wk4 may_epic training_workflow” referring to a video relevant to this section? If so, where can I find it? If not, what is expected to happen with this note? Please explain. 
What is expected to happen with the “*Add the MTL 2.4 & 3.1 edits/content?” A linked cross-reference? Has this information already been updated or is this referring to the update that will happen? 
- [ ] 7.1 dark gray box: is “wk2 jun_epic #training_workflow” referring to a video? If so, where can I find it? If not, what is expected to happen withthis note? Please explain. 
- [ ] 8.1 dark gray box: is “wk2 jun_epic #training_workflow” referring to a video relevant to this section? If so, where can I find it? If not, what is expected to happen with this note? Please explain.  
- [ ] 8.8 dark gray box: is “video w/Facilitators wk1 jun_epic facilitate_workflow” referring to a video? If so, where can I find it? If not, what is expected to happen with this note?

**Comment by ljmoody** [comment]
@jamesmrollins, no content was provided for 3.8.4 Train QA so I gave it my best shot. Please review & edit in the 2999 workflow Lucidchart before I finalize the 3.8 sticky. Thank you!

**Comment by jamesmrollins** [comment]
FYI @lzim 

See lime colored question mark icons on the [#2999_team_psd_safe_workflows](https://lucid.app/lucidchart/0cd93668-a02d-4176-b97d-4f342985a57f/edit?viewport_loc=1129%2C-10595%2C5756%2C2828%2C0_0&invitationId=inv_3462b1a9-3207-4813-87e1-993924811a3f) locations of the questions below:

- [ ] After meeting with @ljmoody we determined that Example 2, team_time links do not work, and Example 3 does not have a link in 4.6.  However, the video of you explaining things does work. 
- [ ] 7.9 There is no video in Teams quant_workflow channel.
- [ ] 8.5.3 Laura will attempt to find the original meeting in Teams to find the recording.
- [ ] Regarding 4.2 Sticky, unable to determine what this is or what it is for.
- [ ] Regarding 4.3 gray note - not sure what this is asking for.
- [ ] Regarding 4.5 gray note - not sure what this is asking for.
- [ ] Regarding 7.1 - where is the video?
- [ ] Regarding 8.1 - same
- [ ] Regarding 8.8 - same

**Comment by lzim** [comment]
FYI: @ljmoody @jamesmrollins 

### @lzim discussed at team_time with @dkngenda & @claradismuke 
wk4 2023_jun_epic 
- [ ] Need the standard **story point definitions** for each value stream in the Team PSD manual
- [ ] Need the standard **story point scale** for each value stream in the Team PSD manual.

**Comment by lijenn** [comment]
Workstreams by priority that @ljmoody and @lijenn could improve based on the team's current needs:

1. Shared Workstreams (Remove “Across Management Trio" in the header)
    1. Manage Outlook Shared Calendars & Meeting Series
    2. Scope Workflow Dependencies Using User Stories and GitHub/ZenHub AND Manage with ZenHub
    3. Coordinate Train Workflow
2. Coordinated Workstreams
    1. Manage Research Repository Including Readme.md (e.g. link to R01 protocol is broken)
    2. Request New Research Data
    3. Submit VACO and VAPAHCS Progress Report
    4. Contribute to a Team PSD Manuscript
3. Research and Development
    1. Manage Research and Development Workstream Permissions
    2. ~~Manage MTL.Info Calendar and Inbox~~ (Covered in Shared Workstreams)
    3. Achieve Research Value Stream Key Performance Indicators (KPI)
    4. Submit an NIH Grant with PAVIR/Submit a Grant to VA
4. PeopleOps
    1. Manage PeopleOps Workstream Permissions
    2. Achieve Operations Value Stream Key Performance Indicators (KPI)
    3. Set Up MTL Live Teams 
    4. Coordinate ILead Workflow (Edit “EES” to ILead)
5. DataOps and DevOps
    1. Refer to Quality Assurance Process in Chapter 3.8

**Comment by lijenn** [comment]
re: Conversation on being careful with AI, plagiarism, and copyright as our work is open science

- [ ] @ljmoody & @lijenn Add a section in Standard Operations or mentions of Open Science to remind Open Science contributors to use the proper license (GPL-3.0 Copyright) when using parts of our work.

**Comment by ljmoody** [comment]
Contacted @hirenp-esquare about a new error message-see below. 
- [ ] Need to know if this is serious (needs to be addressed) or not.
![a09313cb-678b-403e-ac3c-c39a4175a847.jpg](https://images.zenhubusercontent.com/6483906cab53e03a0946b96b/dcf8ab73-f2cb-40cb-9308-c50b51858ac4)

**Comment by ljmoody** [comment]
Hello @hirenp-esquare. There is another error message when actions fire - screenshot is below. This is happening with multiple files, fyi. 
Same approach as the previous error message:
- [ ] Is this serious and does it need to be addressed?

If so,
- [ ] What change(s) need to be made?
- [ ] How are changes incorporated into both the PSD and MTL manual action checkers?
- [ ] Who is responsible for making these changes?
![image.png](https://images.zenhubusercontent.com/6483906cab53e03a0946b96b/adc3c738-0a97-446f-bdd0-76dd20a665b0)

**Comment by lijenn** [comment]
Discussed 7/17 with Hiren, James, Laura, and Jenn:

- [ ] These deprecation issues come up because we use existing actions/code to run the CI/CD. 
@hirenp-esquare will need to either develop our own or find other existing actions to use.

This will be addressed after @hirenp-esquare incorporates feedback for #2979 and #2964.

**Comment by ljmoody** [comment]
@lzim, can you assist when you're able to with the light and dark gray "video boxes" (in [Lucidchart](https://lucid.app/lucidchart/0cd93668-a02d-4176-b97d-4f342985a57f/edit?invitationId=inv_3462b1a9-3207-4813-87e1-993924811a3f&page=0_0#)) that I have questions about?: 

**Videos I do not have access to—do you still want them added/linked?:**
- [ ] 4.6, example 2
- [ ] 7.9, David N+Swap video from 9/20/22
- [ ] 8.5, linked video from facilitate_workflow channel
- [ ] 8.7, set up a co-planning group or team for fidelity ratings va redcap from 5/2/22

**Confirm the use of videos within specific sections:**
- [ ] 4.3, see "this may also be relevant" video link
- [ ] 7.7, Accessing provider survey data with R notebook (is this correct to use?)

**Videos with personal information—are these okay to use in manual?:**
- [ ] 4.xx, Team PSD Onboarding to Cadence Cycles, all videos in the light blue sticky with orange outline

**Weird video box stuff:**
- [ ] 8.10, note "Alert PAVIR of transition" - What, if anything, needs to be done about this?

**Videos or references to videos I cannot find:**
- [ ] 4.3, wk5_may_epic support_workflow reference
- [ ] 4.5, wk4_may_epic training_workflow
- [ ] 5.1, wk5 may_epic support_workgroup
- [ ] 5.3, wk1 jun_epic team_time
- [ ] 5.4, wk2 jun_epic team_time
- [ ] 6.7, wk5 may_epic hq_workflow
- [ ] 7.1 wk2 jun_epic #training_workflow
- [ ] 7.9, refresh_data_r01_iir is referenced but I cannot find
- [ ] 8.1, wk2 jun_epic #training_workflow
- [ ] 8.6, stand-alone videos referenced in steps #4 and 5
- [ ] 8.8, video w/facilitators wk1 jun_epic facilitate_workflow
- [ ] 8.11, video w/Jenn can self-record in wk1 jun_epic - unsure if this exists

There are two pink stickies (on the left-hand side of the workflow Lucidchart) that list linked 2022 and 2023 videos found in training_workgroup, unsure of where they belong. This **might** help with sussing out videos to manual chapter/section...:
![Screenshot 2023-08-08 at 2.37.02 PM.png](https://images.zenhubusercontent.com/6483906cab53e03a0946b96b/fb5cdfa1-9cd0-429d-b329-bb368033e39e)

FYI: @jamesmrollins @lijenn

**Comment by ljmoody** [comment]
## re: Standard story point definitions and scale for each value stream:

@lzim - Please see below for the proposed section "Understand Story Points" This section seems best fitting within Chapter 4, Shared Workstreams. 
- [ ] Is there a particular placement within the chapter you have in mind?
- [ ] Is there missing information to include?
- [ ] Is there any information on the card you would like to _not include_? 
- [ ] Would you like this section to have a link to these videos: [Video 1](https://dvagov.sharepoint.com/sites/teampsd_vha/_layouts/15/stream.aspx?id=%2Fsites%2Fteampsd%5Fvha%2FShared%20Documents%2Ftraining%5Fworkgroup%2FRecordings%2Ftraining%5Fworkflow%2D20221208%5F080239%2DMeeting%20Recording%2Emp4&referrer=Teams%2ETEAMS%2DWEB&referrerScenario=teamsSdk%2DopenFilePreview), [Video 2](https://dvagov.sharepoint.com/sites/teampsd_vha/_layouts/15/stream.aspx?id=%2Fsites%2Fteampsd%5Fvha%2FShared%20Documents%2Ftraining%5Fworkgroup%2FRecordings%2Ftraining%5Fworkflow%2D20221110%5F092410%2DMeeting%20Recording%201%2Emp4&referrer=Teams%2ETEAMS%2DWEB&referrerScenario=teamsSdk%2DopenFilePreview), Training Workgroup, 12/8/22, defining education value stream, std scale for story points (Fibonacci), fiscal porfolio mgmt, scoping work

![Screenshot 2023-08-08 at 3.57.20 PM.png](https://images.zenhubusercontent.com/6483906cab53e03a0946b96b/20a89be6-3f22-4cd0-a7b1-6be50bc8adfb)
FYI: @jamesmrollins, @lijenn, @dkngenda, @claradismuke

**Comment by ljmoody** [comment]
Hello, @lijenn. When you're able, could you please:

1. View sticky 8.8 in the [2999 Lucidchart](https://lucid.app/lucidchart/0cd93668-a02d-4176-b97d-4f342985a57f/edit?viewport_loc=6547%2C11433%2C4561%2C3382%2C0_0&invitationId=inv_3462b1a9-3207-4813-87e1-993924811a3f) and let me know if:
    - this information belongs in the PSD manual, and in this chapter/section
    - this information belongs in a different chap/section
    - this information should only be in the _MTL_ manual

2. View sticky 6.6 (past the bottom of it, where the text overlays the green). We went over most of this sticky + content last Friday, but I'm wondering: 
    - where do the two "Patient Enrollment" numbered lists belong
    - if these two lists should be combined

**Comment by ljmoody** [comment]
Closing this issue and breaking work into smaller chunks - see issue cards #2995, #3040, #3041, #3042, #3043, #3044
