### ISSUE TITLE
2025_3rd roadmap: TEST Reports Generator

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3028]
## AC:
- [ ] all feedback to DEV is addressed and/or incorporated
- [ ] validate Tutor wireframes

## To Test:
- [ ] Can a team vision statement be edited? --> _Jenn and Laura can (within _MTL_ Reports)._
   - [ ] Jenn and Laura need to test within Sim UI (see [Research issue 742](https://github.com/lzim/research/issues/742))
   - [ ] After that, need Debbie to check since she reported [Research issue 742](https://github.com/lzim/research/issues/742).
- [ ] The xlsb file mentioned: "Use the clinic selection table (mtl_site_list_sta6a_203_08_09 (version 1).xlsb to find the full Sta6a." Located in sec 7.0, Make, View, and Export Team Clinic Selections for Import to Sim UI. Folder pathway given in document; possible to change current revision updates so file name stays the same and evergreen link can be placed into _MTL_ Manual?

## Decisions:
- [ ] Team Name should appear at top center of generated report (with vision statement directly under).
- [ ] _**All MTL Red reports** should have Data Tables._
- [ ] Keep or remove **Care Decision Meters**? - _Keep; they're for **MTL Blue only**._
- [ ] Should **Team Data tables** be included in reports? - _Yes, there **should be an OPTION** for Team Data Tables to be included in MTL Blue reports._
  - [ ] Additional questions for Lindsey about Data Tables: 
![image](https://github.com/lzim/teampsd/assets/124643236/f1ca3508-269d-4c8f-9a28-a7596745820e)

- [ ] _MTL Red / Blue logos should appear in bottom right-hand corner of page._
- [ ] Have _MTL_ Red and _MTL_ Blue header logos on the reports? - _Yes, **include MTL logos and MTL Blue/Red logos** on respective reports._
- [ ] In **_MTL_ Reports popup**, add back in:
  - [ ] old Research Arm dropdown - **rename dropdown "Version"** with following selection choices:
    - [ ] Blue
    - [ ] VA Red
    - [ ] NIH Red
    - [ ] Other
![image](https://github.com/lzim/teampsd/assets/124643236/f5933353-0ec7-4fd1-bc9f-5ab5882787db)

- [ ] Keep or remove Charts section entirely? - _re: "Charts" "section"... 
  - _Does reflect the Sim UI Blue Bar definition of  "section?"_
   - If Sim UI "Section" then it should be labeled "Report"
   OR
   - _Does this reflect the Results Dashboard of the Sim UI within the report?_ If yes, then MTL Blue only.
    
- [ ] Rename "Charts" section to "Reports"? (Since user choices in "Select Reports" field map here.) - _If "Charts" are Sim UI Results Dashboard, then menu should be "Select Simulation Results." [should add 'simulation' to distinguish the results]_
  - [ ] Rename as such:
![image](https://github.com/lzim/teampsd/assets/124643236/87baeeee-8359-4316-927d-62b529fab28c)

**Comment by ljmoody** [comment]
Hello @tejaspesquare. Jenn and I tested the reports generator and have the following feedback after today's session:

- [ ] 1. Adjust spelling:
![image](https://github.com/lzim/teampsd/assets/124643236/18665f73-7b38-4a7a-9bf0-f1b89789d0d2)

- [ ] 2. Edits (3 total) to _MTL_ Reports pop-up window:
![image](https://github.com/lzim/teampsd/assets/124643236/7617e22a-43ef-47fd-b36e-e3ccac34fbfc)

- [ ] 3. Two changes to font size offerings and default:
![image](https://github.com/lzim/teampsd/assets/124643236/5115b470-f120-4142-81d1-5c0474cfc990)

- [ ] 4. Insert image issues (2):
![image](https://github.com/lzim/teampsd/assets/124643236/eda5b849-7c5b-4e1e-9219-105d1e0ec6e2)

- [ ] 5. Additional image issues:
![image](https://github.com/lzim/teampsd/assets/124643236/f949898f-52fa-4006-a04a-3497f67d89b1)

- [ ] 6. Scrolling modifications within _MTL_ Reports pop-up window:
![image](https://github.com/lzim/teampsd/assets/124643236/aec002b4-880c-4f22-a0e6-7dc42f68dc8c)

- [ ] 7. Team Flow data stock misbehavior:
![image](https://github.com/lzim/teampsd/assets/124643236/1590d3f0-dc47-4ab7-8949-cf3ab99ef517)

- [ ] 8. _MTL_ Reports pop-up window spelling correction:
![image](https://github.com/lzim/teampsd/assets/124643236/d3f1078f-3db9-4228-8a6d-84a7598e793d)
 
- [ ] 9. Additional checkboxes needed under "Select Causal Loop Diagrams" and "Select Flow Meters":
![image](https://github.com/lzim/teampsd/assets/124643236/892297c4-af3a-464a-b719-e96538112ff3)

- [ ] 10. _MTL_ Reports preview/save issue + italicize "MTL":
![image](https://github.com/lzim/teampsd/assets/124643236/af470432-8951-4863-9f24-da02e98ea096)

- [ ] 11. Three (3) corrections on generated report output:
![image](https://github.com/lzim/teampsd/assets/124643236/4f6ccd68-7047-4169-aab0-88db754306fa)

- [ ] 12. Correction of heading on generated report (specific to Chart-2):
![image](https://github.com/lzim/teampsd/assets/124643236/4a984fe7-14c8-43fa-af50-eb9089d06236)

- [ ] 13. Remove formatting options within the generated report:
![image](https://github.com/lzim/teampsd/assets/124643236/3ff7c41b-6826-466b-8c7b-e1411d8aee0c)

- [ ] 14. Three (3) suggested improvements to the _MTL_ Reports pop-up window behavior and headings:
![image](https://github.com/lzim/teampsd/assets/124643236/6a5b4bda-5a13-4949-b580-2e75685d5b77)

- [ ] 15. Report does not export to Word:
![image](https://github.com/lzim/teampsd/assets/124643236/11d875ce-bb25-41ea-b489-3d4626eb49d3)

- [ ] 16. Scrolling behavior in Report Preview affects Generated Report output:
![image](https://github.com/lzim/teampsd/assets/124643236/3c751ddd-1d95-4d98-9cb5-47e76e928de2)

FYI @lijenn & @jamesmrollins.

**Comment by tejaspesquare** [comment]
@ljmoody - Please see my response

Point 2 - Edits (3 total) to MTL Reports pop-up window:-  i.  Removing drop-down is not possible (Select Team)   
Point 3 - Two changes to font size offerings and default:- By default it will Small, user wants then need select Normal explicitly.
Point 5 - Scrolling modifications within MTL Reports pop-up window: - yes, popup window size is very much possible.
Point 8 - Additional checkboxes needed under "Select Causal Loop Diagrams" and "Select Flow Meters":- Sections Loop Diagrams, Flow Meters & other details are displayed based on drop-down selection of Group Name & Module from top. It is not possible to present all in just a single combination.
Point 9 - MTL Reports preview/save issue + italicize "MTL": - Press 'Save' will save details only whereas on click 'Preview' will save & show saved details. We have set delay time of 10secs so that all selected data save properly.
Point 10 - Three (3) corrections on generated report output: - Services/Settings ->   It will represent information related top service by default & user have provision to change it. Do we really need to restrict user to fetch details of other services?  
Point 13 - Three (3) suggested improvements to the MTL Reports pop-up window behavior and headings: It will erase all filled details of previous combination after toggling to different module.
Point 14 - Report does not export to Word:  This is working at our end. Can you please share downloaded file to verify at our end.
Point 15 - Scrolling behavior in Report Preview affects Generated Report output: This is not possible to change its behavior because limitation of editor.
Point 16 - James informed us that users should be able to edit/revise the text in the Word or PPT export. Any updates on this feature? : - We tried to make it happen but unfortunately not found any solution.

FYI @lijenn & @jamesmrollins

**Comment by tejaspesquare** [comment]
@ljmoody - Please find status:

Points done - 1,2,3,4,5,6,7,8,9,10,11,12,13,15
Point 14 - Report does not export to Word: If issue persist then please share downloaded document with us.

FYI @jamesmrollins @lijenn

**Comment by lijenn** [comment]
@tejaspesquare Attached is the Word file. The feature generates this file, but it is corrupted and an error message pops up when trying to open it.
[MTL_Reports_sp_09_15_jenn_friday_test_team_2024_1_17.docx](https://github.com/lzim/teampsd/files/14004872/MTL_Reports_sp_09_15_jenn_friday_test_team_2024_1_17.docx)

**Comment by tejaspesquare** [comment]
@lijenn - I'm able to download & view attached word file.
![image](https://github.com/lzim/teampsd/assets/144898781/a66577c7-ea4c-43e0-bdc9-7829e0636801)
![image](https://github.com/lzim/teampsd/assets/144898781/57d03dd9-8041-4716-ad6d-4404dc406953)
![image](https://github.com/lzim/teampsd/assets/144898781/30ad029c-085e-47c9-9fa9-7ca07dd61d05)

**Comment by lijenn** [comment]
@tejaspesquare What program/app are you using to open the file? Our users use Microsoft Word. I get this error when opening the file in Microsoft Word: 
<img width="268" alt="image" src="https://github.com/lzim/teampsd/assets/59668647/e73d84d9-5476-40f3-b3af-03ca6ec976a8">

**Comment by tejaspesquare** [comment]
@lijenn - We have WPS office installed on our machine. There is an issue while opening with Microsoft office setup. We will fix this problem & will let you know.

**Comment by ljmoody** [comment]
Hello @tejaspesquare 

> **from Praxis Teams 2/5/24:**
> MTL Reports: Viewing Downloaded Report (Word file): This is partially resolved. Can you please verify in development environment. Viewing doc in Print Layout having some issue but you switch to Web Layout it should work as expected. 
Also, covered red asterisks Recommendation & Experiments  fields. 
Note: Team Care having some header issue, that we will look into it**

I tested in DEV environment today and this is what I experienced:
1. _MTL_ Report exported to Word, print view:
![image](https://github.com/lzim/teampsd/assets/124643236/7c005031-e2a8-4806-aa5d-0898044cbf1d)

2. _MTL_ Report exported to Word, web view:
![image](https://github.com/lzim/teampsd/assets/124643236/ddb788ca-698d-433b-a4ab-671f35dbcfe7)

3. _MTL_ Report exported to PowerPoint view:
![image](https://github.com/lzim/teampsd/assets/124643236/01042638-e59a-4324-a988-f085632ce331)

4. Your revision to the Selected Reports area looks good!: 
![image](https://github.com/lzim/teampsd/assets/124643236/72988a95-a4a7-48bc-adae-cf4829efbc10)

fyi @jamesmrollins @lijenn

**Comment by tejaspesquare** [comment]
@ljmoody  - You see PROTECTED VIEW due to settings applied in File properties. Click on 'Enable Editing' will allow to view file content. 
To fix it permanently please apply following solution in Word:
Go to File > Options. Select Trust Center > Trust Center Settings > Protected View. Clear the box for Enable Protected View for files originating from the internet.

FYI - @lijenn

**Comment by ljmoody** [comment]
@tejaspesquare, Thank you for pointing that out and giving me instructions! I did it and can now see the Word report. I'll check the functionality of it with Jenn and give any feedback we have after that.

**Comment by ljmoody** [comment]
Hello, @tejaspesquare - please see the [wireframe_MTL Reports tutor.pdf](https://github.com/lzim/teampsd/files/13996001/wireframe_MTL.Reports.tutor.pdf) for the _MTL_ Reports tutor prompt wireframe.

- [ ] Add new: 
![image](https://github.com/lzim/teampsd/assets/124643236/46f528ce-b7c1-4284-95e8-04c434257656)

**Comment by ljmoody** [comment]
Hello @tejaspesquare. Jenn and I tested again today and have this feedback to offer:

- [ ] 19. When text is selected and "Increase Indent" is clicked, it indents the text AND increases the font size. Formatting should be stable. See screenshots below: 
![image](https://github.com/lzim/teampsd/assets/124643236/4e4cee17-47ce-4e42-a38d-be5c15c34394)
![image](https://github.com/lzim/teampsd/assets/124643236/f5358e98-6129-4009-b307-7827cbfe9a38)
![image](https://github.com/lzim/teampsd/assets/124643236/760ab511-3a00-4c62-949f-6b113935b244)

- [ ] 20. Pressing the **Preview** button leads to the same message as when the Save button is pressed. 
Please change **Preview** button pop-up to say "_MTL_ Reports is generating a preview."
![image](https://github.com/lzim/teampsd/assets/124643236/d2d57a33-52df-4a90-90eb-0169c4bac7e6)

- [ ] 21. FYI: Exported reports are still not functioning correctly (.doc and .ppt).

- [ ] 22. When a user imports a document to a report that includes a hyperlink, how can a user open the hyperlink in the reports generator? We cannot get it to function/open, although it appears as a hyperlink (tried CTRL+Click, CTRL+Shift+Click, ...) 
We are able to remove the hyperlink, though (by right-clicking, selecting RemoveLink). 
![image](https://github.com/lzim/teampsd/assets/124643236/735179e7-881b-4feb-87b0-9c73a7a55cc1)

- [ ] 23. When a user imports a document to a report, we noticed formatting **not** transferred over from uploaded documents includes: highlighting, underlining, and text color. 
![image](https://github.com/lzim/teampsd/assets/124643236/532e6297-24b7-468b-ba09-e54bdf626f9e)

- [ ] 24. Add Consult Vision statements to the generated reports:
![image](https://github.com/lzim/teampsd/assets/124643236/1b75eb0c-19c6-4c3e-b998-2c1b7985d3da)
![image](https://github.com/lzim/teampsd/assets/124643236/1f0e6147-5f3e-41e9-979e-5c0edfad5291)

**Comment by lijenn** [comment]
Hi @tejaspesquare Here is the .doc and .pptx files for the 09_15_jenn_friday_test_team in TEST. 

The .doc file does not show any output (I will send in Teams, GitHub does not allow me to upload).
The image scale in the .pptx is too large/stretched.
[MTL_Reports_cc_09_15_jenn_friday_test_team_2024_2_15.pptx](https://github.com/lzim/teampsd/files/14325326/MTL_Reports_cc_09_15_jenn_friday_test_team_2024_2_15.pptx)

**Comment by tejaspesquare** [comment]
@lijenn - At this juncture it looks like time consuming to fix issue for .docx version. However, we will give a try sometime later once time permit.

One more update regarding Recommendations section: We are able to represent this block in editable mode however couldn't find a way to bring logo & design formats applied for rest of sections in a report.

Please have a look below,
![image](https://github.com/lzim/teampsd/assets/144898781/4c2ac004-d215-4959-ba99-d7d2afd69ee1)

For your review, tomorrow we will publish it on Dev environment (https://forio.com/app/va/va-psd-dev/login.html). 

FYI @jamesmrollins, @ljmoody

**Comment by tejaspesquare** [comment]
@jamesmrollins , @ljmoody , & @lijenn - Points #19 To #24 are resolved & moved to TEST-Slow. Please verify & let us know your feedback.
Point #23- Formatting of exported document works with all features except underline.

Report Recommendations: We currently observe a discrepancy between the icon and box appearance in relation to the UI of other sections in the exported document. It is my understanding that aligning the UI is not a current priority for us. However, we are committed to addressing these UI issues at our earliest convenience.


![image](https://github.com/lzim/teampsd/assets/144898781/297fb0d8-79ec-4b10-9537-116e5d23f7d6)

**Comment by ljmoody** [comment]
@tejaspesquare - Hi there! I used TEST instance to review the following points and have this feedback to offer: 
(fyi @lijenn, @jamesmrollins)

- 19 - increase indent formatting is stable
- 20 - Preview button text is now different from Save:
**James / Jenn:**  _What do you think about the message? Should it be as shown or "MTL Reports is generating a preview." or something else?_
![image](https://github.com/lzim/teampsd/assets/124643236/f4f3fb39-888d-4bc3-aa87-2d58fbbb24d2)
- 21 - I unchecked this box above as the reports still need fine tuning. The text now exports in a way that is editable in .doc format. 
**Tejas:** _Is it possible to remove the gray background color from the text field?_ This is what I observed when exporting to Word:
![image](https://github.com/lzim/teampsd/assets/124643236/7d399eb0-f2fa-4245-981c-83ef468f6b3d)

This is what the generated PDF looks like now:
![image](https://github.com/lzim/teampsd/assets/124643236/a69e7829-2fff-4635-8688-757968608e24)
- 22 - importing a document with a hyperlink - this is what I observed. 
**James / Jenn:**  _Is this the desired behavior?_
![image](https://github.com/lzim/teampsd/assets/124643236/4a625c89-e8c1-4eed-b7ac-4f9d1cc63945)
- 23 - importing formatted documents to report
**Tejas:** I do not see any formatting carry over to the report except for bolding and hyperlink. I unchecked point 23 above.
![image](https://github.com/lzim/teampsd/assets/124643236/605ca4cc-cbf9-4f34-8976-1060f9ef5d60)
- 24 - Consult Vision statement 
**Tejas:** The vision statement is now showing in the report preview. However, it's not showing in the exported reports, FYI. I unchecked point 24 above.
![image](https://github.com/lzim/teampsd/assets/124643236/e0922214-383d-4968-92b4-35794ce31d5f)

**Comment by ljmoody** [comment]
@tejaspesquare - I updated the link to the wireframe_MTL Reports tutor.pdf. You should have access now.

**Comment by tejaspesquare** [comment]
@ljmoody - 

Point #20: We will change text as mentioned.
Point #21: Recommendation box - 
    i. We will remove gray background color from text field
    ii. Heading font face will appear for Recommendations as Word document settings in user's system
    iii. Exporting to word: Can you please change view of the document from Main menu (View). In our system we are able to see 
         it properly.
         
      
![image](https://github.com/lzim/teampsd/assets/144898781/b3af2385-aef4-458e-8fc2-712d4fc1a0b4)

        
        
        
        
        
Point #22: Hyperlink - This will only work if you export a document (word). For PPTx it is not possible as it always rendered as image. 
Point #23: Formatted document to report: underline, Highlight & text color these three not going to work.

**Comment by ljmoody** [comment]
@tejaspesquare - regarding points #21, 23, 28: We spoke with James today and he would like to discontinue the Word and PowerPoint reports. Instead, is it possible to:

- [ ] rasterize the text input
- [ ] have a print to PDF option for users to save/print
- [ ] make the PDF portrait (not landscape) orientation
- [ ] no part of the report or its graphics run off the page
- [ ] include _MTL_ Reports logo at top left of page
- [ ] eliminate formatting options from this menu that are not kept when: 1) importing documents and/or 2) exporting to pdf:
![image](https://github.com/lzim/teampsd/assets/124643236/80fd9893-0ddb-4b61-8ff3-a2ae028899b9)

**Comment by ljmoody** [comment]
Hi @tejaspesquare and team! Before your weekend begins, please give us an update on this issue (progress, level of effort, estimate to complete, etc.). Thank you~

**Comment by tejaspesquare** [comment]
@ljmoody , @lijenn - Export to PDF is available to test on SIM-Dev environment. Kindly verify & provide your feedback.

![image](https://github.com/lzim/teampsd/assets/144898781/f4201efb-46f9-4ef3-9931-386353c529bf)

![image](https://github.com/lzim/teampsd/assets/144898781/44a6090d-8382-4dca-82fb-4bafc3b7b4e7)

![image](https://github.com/lzim/teampsd/assets/144898781/4d526c50-30f0-4eb6-adcc-b6bd7c4994db)

**Comment by ljmoody** [comment]
@tejaspesquare - we'll meet with Lindsey tomorrow and provide feedback based on decisions made with her input.

**Comment by tejaspesquare** [comment]
@ljmoody - PDF Report: It is **not recommended** to have all images one after other without page breaking. If we do so this will make page getting shrink while doing print & even it won't be available in proper readable format post print. However, if it is required then required POC (proof of concept) & after it can derive actual efforts.

**Comment by ljmoody** [comment]
Thanks, @tejaspesquare, for the information about the PDF report and pages. We will discuss and let you know if a POC or development is needed.

**Comment by tejaspesquare** [comment]
@jamesmrollins , @ljmoody , & @lijenn  - FYI Tutor development (wireframe_MTL Reports tutor.pdf) is done & it is available for testing on TEST-Slow. Please be informed we also doing testing in parallel.

**Comment by ljmoody** [comment]
Hi @tejaspesquare, I started testing this today and then Test-slow began behaving oddly. I'm unable to see Tutor prompts past the first couple now. Because the _MTL_ Reports function has been deprioritized and moved forward to late April and beyond, and may likely also change somewhat, I am going to hold off on reviewing these Tutor prompts.

**Comment by hnorthcraft** [comment]
@lijenn this is closed as not planned, but there seems to be a lot of work here. Do you have an idea for SP estimate?

#adjudicate_memo

**Comment by lijenn** [comment]
@hnorthcraft 8 SP due to several interdependencies across the tech stack and users for this feature.
