### ISSUE TITLE
2024_10: Update mtl.how/demo to reflect 3.7 release

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3158]
fyi: test card for mtl.how/demo is #3219 
## User Story

As a person interested in _Modeling to Learn_, I would be very interested to get more information about how it works and to see a demo of the simulation user interface.

### GIF section:
- [x] gif 1: recreate - has Team (AGG) Care in blue header @ljmoody
- [x] gif 2: recreate - has Team (AGG) Care in blue header @ljmoody
- [x] gif 3: recreate - has Team (AGG) Care in blue header @ljmoody
- [x] gif 4: recreate
- [x] gif 5: recreate - has Team (AGG) Care in blue header @ljmoody
- [ ] ~Make new gif to highlight DDD: begin at Home page, navigate to ellipses, then show Feedback Loops, Decision Meters, & Episodes of Care @ljmoody~ - revised task due to time limit of gif vs number of DDD features to show. New task:
- [x] Make gifs to highlight DDD features:   @ljmoody 
  - [x] gif 6: Home page>ellipses>feedback loop - use checkboxes to show loop dynamics, move window, resize window, close
  - [x] gif 7: Home page>ellipses>decision meter - show population of fields + save
  - [x] gif 8: Home page>ellipses>episodes of care, click "i" icon, scroll, close
- [x] Reminder: once flow is finalized, DDD gif may need to be revised or create new to demonstrate Flow - _created a new issue for this, #3259_
- **FYI:** 10-13 seconds limit on gifs, make via Snagit
- **FYI:** **Team Care** is preferred demo model

### _Modeling to Learn_ section
👉 **Use Selena's icons for these:** @matthewtomo 
- [x] replace mtl blue icon
- [x] replace mtl red icon 
- [x] change mtl Video icon to mtl video (lowercase)
- [x] change mtl Facilitate icon to mtl facilitate (lowercase)
- [x] change mtl Demo icon to mtl demo (lowercase)

### Run Your Test section
- Run: ✅
- mtl Demo: ✅ 
- [x] mtl.how: update link to **https://site-97998392.bcvp0rtal.com/** (from [this comment](https://github.com/lzim/teampsd/issues/3057#issuecomment-2264278379) in card 3057) @ljmoody
- [x] mtl mtl.how/sim: update link to open image only (not within GH) if possible @ljmoody
- [x] mtl.how/facilitate: "Click to access the VA Forio _MTL_ Simulation UI at https://mtl.how/facilitate." 

### Videos section
- [x] **_Review with Lindsey_**
- Vapor: ✅ 
- [x] mtl Live: change thumbnail to "mtl Facilitate" and change description to "Quick Start for _MTL_ 1.0-3.0 Implementation Facilitation" @ljmoody 

_Reviewed videos below with Lindsey at wk3 2024-09  sim_ui_. **Videos below to be removed.**
- ~mtl session 1, team vision: link intact; _needs update to reflect pivot to consult_~
- ~mtl session 2, data user interface: link intact; _needs update to reflect pivot to consult_~
- ~mtl session 3, team data: broken link; _needs update to reflect pivot to consult_~
- ~mtl session 4, team needs: broken link; _needs update to reflect pivot to consult_~
- _Any other videos identified to add?_
  - [x]  1. mtl Consult icon, video description: "Quick Start for _MTL_ 3.7 Consult" - created #3258 to track creation and addition to demo site 

### Slides section
- slide 1: ✅

### Papers section
- paper 1: ✅
- [x] paper 2, CC: to be updated @matthewtomo 
- [x] paper 3, MM: to be updated @matthewtomo 
- [x] paper 4, PSY: to be updated @matthewtomo 
- [x] paper 5, Team Care: 
  - [x] remove "Agg" from title hyperlink
  - [x] to be updated @matthewtomo 
- [x] paper 6, Team Flow: 
  - [x] remove "SP" from title hyperlink
  - [x] to be updated @matthewtomo 

## AC for DEV
- [x] Update the simulation user interface to version 3.7 for the mtl.demo websites (DEV/Test_slow/PROD)
- [x] Update all in mtl_demo_test_slow. We will test before promotion to Prod.
- [x] Check if Vensim model documentation for all modules are the latest version -@matthewtomo 

## AC for card closure
- [x] TEST instance updates reviewed by Lindsey
- [x] any modifications from review are made
- [x] notify @matthewtomo when TEST is ready to migrate to PROD
- [x] close card once updates are made to PROD

**Comment by lzim** [comment]
wk1 2024_06 #sim_ui_workflow
Discussed this at wk5 2024_05 worklow meeting. 
@lzim updated to reflect completion in June (2024_06)

**Comment by lzim** [comment]
Cross-Ref: https://github.com/lzim/research/issues/824 - For the Vensim DSS Version Release names assigned to @tomrust and @jamesmrollins

**Comment by lijenn** [comment]
@lijenn will get a team data file, anonymize it, rename to model_parameters, and add it in this card for Dev to upload into MTL Demo.

**Comment by jamesmrollins** [comment]
@lzim 

- [ ] @tejaspesquare reports this effort will require 4 days.  
- [ ] @ljmoody will test 7/5.

**Comment by tejaspesquare** [comment]
@jamesmrollins , @ljmoody , @lijenn ,
Following few concerns wanted to clarify.
 
1.Highlighted in Red -The links highlighted in red will be deactivated to prevent users from taking any action on them.
 
![image](https://github.com/lzim/teampsd/assets/144898781/f7f5e870-87e6-4dee-8dac-0b4447edec0a)
 
Module -> More menu
 
![image](https://github.com/lzim/teampsd/assets/144898781/3f80ccda-8e11-4c82-9782-830dded73bb8)
 
Decision Meter - Save button will be disabled
 
![image](https://github.com/lzim/teampsd/assets/144898781/411c89bc-0770-4ca0-9941-1ab8e93d401f)

2.Directives - It will render a table but without any data.

![image](https://github.com/lzim/teampsd/assets/144898781/82a2f215-5d11-4180-b7d8-49ed961f42ae)
 
3.The More menu links will be preserved as they only contain read-only information, except for the save button in Decision Meter as specified in point #1.
 
![image](https://github.com/lzim/teampsd/assets/144898781/0ce9ce07-354e-4fc5-9502-1ed772e4e05b)

 
Please indicate if any details have been overlooked or if you would like to make any additional suggestions.

**Comment by lijenn** [comment]
@tejaspesquare I messaged you the model parameter file via Teams for MTL Demo 3.7. Thanks!

**Comment by tejaspesquare** [comment]
Hello @jamesmrollins 
Thanks for your response.

We will make changes according to your notes.
Just one thing wanted to highlight reg. point #2: To add Directives Maintenance section estimating development time required 1 to 2 days.

Thank You!

**Comment by jamesmrollins** [comment]
FYI @lzim @lijenn @ljmoody 

## Sim UI Update 7/8

- [ ] DEV has worked out to create a demo account using the V3 API will Forio last night.
- [ ] They have completed and are testing the full use case for CC model.  
- [ ] They have validated the ability to save experiments.
- [ ] They intend to continue developing this week and will advise when ready to test.

**Comment by tejaspesquare** [comment]
Hello @jamesmrollins, @ljmoody, @lijenn,

Code has been promoted to TEST environment & is ready for testing.
1. Demo user registration
2. Save & Export Experiments

![image](https://github.com/lzim/teampsd/assets/144898781/30bc5ffa-d509-4b88-b7e3-73806940009f)

**Comment by tejaspesquare** [comment]
Hello @lzim, @jamesmrollins, @ljmoody, @lijenn,

**Comment by tejaspesquare** [comment]
Hello @lzim @lijenn @ljmoody @tejaspesquare
> * [ ]  Perhaps we can create a notification email or some other means to notify Admins that a demo account has been created, or a question has been asked in the Chat.

**Comment by lijenn** [comment]
@tejaspesquare, please see the bugs @ljmoody and I encountered while trying to test the Demo Sim UI in TEST:
- [ ] Unable to log into the Demo site (using existing logins). We selected the demo-jul-2024 option, clicked Select World, and nothing happens. It's a recursive loop:<img width="978" alt="image" src="https://github.com/user-attachments/assets/98e2ce2e-32e5-4457-b6f2-ddebb93d2cfe">
- [ ] Missing the "s" in "Dynamics" in invitation email 
<img width="787" alt="image" src="https://github.com/user-attachments/assets/3c17b99d-859e-4184-9647-25ee183d967c">

**Comment by tejaspesquare** [comment]
Hello @lijenn, @ljmoody, 

> @tejaspesquare, please see the bugs @ljmoody and I encountered while trying to test the Demo Sim UI in TEST:

> * [ ]  Unable to log into the Demo site (using existing logins). We selected the demo-jul-2024 option, clicked Select World, and nothing happens. It's a recursive loop:

we have blocked calling a group "team_mtl_demo-jan-2019" on Epicenter.
![image](https://github.com/user-attachments/assets/4e5d8105-d4b7-45e2-ba48-33e0a6589699)

Please note that all new members (in the Administrator/Facilitator role) must be set up through Epicenter.
@lijenn - Your ID(pavir) has been set up as the facilitator for the new group "team_mtl_demo-jul-2024". Kindly log in and confirm.
![image](https://github.com/user-attachments/assets/c58cf1c7-ddf8-4b24-8432-e1fd200503b8)

**Comment by lijenn** [comment]
Discussed 8/2 @ljmoody @lijenn:
- [ ] Test wk1 2024_08 and provide feedback.

**Comment by ljmoody** [comment]
@matthewtomo, could you please replace "mtl facilitate" icon with the "mtl consult" icon on the demo page? I haven't found how to change it via the demo admin page. There's a mtl_consult.png located [here](https://github.com/lzim/teampsd/tree/master/resources/logos).
![image](https://github.com/user-attachments/assets/ecd2feb9-783f-485c-b405-ff6648a23823)

**Comment by matthewtomo** [comment]
@ljmoody

- It looks like those images can not be replaced through the Admin Dashboard and are "hard-coded" into the html. 
- I was able to replace the old facilitate logo with the consult logo, but it stands out differently compared to the other logos (red arrow appears thicker):
![image](https://github.com/user-attachments/assets/a0d1faab-29ab-4c1d-8970-beeeef58698a)
![image](https://github.com/user-attachments/assets/41fe1b1d-5edb-419e-9e87-99af89fb1577)
- One thing I noticed was that the the image you provided me was a .png, but all of the other logos in the row are .svg files.
- Do you have access to any alternate versions of that logo that might be to a different scale or be in the format of .svg?

**Comment by ljmoody** [comment]
**09/11/2024** - reviewed mtl.how/demo page top to bottom with @jamesmrollins @matthewtomo @ljmoody. Updated acceptance criteria at the top of this card based on our discussion and findings.

**Comment by ljmoody** [comment]
@tejaspesquare, this blue bar heading (in Sim UI Play page for Team Care) needs to be updated so demonstration gifs can be recreated. 
- Change heading to "Team Care" (remove AGG)
- Please notify when implemented in PROD instance so gifs 1, 2, 3, & 5 can be remade without showing that detail. 

![image](https://github.com/user-attachments/assets/8f7cb9d3-19a2-4e14-8228-5740fa8a9ed5)
fyi @matthewtomo

**Comment by matthewtomo** [comment]
**Discussed Dev Standup wk_3 2024_9**
@matthewtomo @tejaspesquare 

- [ ] "Agg" needs to be removed from header in aggplay pageof sim_ui. @matthewtomo will handle this and then notify @ljmoody
- [ ] We need to ensure that all of the DEV, TEST, and PROD demo UIs are up to date with the DEV, TEST, and PROD sim_ui UIs.
- [ ] Dev team will investigate to make sure that the Demo site is up to date and that there are no unaddressed bugs.
  - [ ] This includes sign-in and start a session issues that we ran into during this meeting.

**Comment by matthewtomo** [comment]
@ljmoody, AGG is now removed from the PROD environment on that blue bar.

fyi: @tejaspesquare, I removed it in aggplay.html on the main branch and updated it in Epicenter. This will be easy to address when merging next round of updates from TEST to PROD.

**Comment by ljmoody** [comment]
**Decisions at wk2 2024_09 9am_workflow**
@lzim @matthewtomo @ljmoody @dlkibbe @dlounsbu 
- Add thumbnail: _MTL_ Facilitate
  - accompanying text: Quick Start for _MTL_ 1.0-3.0 Implementation Facilitation
  - link to: mtl.how/facilitate

@lzim, I realize I didn't have 100% shared understanding with this decision. _Is the above to add in addition to the existing content or to replace the mtl.how icon, text, and link?_

**Comment by ljmoody** [comment]
For documentation purposes, I'm pasting notes used to create gifs. Maybe they'll come in handy to someone down the line. 🤷  All gif files are located in mtl>gh-pages>images folder.
- fyi: limited to 13 seconds

### GIFS
**1. Team Care - file name: demo_gif1_reveal_dynamics**
- Show Appointments section 
- Reveal dynamics (all)
- Click "i" icon, display, move around, then close that window

**2. Team Care - file name: demo_gif2_qhfd_fields**
- Show Patients section 
- All reveal dynamics checkboxes checked 
- Type "Type your question here . . ."
- Type "Type your hypothesis here . . ."

**3. Team Care - file name: demo_gif3_experiments**
- before recording - Scoot Text blue bar to left to reveal Experiments blue bar  
- Select an experiment, press Go
- Review previous settings popup: press Go
- Float over the text that was populated in Text blue bar
- Float down near supply slider showing numbers

**4. Team Care - file name: demo_gif4_outputs_and_text**
- before recording, open Outputs and Text blue bar - expand to most of screen
- Scroll down to control panel: PSY
- Alt 1: pick one
- In top left graphic, use dropdown to select Patient Start Rate

**5. Team AGG Care - file name: demo_gif5_sim_tutor**
- before recording: show appts at top, all dynamics chosen
- Circle then press tutor button
- Click through 2-3 tutor messages
- Click tutor X button

**6. DDD, focus feedback loops - file name: demo_gif6_ddd_feedback_loop**
- Display DDD
- Go to Team Care>More
- Open Feedback Loop 
- Show loop dynamics
- Move & resize window
- Close window

**7. DDD, focus decision meter - file name: demo_gif7_ddd_decision_meter**
- Display DDD
- Go to Team Care>Decision Meters
- Populate patients/wk
- Save

**8. DDD, focus episodes of care - file name: demo_gif8_ddd_episodes_of_care**
- Display DDD
- Go to Team Care>Episodes of Care
- Click "i" icon
- Scroll down CPT Code Cheatsheet
- Navigate back to pop-up and close

**Comment by lzim** [comment]
**wk3 2024_09 #sim_ui_workflow**
@ljmoody 
@matthewtomo 
@lzim 

## mtl.how/demo
01. _Want a demonstration?_ Register
02. _Already registered?_ [see below]
03. Consult
04. _MTL Red_ - Data User Interface Cheatsheet
05. _MTL Blue_ - Simulation User Interface Cheatsheet
06. _

### Text Edits
01. _Need a demonstration?_ Click on the icon to register for a free demonstration of _Modeling to Learn 3.7_
02. _Already registered?_ Click on the icon for the existing user login page at https://mtl.how/demo_login.
03. Edit the Consult Logo to this one: 
04. _MTL Red_
05. 
06. Click to access the VA Forio MTL Simulation UI at https://mtl.how/facilitate.

**Comment by tejaspesquare** [comment]
Hello @ljmoody ,
As per notes from Teams: 
> DECISION: 
> ALL instances of "AGGREGATE" or "AGG" should now be only "Team Care" in any Sim UI, Demo, Team, Documentation.
> ALL instances of "SP" should now be only "Team Flow" (keeping the setting predecessor GMH/SMH/PC PCMHI as appropriate)

These changes are available on Dev environment. 
- [ ] SIM UI
- [ ] MTL Demo

<ins>Team Care</ins>
![image](https://github.com/user-attachments/assets/2fa4e9e6-3762-4359-9f91-605cdef905f8)

<ins>Experiment</ins>
![image](https://github.com/user-attachments/assets/5198bd5a-e597-4ebe-9bcd-1d12dbd4f2a9)

<ins>Team Flow</ins>
![image](https://github.com/user-attachments/assets/5913b1f2-09b0-4291-abe2-c0127416a84a)

<ins>Note</ins>: For this development, it is recommended to avoid manual deployment & get support using Git CI-CD to facilitate the deployment of code into TEST & Prod environment as it involves changes at multiple locations.

**Comment by ljmoody** [comment]
- @matthewtomo, I appreciate you trying to switch out Facilitate image to Consult image with the logos we have! Seems that we don't currently have all "matching" logos in svg or png format; as you identified, the red arrow thickness differs. 

- [ ] @jamesmrollins, can you create a new .svg file of the _MTL_ consult icon (and also create an accompanying png file) to match the size of the other images and same thickness of the red arrow? Then we'll be able to update the demo site>Run Your Test section with the needed image and accompanying text+links.

> * I tried using some of the other images from [your link](https://github.com/lzim/teampsd/tree/master/resources/logos) for the other logos, and I found similar looking logos for mtl_red and mtl_blue, but the only alternates I found for mtl_video and mtl_demo did not match the same style:
>   ![image](https://private-user-images.githubusercontent.com/176075580/364424994-c312def4-c07d-4abc-b6c0-603d173a775d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3ODQxMzEsIm5iZiI6MTcyNjc4MzgzMSwicGF0aCI6Ii8xNzYwNzU1ODAvMzY0NDI0OTk0LWMzMTJkZWY0LWMwN2QtNGFiYy1iNmMwLTYwM2QxNzNhNzc1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOVQyMjEwMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xN2ZmZDM1OTYwMjc0NWM5Y2M4NjZjZWNmNjc2ZDhmZjUzMjNlZWVmOGI0MTQ1MTJkMTE0YWNlNTNjMzU2YmJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wWBGcpC5gagaQyYSVpoEfxDgQy3iBWfMP93FgZcYtcI)
> * In case it helps, the red text in this next photo is the old images/sources (what is currently on demo) and the green text is the images/sources for the above screenshot (my changes):
>   ![image](https://private-user-images.githubusercontent.com/176075580/364427134-ceabf1b7-ad76-429b-934e-b8dd1ea0196e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3ODQxMzEsIm5iZiI6MTcyNjc4MzgzMSwicGF0aCI6Ii8xNzYwNzU1ODAvMzY0NDI3MTM0LWNlYWJmMWI3LWFkNzYtNDI5Yi05MzRlLWI4ZGQxZWEwMTk2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOVQyMjEwMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjYwNGI5ZDA5OGNiNDFjYjNkODQzMGYwMzAyZmM0NmNkOTg4NjZiMzc2NDJmM2RkNGY0MmNmZGI3MmNlOGVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Jz8RVaBMob4Jj4EQbSr83DWxN_ZY-yGCbOx9tXQ0U8Y)

**Comment by tejaspesquare** [comment]
Hello @ljmoody,

> @matthewtomo, I'm unable to edit this text directly from the Admin Dashboard. Is this something you or the Dev team could implement? 

We have updated text as per above note. 
![image](https://github.com/user-attachments/assets/5ad7f26a-c1c9-464a-a833-e25ce55e97ca)

**Comment by matthewtomo** [comment]
**Discussed Monday Dev Standup wk_4 2024_09**
@matthewtomo @tejaspesquare 

- [ ] @matthewtomo still owes some work from the above comment: https://github.com/lzim/teampsd/issues/3158#issuecomment-2363616410

> **Discussed Friday Dev Standup wk_3 2024_09**
> @matthewtomo @tejaspesquare 
> 
> - PROD environment of Demo site is currently using older UI.
> - TEST environment of Demo site is currently up to date with Dev environment of Demo site.
> - [ ] @matthewtomo will sync up with @ljmoody and/or @lijenn to verify that the behavior and appearance of the TEST environment for the Demo site.
> - [ ] Once behavior and appearance is confirmed, we will promote changes in TEST to PROD for the Demo site and deploy those changes into PROD.
> - [ ] @matthewtomo still needs to Verify SDM docs for the demo sites are all up to date.

**Comment by matthewtomo** [comment]
**Discussed Friday Dev Standup wk_4 2024_09**
@matthewtomo @tejaspesquare 

- Demo site now is up to date feature-wise with Demo-test, but we encountered a bug during our trial this morning
- [ ] @matthewtomo will document related bugs to the Demo site in new cards later today.

fyi: @ljmoody

**Comment by lzim** [comment]
**DECISION:**
Do not let the Quick Start Video Block the DEMO Release. 
@lzim moved #3258 to 2025_01 for the #nih_2025_grant submission wk4

**Comment by ljmoody** [comment]
@matthewtomo - Selena created new logos for the demo site and they're located in [this Praxis shared folder](https://takouba.sharepoint.com/:f:/s/TeamPraxis/EswGU147ZXZFvO0lDfWcjeABicd-rHtli__Nn4HT2RRyHw?e=w5DRGl).

When you're able, will you please update the TEST Demo site with these logos and LMK when that's done so I can reveal to @lzim and get her eyes on it for approval?

In the meantime, I'll work on making the other updates.

**Comment by tejaspesquare** [comment]
Hello @ljmoody , @matthewtomo,
 
> * [ ]  Is it possible to have TEST Demo = PROD Demo? I'd like to make any remaining changes in TEST for Lindsey's approval (versus making changes directly to PROD).
> * [ ]  When you're able, will you please update the TEST Demo site (the ones hard-coded into the html) with these logos and LMK when that's done so I can reveal to Lindsey and get her eyes on it for approval?

Code migration is completed from DEV to PROD environment.

**Comment by lzim** [comment]
Whew!!! 😅 This is going to be just in time for our big talks in San Francisco next week! 
Way to go @tejaspesquare & @matthewtomo and @ljmoody

**Comment by ljmoody** [comment]
@lzim, I'd like to review in either wk2 2024_10 #support_workflow or #sim_ui_workflow. Feedback is needed today so I can implement changes today/tomorrow.

**Comment by lzim** [comment]
wk2 2024_10 
@ljmoody 

**EDIT TEXT:** "...consults with Team PSD."

![image](https://github.com/user-attachments/assets/46857826-a1a4-4896-ba99-732e144074fb)

**Comment by lzim** [comment]
**For the IIR Grant number:**
- [ ] Change HSRD to HSR
- [ ] Find a higher res logo of the VHA ORD logo
![image](https://github.com/user-attachments/assets/1793626d-6942-44ec-82b5-18c2bd8f111e)

**Comment by ljmoody** [comment]
**Discussed at wk2 2024_10 #sim_ui_workflow**
@matthewtomo @ljmoody @lzim @jamesmrollins 

**Revisions needed:**
- [ ] 
![image](https://github.com/user-attachments/assets/fefbdde5-ee35-46ca-9117-39c5cc340f60)
- [ ] Remove CAMHD logo
- [ ] VA Health Systems Research: 
  - logo will be identified by Lzim - 
  - copy wording from NIH; update with SAMSHA H795M082961
- [ ] edit HSRD to HSR (see above) in intro paragraph
- [ ] use HSRD logo at bottom (Funding logos)

**Comment by ljmoody** [comment]
@matthewtomo,
Demo site TEST instance is nearly ready to go. I need your help with these two tasks, then this card can be closed:
- [ ] Switch the Run logo with the mtl_demo icon, ensure they both link appropriately (see comment above)
  - I found a Run icon in the teampsd repo, but it was larger and rounded corners. I'm hoping you can get the square Run icon from behind the scenes and add it. 
- [ ] Promote TEST to PROD

**Comment by ljmoody** [comment]
PROD instance of mtl.how/demo is updated with all changes on this card.

Closing as complete. 
fyi @lzim

**Comment by lzim** [comment]
@matthewtomo 
@ljmoody 

### Three questions

1. As an Admin use, _How can I log in to mtl.how/demo?_ I tried, but it just takes me to my Admin Dashboard. 
2. _Does Demo have Flows in it?_

**Comment by lzim** [comment]
Hi @ljmoody 

I might not have been clear enough in my first post:
- I can get to MTL demo admin in the way you've highlighted above. But clicking the Demo icon does not take me to the MTL demo itself.
- I didn't mean the Flows .gif (no problem on that BTW), I meant the Flows that are releasing to PROD by Friday.
- I want to announce that feature accurately during the talk tomorrow.

**Comment by ljmoody** [comment]
@lzim,
A-ha! I read "demo site" and thought you meant the mtl.how/demo page. You were referencing the actual demonstration site, sounds like. 
- One can access it by going to mtl.how/demo_login; _however_,
- @matthewtomo - I just tried to access the demo site, and when I selected team_mtl_demo-sep-2024, the dropdown refreshed to "Please select a World". Seems to be a recursive loop. 
![image](https://github.com/user-attachments/assets/188b5de5-706f-4d80-8120-538e171bd61c)
- Because of the above issue, I'm unable to log in to see if flows are there. @matthewtomo, could you please respond to Lindsey about that? I tried both a hard reload and empty cache & hard reload. Here's a snapshot of the inspect console:
![image](https://github.com/user-attachments/assets/8f9ea986-19ab-4c07-a644-67824f5dbe98)

**Comment by tejaspesquare** [comment]
Hello @ljmoody,

> * @matthewtomo - I just tried to access the demo site, and when I selected team_mtl_demo-sep-2024, the dropdown refreshed to "Please select a World". Seems to be a recursive loop.

Wanted to highlight behavior of this functionality:
1.To gain access to the demo site, it is essential to register as an end user. You will receive a notification regarding this process.
![image](https://github.com/user-attachments/assets/2d6e511c-6deb-4007-b4ff-a8b42e7ef8e5)
2. It does restrict user if logged in as a facilitator.
3. End users remain active until completion of 15 days including date of registration.

**Comment by matomasz** [comment]
> Hi @ljmoody
> 
> I might not have been clear enough in my first post:
> 
> * I can get to MTL demo admin in the way you've highlighted above. But clicking the Demo icon does not take me to the MTL demo itself.
> * I didn't mean the Flows .gif (no problem on that BTW), I meant the Flows that are releasing to PROD by Friday.
> * I want to announce that feature accurately during the talk tomorrow.

@lzim, currently the flow diagrams are not available on the Demo site. Currently only

**Comment by matthewtomo** [comment]
**Discussed Friday Dev Standup wk3 2024_10**
@matthewtomo @tejaspesquare 

- Getting Flow Diagrams integrated into the Demo Site would take an estimated 30 hours of Dev time

fyi: @jamesmrollins
