### ISSUE TITLE
2024_07: White glove Test the Sim UI interface

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#3165]
## Context

- Sim UI is updated in Test Slow and declared "ready" by DEV team.

## Acceptance Criteria

- [x] System Stories (Causal Loop Diagrams) are screen resolution issues resolved.
- [x] Decision Meters retain values after window close.
- [ ] Directives Table up to date. This AC is transferred to #3184 
- [x] Team dropdowns working properly
- [x] MTL Reports Icon hidden
- [ ] SME setup functionality (7/1). This AC is transferred to #3182 and #3152
- [ ] Directives Dashboard and functionality (6/21). This AC is transferred to #3184.
- [x] Dynamic Dashboard alignment issues resolved

## Notes
- Supported Screen Sizes for responsive sizing: 
3200,2560,1920,1800,1780,1700,1600,1560,1400,1360,1280,1200,1180,1100,1024

**Comment by tejaspesquare** [comment]
@jamesmrollins - This is resolved & available to test on Dev environment.

**Comment by jamesmrollins** [comment]
@tejaspesquare - the above was not migrated to Test environment:

![image](https://github.com/lzim/teampsd/assets/30132017/0b173a1a-3e2e-40e5-ba44-92b015a770da)

**Comment by jamesmrollins** [comment]
@tejaspesquare 

## MM Model Calling Variables that do not exist in the model.  

![image](https://github.com/lzim/teampsd/assets/30132017/18ead1c0-ca5a-4cee-99dd-939a629ed0bf)

## MM_PROD.ctx Context File needs to be updated

![image](https://github.com/lzim/teampsd/assets/30132017/2f9a59dd-f020-4768-99ec-9bfe216b5814)

**Comment by jamesmrollins** [comment]
@tejaspesquare 

## Psychotherapy Causal Loop Diagram opens incorrectly

- The lower sizing icon is hidden below browser window, so user cannot grab it.
- Text is too small.
- Display size 1920 X 1080

![image](https://github.com/lzim/teampsd/assets/30132017/0e2db6df-f182-467f-8a72-8e272edf2956)

## Expand viewable area of Team Care Story

![image](https://github.com/lzim/teampsd/assets/30132017/754c6d3a-c75b-4e71-b54c-78e0fcf8196b)

## Increase font size and improve text centering (see highlights) in Team Flow Story

![image](https://github.com/lzim/teampsd/assets/30132017/b2378ec5-c026-4ec5-b960-452853ef63ec)

## @lijenn @ljmoody do these dropdowns need to be relabeled "Causal Stories" or "Stories?"

![image](https://github.com/lzim/teampsd/assets/30132017/7f96df7f-9404-458c-b259-600060ddf2e8)

**Comment by lzim** [comment]
**wk5 2024_05 #systems_sme_workflow**
@lzim
@dlkibbe

@jamesmrollins - Unclear about the only 2 of 8 requirements tested. Some seem to say 05/31. 
Our understanding was that we would have the _**MTL 3.7 Blue Live Consults**_ ready to set up this week for scheduling. 
Please advise on timeline to completion.

FYI: @dlounsbu

**Comment by jamesmrollins** [comment]
@lzim 

- White Glove Testing scheduled today.  I am slowing working my way through (started it yesterday, actually).
- 5/31 dates for Directives dashboard maintenance panel and SME maintenance feature. (this should not affect blue team setup)
- Once complete, Directives Dashboard complete, we can populate with content.
- Regarding the "Feedback Loops" label in the dropdown above, do you want that renamed "Stories" or "Causal Stories" or something else?

**Comment by lzim** [comment]
@jamesmrollins - Unfortunately, I'm understanding this response re: _**_MTL Blue 3.7 Live Consult_**_ prep planned for this week. _Are you saying we will not be done with testing until end of week?_ 

Please keep all of **#systems_sme_worklow** in the loop. 

FYI: @dlkibbe @dlounsbu

**Comment by jamesmrollins** [comment]
FYI:
@lijenn @ljmoody @dlkibbe @dlounsbu @lzim 

## Regarding Testing

- [ ] We have some set up we have to perform by-hand once PROD is brought fully to 3.7.  This includes the creation of group folders for all team data files, and moving legacy team data to the folders. **This will not affect any work setting up new groups.**
- [ ] We are attempting to clear remaining bugs so we can start that work tomorrow (5/28) in prod.  We will also start updating the consult manual.

**Comment by jamesmrollins** [comment]
@tejaspesquare 

## Please modify the following popup as shown.

- [ ] Extend popup size at the bottom to include the lower part of the Month 4, 5 and 6 tables in Medication Management.
- [ ] Make the table floating.

![image](https://github.com/lzim/teampsd/assets/30132017/caff942d-48c8-4554-8117-08ae089b717e)

**Comment by tejaspesquare** [comment]
Hello @jamesmrollins - 
Episodes of Care -Extend popup size:  This is resolved & available to test on Test-Slow. 

![image](https://github.com/lzim/teampsd/assets/144898781/27207eae-ea34-4abd-952a-af5a35ce6bfa)

**Comment by ljmoody** [comment]
@jamesmrollins, just saw your comment today re:

> ## @lijenn @ljmoody do these dropdowns need to be relabeled "Causal Stories" or "Stories?"
> 
> ![image](https://github.com/lzim/teampsd/assets/30132017/7f96df7f-9404-458c-b259-600060ddf2e8)

To my knowledge, no, these do not need to be renamed. **However**, I've seen/heard the following different references for same, and wondered if there are correct/incorrect ways in which we refer to them. We may need clarification from @lzim if there is one (or more) specific ways for she'd like to refer to them via Sim UI drop-downs, documentation, blue bar headings, etc.

Here's a list of possibilities - I've bolded the ones that are currently used in Sim UI menus, blue bar headings, and Consult Manual documentation:
- [ ] **causal loops**
- [ ] **feedback loops**
- [ ] causal loop diagrams
- [ ] system stories
- [ ] causal stories
- [ ] stories

fyi @lijenn

**Comment by lzim** [comment]
@ljmoody - I believe we have used "feedback stories" and "systems stories" and "causal feedback."
Let's leave this standardization card as lower priority until we are sure _MTL 3.7 Blue_ consults are prepared in PROD without issues.

**Comment by jamesmrollins** [comment]
@lzim @lijenn @ljmoody 

I am closing this card as remaining issues related to Directives and System SME setup is being tracked in separate cards.
