### ISSUE TITLE
2025_early 3rd roadmap: create Admin Dashboard Cheatsheet for Sim UI Admin Users

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3297]
Possible need identified in 10/10/2024 #sim_ui_workflow meeting.
Once consults with MTL Blue teams have happened, this need may rise based on Admin user feedback and/or pain points.

## Items to include on cheatsheet:
- [ ] TBD
- [ ] check with Lindsey: this[ list of how to prep for consults](https://github.com/lzim/research/issues/605#issuecomment-2470651982)? (or, in the _MTL_ Manual?)

## AC:
- [ ] create "mtl_how_3.7_sim_ui_admin_cheatsheet" document
- [ ] Cheatsheet .pdf uploaded to mtl>gh-pages>images
- [ ] Cheatsheet .png uploaded to mtl>gh-pages>images
- [ ] Cheatsheet link added to manual sections
  - [ ] 3.1 Cheatsheets
  - [ ] 3.3 Administrator Technical Manual
  - [ ] 3.3.2 Sim UI Administrator Dashboard

**Comment by ljmoody** [comment]
Adjusted card point value to zero. Closing this card as not planned.
