### ISSUE TITLE
Facilitate Workgroup Tasks

### ISSUE THREAD

**Issue by branscombj** [lzim/teampsd#352]
**Tasks for the Facilitate work group**

@lzim @dlkibbe @staceypark 
- Finalize the inter-session checklist
- Make sure the pre-post checklists are complete and clear – including what’s needed from the Fidelity Checklist/systems thinking skills (CFBT)
- Proof-read all the I information
- Map VAPOR videos to pre-post emails
- Start the MTLFacilitate accreditation brochure
- Review all the Say and See files
     - Make sure they have the most updated language and model version information
     - Make sure Say files don’t have team-specific content (like, “Our team is worried that we’ll lose a provider…”)
     - Put time stamps or estimates in
     - Make sure Say and See files match each other
     - Make sure Done and Do in the See and Say are correct and are aligned with the Pre-Post emails
     - Check gifs, identify ones that need to be remade, develop index

**Comment by lzim** [comment]
**Tasks for the Facilitate work group**

 @branscombj @dlkibbe @staceypark

**Turning this into a checklist for finalizing.**

_Are we ready in Lucid for the first item **"finalize the inter-session checklist"** with the TAS tomorrow?_

- [ ]  * Finalize the inter-session checklist
- [ ] * Make sure the pre-post checklists are complete and clear – including what’s needed from the Fidelity Checklist/systems thinking skills (CFBT)
- [ ] * Proof-read all the I information
- [ ] * Map VAPOR videos to pre-post emails
- [ ] * Start the MTLFacilitate accreditation brochure
- [ ] * Review all the Say and See files
   
- [ ] * Make sure they have the most updated language and model version information
- [ ] * Make sure Say files don’t have team-specific content (like, “Our team is worried that we’ll lose a provider…”)
- [ ]  * Put time stamps or estimates in
- [ ]  * Make sure Say and See files match each other
- [ ] * Make sure Done and Do in the See and Say are correct and are aligned with the Pre-Post emails
- [ ]  * Check gifs, identify ones that need to be remade, develop index

**Comment by branscombj** [comment]
> High-level 2 hours of organizing what you can do to prepare for MTL co-facilitation. 

@lzim The "[course guidance](https://github.com/lzim/teampsd/blob/master/mtl_facilitate_workgroup/facilitation_guide/manual_courseguidance.md)" I started a skeleton for back in the day might help with this task. It's not an exact 1:1 match; but it is a high-level overview that I think could help facilitators-in-training keep track of aspects of *MTL*.

I also started an explanation of the platform and terminology around the sim UI [here](https://github.com/lzim/teampsd/blob/master/mtl_facilitate_workgroup/facilitation_guide/manual_usingsimui.md).  ... and other reference documentation like list of acronyms (we have now elsewhere) and acknowledgements.

**Comment by lzim** [comment]
Thanks @staceypark 

See the links in @branscombj's post above. It may go with the overview and even the meta cheatsheet or facilitator cheatsheet.

**Comment by branscombj** [comment]
Check off each session that has been reviewed per the above steps:
- [ ] 1 
 - [ ] 2 
 - [ ] 3 (steps 2,4,5)
 - [ ] 4 
 - [ ] 5 CC
 - [ ] 5 MM
 - [ ] 5 PSY
 - [ ] 5 AGG
 - [ ] 5 SP
 - [ ] 6 CC
 - [ ] 6 MM
 - [ ] 6 PSY
 - [ ] 6 AGG
 - [ ] 6 SP
 - [ ] 7 CC
 - [ ] 7 MM
 - [ ] 7 PSY
 - [ ] 7 AGG
 - [ ] 7 SP
 - [ ] 8 CC
 - [ ] 8 MM
 - [ ] 8 PSY
 - [ ] 8 AGG
 - [ ] 8 SP
 - [ ] 9 CC
 - [ ] 9 MM
 - [ ] 9 PSY
 - [ ] 9 AGG
 - [ ] 9 SP
 - [ ] 10 CC
 - [ ] 10 MM
 - [ ] 10 PSY
 - [ ] 10 AGG
 - [ ] 10 SP
 - [ ] 11 
 - [ ] 12

**Comment by staceypark** [comment]
@branscombj @dlkibbe @lzim One more thing I would add to the list of comb-over items is to make sure that it is specifically clarified which actions should be done in the "ind" world and which in the "team" world in the done/do for the emails and session guides.

i.e. when team starts building out the qhfd and writing them up on their own, they will need to be accessing both to refer back to the text created in-session (team world) and write up their own (ind world)

**Comment by branscombj** [comment]
> @branscombj @dlkibbe @lzim One more thing I would add to the list of comb-over items is to make sure that it is specifically clarified which actions should be done in the "ind" world and which in the "team" world in the done/do for the emails and session guides.
> 
> i.e. when team starts building out the qhfd and writing them up on their own, they will need to be accessing both to refer back to the text created in-session (team world) and write up their own (ind world)

Thanks @staceypark ! I added it to our checklist above.

**Comment by lzim** [comment]
@dlkibbe @branscombj @staceypark @TomRust 

Can we divvy this up, and align with the TAS training schedule as we complete our GANTTs this week?

**Comment by branscombj** [comment]
> @dlkibbe @branscombj @staceypark @TomRust
> 
> Can we divvy this up, and align with the TAS training schedule as we complete our GANTTs this week?

Yes, I will try to do that.

**Comment by branscombj** [comment]
@lzim @staceypark There was a time a few wks ago, I thought, when we imported all the latest SEE files from mtl.how to the TeamPSD repo, meaning to move the whole batch of SAY and SEE files back to the public-facing location when finalized. I want to be sure that we (including @dlkibbe @TomRust @dlounsbu ) haven't been making revisions to those files in different places.

**Comment by lzim** [comment]
@branscombj @dlkibbe @TomRust @dlounsbu @staceypark 

Great question! **_And, VERY important clarification._** SEE is at mtl.how here https://github.com/lzim/mtl, SAY is at TeamPSD here: https://github.com/lzim/teampsd

# SEE - pull requests to [mtl.how](https://github.com/lzim/mtl)
For minor changes to SEE files they need to be **pull requests** to the Master branch of [mtl.how](https://githu.com/lzim/mtl) that Stacey and I approve.

- We also do want to keep an **archive of all the SEE and SAY files at different milestones (e.g., R21 vs. R01; MTL 1.7 vs. MTL 1.8).** In other words set them aside, so that we know what we working with at that point, not just have a record a edits that can be walked back.  
- @staceypark Were we able to recapture this at all?  Or had we just edited the old versions and lost the prior ones?  Moving forward we'll want records archived of what we actually were doing when.

# SAY - pull requests to [TeamPSD](https://github.com/lzim/teampsd)

**Comment by branscombj** [comment]
@lzim @dlounsbu What would you think about removing time stamps from the Learner See guides? @TomRust and @dlkibbe and I talked about it yesterday. In my facilitation, I typically prefer that participants not be watching the clock or second-guessing whether we're "on time", especially since I may be intentionally adjusting on the fly to accommodate the group's need.

**Comment by lzim** [comment]
FYI: @dlounsbu @TomRust @dlkibbe @staceypark 

Good question: Thanks for documenting this conversation here @branscombj ! 📋  

> What would you think about removing time stamps from the Learner See guides? 

1. **GitHub Dialogue is key to our shared understanding and our Level 2 Resources:**
- Tracking any conversations like this is critical, because we want to move toward a **shared understanding of _how_ to facilitate the _MTL_ Theory of Change** now that our larger research trials are funded.
- As we work to improve our Team PSD time management, we will use **our three shared facilitate_workgroup meetings** as _working meetings_ to avoid unnecessary _unlearning_ and/or rework.
- Even as it extends our timeline to launch, developing "Level 2" resources for facilitators, cannot be done by Team PSD members unless their framing of the **participatory learning** and **systems thinking** goals and emphases across the 12-session plan is rock solid.
- Now, as we scale, it is preferable to devote our time to **mutual learning with the OMHSP TAS during the progressive** #manuscriptmondays, Wednesday intersession preparation and Friday demonstration lessons.
- And, 😄 everything we document in terms of this rationale can go in the facilitator SEE guide  📖 

2. **This learner SEE guide change concerns me in ways that will be helpful to link to our larger focus and priorities now.**
- We need to highlight these  dimensions 💎 now as we transition away from our several years of learner-focused development, to really **training _MTL_ Facilitators (you!) to deliver the developed program with fidelity to the _MTL_ Theory of Change, _as part of a research trial._**

3. **We developed the learner SEE guides in their current form with lots of iterative participatory learning with stakeholders.** 🌀 
- We learned to add the timestamps after our **4 years of participatory, iterative development.**
- Our learners are **mental health providers who are very practiced watching the clock.** 
- Depending their specialty, they are seeing new patients **every 30 minutes or every 50 minutes,** given what they've told us about their **stress of "limited time**," we have learned to expect that showing them the time will help them to do _two very important things_: 
a. **Reduce their anxiety** about whether we're doing a good job covering what we are supposed to be covering. Sticking to **_within session_ time** will show we are competent facilitators worthy of them sharing team meeting time, knowing that we will end on time for them to see their patients. 
b.  With the **team format,** if we provide timestamps (i.e., a clear agenda), it is also more likely that these practiced time managers will **moderate their in-session time** more effectively all by themselves.

4. **_Modeling to Learn_ is developed, now facilitator training is underway.**
-  **The time for focusing on changes to the learner SEE (level 1) documentation is over.**
-  These SEE guides that have largely been stable through several rounds of iterative testing from the R21 teams (May 2015-Sept 2018), to the MTL Facilitate Pilot (Sept 2018), to the MTL Video Shoot (Nov 2018), through MTL Facilitate Training - Learner Mode (Mar-Apr 2019). 
- Now we have to **test the federally peer-reviewed program that we developed, as it was reviewed and funded.** 💵 
- We can safely transition away from developing the learner materials, and **transition to practicing being _MTL_ Facilitators.**

5. **Research shows that supervised practice is key to fidelity**
- Research shows that **fidelity is key to achieving desired outcomes.**
- So, **we have to learn to avoid adjusting "on the fly," in terms of time management.**
- Given how hard tailoring to a local team, while painting fidelity, within the existing team meeting really is, we need to **prioritize** and **practice** using the **intersession checklist timestamp scripts** for our teams. 

6. **We need to make sure variation in our R01/IIR trial outcomes is NOT due to variation in our facilitators**
- We aren't launching a national quality improvement program, **we're doing a randomized, multi-site implementation science trial.** 
- This means we aim to create **generalizable knowledge** about what works for whom, under what conditions, and _why_.
- Therefore, we need to work very, very hard to do everything in our power to ensure that **variability in our outcomes is NOT due to variability in facilitator fidelity to the _MTL_ Theory of Change** that we are testing across the arms of these trials (i.e., lack of facilitator competence).

**Summary**
1. Training ourselves as _MTL_ Facilitators up to **fidelity** is the key the **critical path to our R01/IIR launch.** 🚀 
2. We **cannot launch** until we are _all_ competent maintaining fidelity across all modules and across the 12-session plan. 📆 
3. We will work hard on this **across sessions and modules at the F2F,** so that we can begin training the TAS. 💻 
3. Our highest priority need now as _MTL_ Facilitators is supervised practice triaging our **4 priority** questions to make sure that we **practice** to get those done within the time-frame. 🕙

**Comment by branscombj** [comment]
@lzim @TomRust @dlkibbe @staceypark @dlounsbu 
In order to carve out 7-8 days for dedicated MTL travel and work, I will be focused on my non-VA projects until Thursday. I've changed my RSVP to today's meeting, but in the past that hasn't made it to folks' radar so just letting you know here. I know Debbie and I got some of the aligning See-Say files done over the weekend. I'll continue to work on getting that task completed (despite what I just said:).

**Comment by lzim** [comment]
Thanks @branscombj

I saw your “no” rsvp. Thanks!
It does help to see it in advance!

We are giving folks the time back to work (on Team PSD or other work), but I will make myself available at 11AM Pacific on #manuscriptmondays Lucid meeting to answer any questions folks may have in advantage of the f2f 

Thanks!
FYI: @staceypark @tomrust @dlkibbe and @dlounsbu

**Comment by branscombj** [comment]
> @branscombj @dlkibbe @TomRust @dlounsbu @staceypark
> 
> > # SEE - pull requests to [mtl.how](https://github.com/lzim/mtl)
> > For minor changes to SEE files they need to be **pull requests** to the Master branch of [mtl.how](https://githu.com/lzim/mtl) that Stacey and I approve.
> 
> I've tried to do edits twice to mtl.how and did a pull request to create branch and it says I do not have permission to create a branch. So I'm focusing on the say edits only.

@staceypark @jessfroe @lzim  **Could you let us know our process for this please.**

**Comment by lzim** [comment]
So, @branscombj @staceypark @jessfroe @dlkibbe @TomRust @dlounsbu 

It looks like #352 is the meta-issue on these tasks that we've now divvied up into the **document_tracker.** 

I expect we may be able to close this issue, unless, there is anything on this list that has not be captured in our new workflow.

I still see that we need to clarify at least 3 things at the **workgroup leads** meeting and in the **tracker/workflow SOP.**

1) How to use the **checklist** in the **document_tracker** to provide a standard review.
- Items should be checked off when they are a) updated, or b) reviewed to ensure that they don't need updating.

2) We also need to make sure everyone knows how to add to or edit **dependent issue cards** to make sure they've been cross-checked.
- For example, she issues need to tracked by point persons in the list for **describe, detail, and document**.

3) Last, we need to **clarify how/when issues should be closed** when there are dependencies. 
- For example, since you can always check a closed issue. I believe it does make sense to close issues, when the work reflected in that card is done. But, _only when the dependencies have been tracked across other cards._

**Comment by branscombj** [comment]
**Data UI/Splash page nomeclature follow-up** (copied from 10/25/19 Lucid) @lzim @staceypark @dlkibbe @holbrooa 

Where I was headed when I brought this up on Monday was not so much whether we should use the term "splash page", but how we define - and whether it even matters to be precise - the Data UI. Is it everything starting from mtl.how/data; or only the Excel file from which you select clinics, review data and vizzes, and calculate parameters for the Sim UI?

My impression from observing our fearless leaders is that technically, mtl.how/data takes you to the Splash Page for the Data UI and the actual Data UI is the Excel file - AND, that it isn't really a problem if you call all of it the Data UI, as long as you can be clear when you're on the Splash Page and are seeing only Facility-level data vs. when you're in the Data UI and looking at team-specific, individual-level data and sim parameters. The first part of my Monday question was trying to discern whether our Splash Page is something VA clinicians already know and call by that name (i.e., not unique to MTL).
