### ISSUE TITLE
Test Issue for TeamPSD Issues Tracker Policy

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#443]
**ORIGINATOR**
*Please follow the steps below to open an issue for the MTL Workgroups to address. Be sure to provide a descriptive title for the issue when saving.*

**Step 1** - Please assign this issue to the issue_tracker, under the “Projects” menu on the right side of your GitHub page.

**Step 2** - Please answer the questions below by checking the appropriate boxes and providing brief narratives where appropriate:

1. Is this issue a problem, such as a malfunction in the simulation, an error in documentation or similar concern, or is this a new idea
   we should consider?
   
   - [x] Problem *(continue to number 2 below)*
   - [ ] New idea *(continue to number 7 below)*

2. What team are you on (exg., Menlo Park, Team Blue)?
Workgroup Leads

3. How urgent is this problem?

   - [x] Urgent - *should be fixed right away!*
   - [ ] Non-urgent - *can be prioritized within normal workstreams.*

4. In the space provided below, please describe the behavior you expected from the simulation or otherwise describe what you expected to see or hear. 

I expected the check-boxes to work better than they are. The tables and all other interactive elements of this form totally suck in this format. Need helpful ideas!!

I would have like to see check boxes that behave like check boxes, versus having to place an "x" between the brackets.

5. Please provide a screenshot of the bug, if possible.  Make as many screenshots as you like that would be helpful to illustrate the  issue.

   *<< Paste screenshots here>>*
![image](https://user-images.githubusercontent.com/30132017/60388897-153ddf80-9a6d-11e9-995b-c583815058ab.png)

6.  Within which product did you notice the problem? *Check all that apply*

   - [x] SharePoint
   - [x] Data/Queries
   - [x] Team Data
   - [x] R-reports
   - [ ] See Guide
   - [ ] Say Guide
   - [ ] Videos
   - [ ] Post tests
   - [ ] Fidelity Checklist
   - [ ] Other?  Please describe here >>
   
   Care Coordination Simulation
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
   Medication Management
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
   Psychotherapy
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
   Aggregate 
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
   Suicide Prevention
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
  
7. What kind of device are you using?
   - [ ] Tablet
   - [ ] Smartphone
   - [ ] PC

8. What browser were you using?
   - [ ] Chrome  *What version?*
   - [ ] Edge    *What version?*
   - [ ] Safari  *What version?*

9. Please describe your idea below.  Feel free to provide a scan or screen capture of a sketch of your idea.

10. Why is this idea important, in terms of your work?

11. How is this idea related to a problem you face in your daily practice?

12. Is there a deadline or other scheduled constraint driving your request that we should be aware of? *This will help us to prioritize
    this request.*

     **THANK YOU!!**

---------------------------------------------------------------------------------------------------------------------------------------
**STOP HERE. INFORMATION BELOW IS TO BE FILLED OUT BY WORKGROUPS AS PART OF TRIAGE AND WORK BREAKDOWN PROCESS**
---------------------------------------------------------------------------------------------------------------------------------------

**Executive Summary**

*Estimated person-hours to complete:*  10 hrs.

*Estimated date for completion:*  Aug 9, 2019

*Lead team for effort:* Quantitative

*Key people (use @ assignment for people whose input will be necessary):*
@jamesmrollins 

**Step 1 - Complete the Interdependencies Table**

Workgroup Leads review information provided by originator and collaborate to identify interdependencies. Then they describe modifications that are needed in the appropriate column and estimate hours needed to make changes:
 
● *Workgroup Products* - This column identifies the workgroups and the products for which they are responsible. This column can be
  modified by a workgroup lead on an ad-hoc basis to add one-time products or can be modified to include new and enduring products.
  
● *Dependency?* - This column is used by the workgroup leads during collaboration to identify the existence of an interdependency.

● *Description of Change or Action Needed* - Workgroup leads briefly describe the change required.

● *Hours* - Workgroup leads estimate the person-hours required to complete the task.

Workgroup Products        | Dependency?  | Description of Change Needed               |  Hours Estimate
------------------------- | -------------|--------------------------------------------|-----------------
**Documentation**            
Brochures                 |              |                                            |
MTL See Guide             |              |                                            |
MTL Say Guide             |              |                                            |
MTL Videos                |              |                                            |
Post Test                 |              |                                            |
**Investigators**         |              |                                            |
Presentation              |              |                                            |
Quarterly Report          |              |                                            |
Annual Report             |              |                                            |
**Qualitative**           |              |                                            |
MTL Fidelity Checklists   |              |                                            |
Systems Thinking Codebook |              |                                            |
CFIR Codebooks            |              |                                            | 
**Quantitative**          |              |                                            |
Data UI                   |              |                                            |
Data Queries              |     Y         |                                            |
SharePoint                |         Y     |                                            |
Excel Outputs             |         Y     |  Needs a revised query                       |  10 hrs.
ModelParameters           |              |                                            |
tt Reports                |              |                                            |
**Model**
CC                        |              |                                            |
MM                        |              |                                            |
PSY                       |              |                                            |
AGG                       |              |                                            |
SP                        |              |                                            |
**Sim User Interface**    |              |                                            |
Model Diagram             |              |                                            |
"i"Information            |              |                                            |
Experiments               |              |                                            |
Outputs/Charts            |              |                                            |
Exports                   |              |                                            |
Master Crosswalk Table    |              |                                            |

**Step 2 - Identify Constraints that may affect the team’s ability to complete the necessary actions.** 

Describe the constraint in terms of capability, capacity or affect on grant research goals. If there are no constraints identified, then leave the table blank.

●  Type - The type of constraint identifies one or more resource areas that are affected.  

●  Workgroup - this is the workgroup responsible for developing a new or modifying an existing product.

●  Discussion/recommendation - A brief narrative that expands the information regardingthe constraint and ideally a recommendation for
   overcoming the constraint.

**Type Constraint (check all that apply) / Workgroup(s) Affected / Discussion/Recommendation**

- [x] Capacity / Quantitative / Need to re-prioritize in order to state the expected due date 
- [ ] Cost         
- [ ] Schedule     
- [ ] Interference 
- [ ] Capability   
- [ ] Other (describe)

**Step 3 - Identify supported milestones.** *Affix the milestone at the issue level using available GitHub milestones.*

**Step 4 - Indicate the due date for completing the actions identified above, assuming constraints are removed.**
Aug 5, 2019

**Step 5 - Identify the lead workgroup for the action (check one):**

- [ ] Documentation
- [ ] Investigators
- [x] Quantitative
- [ ] Qualitative
- [ ] Model
- [ ] Sim UI

**Step 6 - Go to the top of this section and complete Executive Summary information**
