### ISSUE TITLE
s01_detail - DUE 10/4

### ISSUE THREAD

**Issue by jessfroe** [lzim/teampsd#522]
# s01 CHECKLIST

## 1. Link to the document, add relevant team members to the card, and add workflow decisions.
- [x] Add the link the current draft of the documentation for the issue #959 

## 2. Link to issues that must be edited in the document in the **issue_tracker** and **feature_tracker.** _(use the # for the link to the issue)_
- [x] Issue #490  - Spell out name of SP module
- [x] Issue #577 - I think this has some info to attend to in sessions 5-7.
- [x] Issue #830 - Red and Blue Icons & Links; "Episode of Care" units for SP.

## 3. Team Review
- [x] Fidelity - check with Lindsey
- [x] Data UI - check quant_workgroup
- [x] Sim UI - check with model_workgroup and/or sim_workgroup

## 4. Review and Open Pull Requests _(use the # for the link to the pull request)_
- [x] Check the draft for typos
- [x] Check or open a pull request for the document edits

## 5. Review and/or Update Graphics
- [x] Screenshots
- [x] Gifs
- [ ] Logos/Icons - DO WE WANT TO USE AN **MTL BLUE** logo instead of **MTL LIVE** in these guides?
- [ ] Links - I think this is handled with #954 

## 6. Dependencies
- [x] Make sure that any edits you make that need to be added to **depend_product** are tracked (e.g., _MTL Video_)**

## 7. Close Pull Requests
- [x] Request review and/or close open pull requests for the document
