### ISSUE TITLE
meta_document

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#602]
# Meta Document Checklist

## 1. Link to the document, add relevant team members to the card, and add workflow decisions.
- [ ] Add the link the current draft of the documentation for the issue
1. Need to create documentation on VA Skype use for non-VA TeamPSD facilitators #489 
- [ ] Add all related workflow decisions here:
1. 
2.
3. 

## 2. Link to issues that must be edited in the document in the **issue_tracker** and **feature_tracker.** _(use the # for the link to the issue)_
- [ ] Issue #451 
- [ ] Issue #410  
- [ ] Issue #490  
- [ ] Issue #588, #397 @staceypark facilitate cheatsheet
- [ ] Issue #563 @staceypark update OSF cheatsheet to include instructions on 2+ source citations citekey format
- [ ] #663 MTL Demo cheatsheet
- [ ] Issue #620 - update cheatsheets on uploading photo to SIM
- [ ] update pre/post emails with VAPOR videos
- [ ] create second set of pre/post emails for comparator arm 
- [ ] done/do update for comparator arm
- [ ] #756 - details on being "facilitator" or not for attendance count in the sim and how attendance statistics work along with other stats in the epicenter dashboard

## 3. Team Review
- [ ] Fidelity - check with Lindsey
- [ ] Data UI - check quant_workgroup
- [ ] Sim UI - check with model_workgroup and/or sim_workgroup

## 4. Review and Open Pull Requests _(use the # for the link to the pull request)_
- [ ] Check the draft for typos
- [ ] Check or open a pull request for the document edits

## 5. Review and/or Update Graphics
- [ ] Screenshots
- [ ] Gifs
- [ ] Logos/Icons
- [ ] Links

## 6. Dependencies
- [ ] Make sure that any edits you make that need to be added to **depend_product** are tracked (e.g., _MTL Video_)

## 7. Close Pull Requests
- [ ] Request review and/or close open pull requests for the document

**Comment by lzim** [comment]
Please cross-ref issue #600 **meta_describe** and populate the combined schedule in each column.
It will be easier across the team to keep track of all the relevant weekly documentation deadlines across columns/point persons according to the Master training schedule. Thanks!

**Comment by staceypark** [comment]
**Documentation Schedule**

|   Date   |  Co-Facilitator Training | Describe/Detail/Document | Depend | Disseminate 
| - | - | - | - | - |
| 9/6 | Systems Stories | S07, S05 | S06, S05 (as many as possible) | DART Mod
| 9/13 | No Facilitate Meetings | S08, S04 | S07, rest of S05 | IIR IRB
| 9/20 | s07 | S09, S03| S08, S04 | IIR JIT
| 9/27 | s08 | S10, S02 | S09, S03 | R01 CT
| 10/4 | s09 | S11, S01 | S10, S02 | IIR ART
| 10/11 | s10 | S12 | S11, S01 | -
| 10/18 | s11 & s12 | - | S12 | -
