### ISSUE TITLE
meta_depend

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#604]
# Meta Depend Checklist

## 1. Link to the document, add relevant team members to the card, and add workflow decisions.
- [ ] Add the link the current draft of the documentation for the issue
- [ ] Add all related workflow decisions here:
1. 
2.
3. 

## 2. Link to issues that must be edited in the document in the **issue_tracker** and **feature_tracker.** _(use the # for the link to the issue)_
- [ ] Issue #451 - for PSY only. _This change resulted in a different layout and labels for the Team Data Table (RVI medians for patients in care > 3 months using 25th, 50th, 75th percentiles for each Low, Medium, and High engagement duration group._ 
- [ ] Issue #410 see also Issue #339 These are about the new Participatory Learning & Design feature. A new icon will appear on the sim UI Home page and a bouncing arrow will call attention to it when there are items open for user voting.
- [ ] Issue #446 
- [ ] Issue #490  
- [ ] Issue #638 for PSY only
- [ ] Issue #704 for SP only
- [ ] Issue #726 for SP only
- [ ] Issue #727 for SP only
- [ ] Issue #739 SP only

## 3. Team Review
- [ ] Fidelity - check with Lindsey
- [ ] Data UI - check quant_workgroup
- [ ] Sim UI - check with model_workgroup and/or sim_workgroup

## 4. Review and Open Pull Requests _(use the # for the link to the pull request)_
- [ ] Check the draft for typos
- [ ] Check or open a pull request for the document edits

## 5. Review and/or Update Graphics
- [ ] Screenshots
- [ ] Gifs
- [ ] Logos/Icons
- [ ] Links

## 6. Dependencies
- [ ] Make sure that any edits you make that need to be added to **depend_product** are tracked (e.g., _MTL Video_)

## 7. Close Pull Requests
- [ ] Request review and/or close open pull requests for the document

**Comment by jessfroe** [comment]
**Video Review Schedule**

|   Date   |  Videos   |
| - | - |
| 9/6 | S06, S05 (as many as possible)
| 9/13 | S07, rest of S05 
| 9/20 | S08, S04
| 9/27 | S09, S03
| 10/4 | S10, S02
| 10/11 | S11, S01
| 10/18 | S12

**Comment by lzim** [comment]
@jessfroe and @staceypark

Please cross-ref issue #600 **meta_describe** and populate the combined schedule in each column.

It will be easier across the team to keep track of all the relevant weekly documentation deadlines across columns/point persons according to the Master training schedule. Thanks!

**Comment by staceypark** [comment]
@branscombj @dlkibbe #638 I'ved added the PSY "i" information issue to this card. We may need some recheck on PSY specific videos.

**Comment by staceypark** [comment]
@jessfroe I know you're working on compiling the video edits to send to Ann. Just wanted to give you a heads up that @TomRust is also doing video review, specific to model related content for major changes to logic & structure. 

He will be adding these notes to the relevant session cards so be on the lookout for that.

**Comment by lzim** [comment]
> @jessfroe I know you're working on compiling the video edits to send to Ann. Just wanted to give you a heads up that @TomRust is also doing video review, specific to model related content for major changes to logic & structure.
> 
> He will be adding these notes to the relevant session cards so be on the lookout for that.

Right, @TomRust and I are using the experiment series from the videos in our manuscripts, which is what prompted this.

It is the risk of sending an **Excel** file to Ann, which is why we usually try to avoid that sort of thing, as versions get out of sync very quickly 🙁

**Comment by staceypark** [comment]
@branscombj @dlkibbe 
We are behind on the video review by two weeks as of now. Since Jane will be back next week, I think you guys will be able to catch up faster:

- 9/20 Session 04 & 08
- 9/27 Session 03 & 09

**Comment by staceypark** [comment]
@branscombj @dlkibbe I've added an additional issue for SP only (Issue #726) that may need video check for previous sessions

**Comment by dlkibbe** [comment]
Missed this message when I reviewed the rest of the SP video last night. @jessfroe may want to consider editing if necessary. I can't get to this until Thursday.

**Comment by staceypark** [comment]
@branscombj @dlkibbe Can we get a update on where folks are on the video review?
This week's videos include Session 10 & 2, as well as we need to catch up on the ones below.

> @branscombj @dlkibbe
> We are behind on the video review by two weeks as of now. Since Jane will be back next week, I think you guys will be able to catch up faster:
> 
> * 9/20 Session 04 & 08
> * 9/27 Session 03 & 09

**Comment by staceypark** [comment]
@branscombj @dlkibbe We just sent the first batch of video edits (s5-s7) to Ann.
Thank you for all your hard work on these. And please let me know where we are on the review schedule as we are behind.

Also, please make sure that you are:
1. double checking all the dependencies when providing edits (i.e. I noticed that the SP edits had "for" instead of "and" in the full name - Measurement Based Stepped Care *and* Suicide Prevention)
2. edits are consistent across the same module (i.e. I only saw in one session the edit to change the banner for "Suicide Prevention" to the full name, so I went ahead and added it to the other sessions as well).
3. double checking for typos in *your* edits

**Comment by staceypark** [comment]
@branscombj @dlkibbe We are a fair bit behind on the video review schedule that we outlined. @dlkibbe I saw the edits come through for Session 08 which is great! Could you both provide an update on the plan for getting the rest of these videos reviewed? Let us know if you need help or need to re-sketch the timeline

**Comment by dlkibbe** [comment]
@staceypark - just entered session 9 video reviews. Will work on 10 over the weekend and 11 next week.

**Comment by lzim** [comment]
Hi @branscombj and @dlkibbe 

AMAZING WORK on [**document_tracker**](https://mtl.how/documents) 🔥 
 
@jessfroe alerted me to the fact that we nearly 1 monthly late on finalizing our **depend_products** video review for Ann at EES (schedule above, with target to wrap by 10/16). EES really needs us to wrap-up as there is so much more to do: a) apply the edits, b) close caption, c) 508 compliance, d) pilot for accreditation, etc.

How can HQ help to get this done? It looks like there are only 5 videos left to review, AMAZING!
Is there any chance we can get this done by COB Friday for Ann?
- [ ] s01 #557
- [ ] s02 #556
- [ ] s03 #555 
- [ ] s11 #548 
- [ ] s12 #547 

Thanks!

FYI: @staceypark and @ritahitching

**Comment by dlkibbe** [comment]
Never mind @jessfroe (grin) -- I'll work on this over the weekend.

**Comment by jessfroe** [comment]
@dlkibbe Thank you so much! We are so close to finishing video review! 
🥇
