### ISSUE TITLE
Week of 9/3 #hqhuddle

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#613]
#hqhuddle 

- [x] 1. Update GH dependency check label definitions #478 
- [x] 2. welcome & orient Rita to the team 
- [x] 3. orient team to changes in SOP including new meta column cards: #600 #601 #602 #603 #604 
- [x] 4. PCSPDB due today #599 
- [x] 5. Prep for MTL Facilitate this week
- [ ] Resolve Issue #401 of error with zeroes in Params file
- [x] #483 VA REDCap
- [x] #480 team tracker

**Comment by lzim** [comment]
@staceypark @jessfroe

Do each of you have a specific list of training items for Rita today?

- Stacey, you’ll sit out on Qual today. Does it make sense for Rita to train on basics w/you during Qual? 
- Or, should she join Qual and get her bearings with Jessilyn?

**Comment by staceypark** [comment]
@lzim @jessfroe
I think makes more sense for her to sit out of qual with me and I can orient her to our platforms, mapping, etc

**Comment by staceypark** [comment]
@ritahitching

**Comment by staceypark** [comment]
@ritahitching and I covered the following

1. mtl.how
2. mtl.how/team
3. mtl.how/demo
4. mtl.how/facilitate - Epicenter account created and added to TeamPSD projects
5. mtl.how/sim - Error in adding new users (see Issue #616 )
6. mtl.how/lucid - Account created under PAVIR email address
7. mtl.how/live
8. mtl.how/osf - Account created under PAVIR email address & added to SOP project
9. mtl.how/refs - Account created under PAVIR email address
10. mtl.how/teampsd - Account created under PAVIR email address, @lzim please add @ritahitching to the repository, oriented to resources > cheatsheet folder

**Comment by jessfroe** [comment]
@staceypark @lzim @ritahitching

I am getting ready to leave so I wanted to give an update on where I was able to get to in my work today:
1. Updated documentation schedule table for the describe (#600), detail (#601), and depend (#604) column
2. Began working on the fidelity rating operational definitions on #614 

I still need feedback on the team_tracker_template before I am able to populate the team_tracker with the checklist. Lindsey, whenever you have time to do that (hopefully before COB Thursday?) I'd appreciate it. That way, I can populate the tracker before our Friday meeting. 

During intersession prep tomorrow, if time allows I believe further clarification and specificity regarding the fidelity ratings would be much appreciated. Multiple facilitators in Team 2 mentioned their confusion about the function of these questions, and expressed a need for clairity in order to correctly use the ratings during MTL live co-f practice. 

**Reminder:  I am on CWC/STAIR tomorrow all day.**

**Comment by staceypark** [comment]
@lzim on issue #401 - what is the cofacilitation plan tomorrow esp given Jane’s email?

If we are still walking through systems stories, we won’t be able to 0 proof the models by tomorrow but I checked the team4 data file this morning against all modules and it doesn’t throw the same 0 error that the team2 file did. So we could use that.

**Comment by lzim** [comment]
@staceypark

Right, I just posted the same about using Team 4 on issue #401. Although, I also do hope @tomrust can weigh in on this.

- Also, @tomrust did you make progress with the s06 SAY guides, which you were editing to further flesh out systems stories.

**Comment by lzim** [comment]
@staceypark and @jessfroe

- Jessilyn is out today (for Team PSD) today
- Stacey will you populate my edited Master Documentation schedule Issue #600 across the **document_tracker** columns please? 
- Stacey, **for this morning’s training,** I also need a table of exactly who has 
1. Attended each _MTL Facilitate_ training session.
2. Co-Facilitated each session (i.e., the pairs, the session, the team).
3. Make sure all the training videos are posted in 000, and give me a list of who is recorded and note if there are any issues with the recordings (e.g., no sound).
4. Check with Tom about his work on the systems stories. 
5. Include a link to s06 _MTL Video_ for each **module** in the Lucid Meeting.

> I still need feedback on the team_tracker_template before I am able to populate the team_tracker with the checklist. Lindsey, whenever you have time to do that (hopefully before COB Thursday?) I'd appreciate it. That way, I can populate the tracker before our Friday meeting.

- I will work in this. However, we may need to slow down and do less on Friday. We may only want to focus on **fidelity** using RedCap 

> During intersession prep tomorrow, if time allows I believe further clarification and specificity regarding the fidelity ratings would be much appreciated. Multiple facilitators in Team 2 mentioned their confusion about the function of these questions, and expressed a need for clairity in order to correctly use the ratings during MTL live co-f practice.

**Comment by staceypark** [comment]
@lzim
@tomrust said yesterday the model won’t be ready by today because they need to test and validate.

Ok I’ll populate the schedule and get a table put togethet

**Comment by lzim** [comment]
@staceypark

- I think maybe an #hqhuddle for the week, that we work with throughout each day may make the most sense, because not all items across the team are resolved within the day.
- Thanks re: Table - Can you turn the table creation into a “teachable moment” for orienting Rita to Lucid this AM?
- what did you train her in yesterday, please include the HQ training updates in the #hqhuddle issue thread 
- we want to be much more structured than we were with Jessilyn
- Please have her create a GitHub account and I will add her to TeamPSD so she is included in these #hqhuddles

FYI: @jessfroe

**Comment by staceypark** [comment]
@lzim Check the fourth comment from the top. I can add more detail to that if that's what you mean?

**Comment by jessfroe** [comment]
@lzim thanks for getting back to me re: team_tracker. I can focus on orienting the team to the REDCap project this week, then. Ignore my other comment on my pull request! I didn't sort through my notifications effectively enough this AM 🙈

**Comment by jessfroe** [comment]
Also - are we using the same GitHub thread for one week? Or, starting a new thread each day? Or, never starting a new thread?

**Comment by staceypark** [comment]
@jessfroe I think we're finding it makes more sense to do 1 per week

**Comment by jessfroe** [comment]
@staceypark that makes perfect sense. Petition to say "week of" in the title?
@lzim @ritahitching

**Comment by staceypark** [comment]
- [ ] Need to create a poll for TIDIRH for LZ & JD Smith

**Comment by lzim** [comment]
@jessfroe 

We realized at today's meeting that we need to put the correct (most up-to-date) video links in the **depend_products** column. Will you please put the correct link in each issue card please?

- [ ] Link the most current video links in each session card for the **depend_products** column.

Thanks!

**Comment by staceypark** [comment]
- [ ] @staceypark schedule manuscript planning meeting with @lzim

**Comment by lzim** [comment]
@ritahitching @jessfroe 

-[ ] Please add images to Gravatar so that you have images on GitHub, etc.
-[ ] Please also add yourselves and your images to https://mtl.how/team

I will take a photo of you, if you need one that works on the site 📸

**Comment by lzim** [comment]
@jessfroe 
 **#fidelityfridays & team_tracker (this week):** 
- [ ] _updated fidelity training checklist_: get the question items with their associated operational definitions together. 
- [ ] ask you to turn SAY guides into “1-pager” or “overview checklists” the way that I did with you and Tom last week, **starting with s07**. 
- [ ]  key part of the team_tracker. Let’s talk about this tomorrow.

@lzim 
- [ ] edit the link to be **mtl.how/documents** so that all trackers are plural (keep the names singular, however, e.g., **team_tracker**

**Comment by lzim** [comment]
Welcome to GitHub @ritahitching 🥳

I re-opened the “Week of 9/3 #hqhuddle” issue until we get through the end of the week. 😄 

FYI: @staceypark and @jessfroe

**Comment by lzim** [comment]
@staceypark I believe @ritahitching needs help with how to open a pull request for her bio

- [ ] GH pull requests

**Comment by lzim** [comment]
@staceypark @jessfroe @ritahitching

FYI HQ:

From yesterday’s Intersession Prep:

- [ ] Need to put the training schedule prominently in the **team_tracker**

- [ ] Need to link issue #303 in the top of each _MTL Facilitate_ Training

- [ ] Re-name the 3 weekly Facilitate Sessions (M/W/F) according to what will be covered that week (s07: _Modeling to Learn_ base case)

- [ ] Cancel next week’s meetings, BUT...

- [ ] 1. First, back-up the video session from yesterday in 000 and link directly to it in the cancellation message

- [ ] 2. Second, put the updated video links in the **depend_products** column. 

- [ ] 2. Third, be sure to say in the email: “THIS IS A ONE-TIME CANCELLATION due to many team members being out for travel this week. 

Thanks! 🤓

**Comment by staceypark** [comment]
@jessfroe @ritahitching
We’ve learned that the adobe connect videos can’t be backed overnight since the system reboots sometimes and can’t be backed while we use adobe connect.

Let’s make sure we all use our machines today during the day to back up the missing ones to make sure we have all of them.

**Comment by staceypark** [comment]
@ritahitching and I went through how to Invite folks on Lucid as a "Series Attendee" and she added herself to all of the meetings as practice (except MTL Facilitate 3 meetings which @jessfroe will do and we already discussed).

@lzim @jessfroe @ritahitching 
I noticed that our adobe connect videos are named a little differently each time making it terribly confusing to pinpoint a specific session's video.

**I propose we rename them to be: year_month_day_session#_teamname or 2019_09_05_s05_team4**. 

This will let make them autosort from most recent to oldest when it sorts by name and help us keep track of which teams have recorded which sessions.

**Comment by staceypark** [comment]
@ritahitching @jessfroe and I are all backing up different Adobe Connect meetings.
@jessfroe - Wed 9/4 prep session
@ritahitching - Fri 8/30 demo session
@staceypark - Wed 8/28 prep session

**Comment by jessfroe** [comment]
@lzim I did not see the bullet point re: linking the videos directly in the cancellation. Could I instead link the videos to the follow-up from tomorrow's #fidelityfriday?

**Comment by jessfroe** [comment]
@staceypark I agree we need a hashtag and have been trying to think of good "w" words to do so...we work every day so I'm not sure if we want to do working? Its going to be tough to come up with something for that one! Especially one that is related to what we do on Wednesdays.

**Comment by staceypark** [comment]
😄 true we definitely do work everyday! work-in-progress wednesdays? ugh but that's so long

**Comment by staceypark** [comment]
- [ ] Need to cancel 9/24 co-I meeting as Craig is giving the D&T Director Job Talk & reschedule to Tues 10/1 @jessfroe can you do this

**Comment by ritahitching** [comment]
Lindsey and I came up with the suggestion of **WikiWednesday** or **WorkboxWednesday** - thoughts @lzim @jessfroe @staceypark

**Comment by staceypark** [comment]
Please update the staff tree with your information. Refer to the email for the actual link.
- [ ] @jessfroe  Add information to NCPTSD Staff tree
- [ ] @ritahitching   Add information to NCPTSD Staff tree

**Comment by jessfroe** [comment]
@ritahitching @staceypark @lzim 
Hmm I'm just not totally partial to the Wednesday hashtags currently. Also, neither of those options seem to address what we are actually doing that day. 
Why does it have to be on the W day! 😭

**Comment by jessfroe** [comment]
Also, can I just say...it is SO satisfying to click on these little check boxes when I am finished with a task!! Very reinforcing 🤣

**Comment by staceypark** [comment]
@jessfroe @lzim  for the REDCap fidelity tracker, what granularity do we need when they are submitting their fidelity ratings? Specifically, do different team ratings need to be separated like in the MTL menu when viewing results immediately after submitting? I can talk about it more at the HQ meeting @1pm.

**Comment by staceypark** [comment]
- [ ] track all of the serial numbers for new monitors and give list to NCPTSD admin (Mary & Doug) as well for move upstairs

**Comment by jessfroe** [comment]
@staceypark not sure, that would probably be a call you need to make

**Comment by staceypark** [comment]
- [ ] pull requests with Rita for updating mtl.how 1.8 models and bio

**Comment by staceypark** [comment]
- [ ] mtl.how/demo links: mtl live & mtl video intro update links

**Comment by jessfroe** [comment]
@lzim @staceypark @ritahitching 
Alright HQ, I'm off for the day. Here are my needs during the huddle - 
- [ ] Lindsey provide feedback on the new REDCap branching logic and questions so that I can finish the fidelity ratings ASAP in the morning - Stacey can you link this? I can't find it and I have to go. 

- [ ] Lindsey review pull request for the fidelity rating checklist - https://github.com/lzim/teampsd/pull/631

**Comment by staceypark** [comment]
- [ ] add document tracker link and instructions to top of issue #294 to give clarity

**Comment by ritahitching** [comment]
### Adobe Recordings List
#### List of recordings from Lucid Meeting

Adobe | Sound  |  Backed Up
------------- | -------------|  -------------| 
s06_interssion_prep  | Yes |
s06_demo_08_30_2019 | Yes |
s06_intersession_prep | Yes |
manuscript_monday_group_supervision_s06_systems_story | Yes | Yes |
s05_demo | No |
2019_08_21_team2_intersession_prep | No |
s05_group_supervision_manuscript_mondays | Yes |
s4_team4_2019_08_16 | Yes | Yes
2019_08_14_s3_s4_team4 | No |
s4_team2_2019_08_09 | Yes | No video & No Sound
s4 | Yes | Yes
s4_manuscriptmondays | Yes | Yes  | Yes
s3_team4_intersession_prep_2019_07_31 | No |
s3_team4_live_cofacilitation_2019_08_02 | No | Yes 
s3_manuscript_monday_2019_07_29 | No | Yes
team2_s2_2019_07_19 | No | Yes
s2_2019_07_17 | Yes | Yes 
s2_sp_gap_threshold | Yes | Yes
s2_intersession_prep | Yes | Yes
mtl_facilitator_orientation_2019_07_10 | Yes | Yes

**Comment by lzim** [comment]
@jessfroe @staceypark @ritahitching 

Hurray! 

- [x] [mtl.how/fidelity](https:mtl.how/fidelity) is live 🎆 
- [ ] Need to remove the "Dr." from the _MTL Facilitator_ list and just alphabetize by first name.
- [ ] Need to populate team 2 and 4 through the RedCap Survey

thanks!

**Comment by lzim** [comment]
HQ

We want to send the 000 video for Wed 09/05/2019 Intersession Prep in the Lucid Follow-up Email ASAP this morning.

Lindsey

**Comment by lzim** [comment]
> @jessfroe @staceypark @ritahitching
> 
> Hurray!
> 
> * [x]  [mtl.how/fidelity](https:mtl.how/fidelity) is live 🎆
> * [ ]  Need to remove the "Dr." from the _MTL Facilitator_ list and just alphabetize by first name.
> * [ ]  Need to populate team 2 and 4 through the RedCap Survey
> 
> thanks!

Hey @jessfroe I noted your pull request #631 - Let’s make sure we’re clear about the distinctions for s11 and s12 within the APPLY phase (s9-12) _**BEFORE**_ you populate further.

Let’s touch base first thing 🌅

**Comment by lzim** [comment]
## #hqhuddle for Friday AM

@jessfroe 
> - [ ] Lindsey review pull request for the fidelity rating checklist - #631 - See my comments about this. Let’s review this together _**BEFORE**_ you populate RedCap
> - [ ] ask you to turn SAY guides into “1-pager” or “overview checklists” the way that I did with you and Tom last week, starting with s07.
- Let’s turn to this tomorrow after #fidelityfridays tomorrow I will help with the **s07_checklist** and the **team_tracker**

@staceypark 
> - [ ] track all of the serial numbers for new monitors and give list to NCPTSD admin (Mary & Doug) as well for move upstairs
- NOTE: I need to send the serial #s to PAVIR, and we should track any equipment that Team PSD uses that we may worry the movers may skip. 
- We may need to spend an hour on Friday afternoons scanning/shredding and getting ready for the move.

**ALL**:
> We want to send the 000 video for Wed 09/05/2019 Intersession Prep in the Lucid Follow-up Email ASAP FRIDAY MORNING

**Comment by lzim** [comment]
P.S....

LOVING the #fidelityfriday agenda in Lucid great work HQ 🚀

**Comment by jessfroe** [comment]
@lzim I can send out the recording this morning when I get in. Should I clarify the meaningful work the facilitators should be doing during that time? 

Also, now that we discussed emails, would you like me to revisit the grant meeting reschedule?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lzim** [comment]
FYI HQ: @branscombj asked some great questions on pull request: **Update mtl_session07_see.md #635**

Need to cover a few of them today re: .gifs.

**Comment by lzim** [comment]
> @lzim I can send out the recording this morning when I get in. Should I clarify the meaningful work the facilitators should be doing during that time?
> 
> Also, now that we discussed emails, would you like me to revisit the grant meeting reschedule?

Morning @jessfroe 🐔 (meant to be a rooster)
- The message (and formatting) of the email you send this morning should be: 

“As we discussed on Wednesday during this intersession prep meeting, today we will divvy up to practice telling causal systems stories. The details are in the record below. 

Also, we spent a fair bit of time on Wednesday focusing on _MTL resources_ principles for co-facilitators, our schedule and next steps, and the research on importance of **psychological safety** for achieving organizational improvement using system dynamics. Several in attendance recommended that this was a _valuable video to watch_ Please check it out here: [insert the complete link, so that they can just click right on it and go to the video; I’ve omitted it on GH, because we do not post secure paths here]”

- Grant meeting schedule: Let’s clarify with Savet and Andrew what we will cover at the 10/4 meeting first. Then, yes, let’s circulate an invite to the 10/4 meeting.

**Comment by lzim** [comment]
@staceypark cross-ref PR #636 

I need your help on how to handle edits/PR across TeamPSD and MTL.
I’m not current on what was decided and how it works and cannot advise.

Can we please document this for the team, so that everyone is clear.
It may be something that goes in Team PSD > Resources > GitHub guide (re: Pull Requests)?

**Comment by lzim** [comment]
All **HQ** @staceypark @jessfroe @ritahitching 

- Need to clarify across **document_tracker** that if there are .gifs needed they need to be tracked in the **document_tracker** **session cards** under checklist item 5. 

- Jane created several in PR, but that will hide them from other documenters across the **document_tracker** 

- We need those .gif needs to be added to the session card as a **checklist item**

**Comment by jessfroe** [comment]
🌞 
> “As we discussed on Wednesday during this intersession prep meeting, today we will divvy up to practice telling causal systems stories. The details are in the record below.
> 
> Also, we spent a fair bit of time on Wednesday focusing on _MTL resources_ principles for co-facilitators, our schedule and next steps, and the research on importance of **psychological safety** for achieving organizational improvement using system dynamics. Several in attendance recommended that this was a _valuable video to watch_ Please check it out here: **[insert the complete link, so that they can just click right on it and go to the video; I’ve omitted it on GH, because we do not post secure paths here]”**
> 
- Just so I'm *crystal* clear, when you say complete link, are you referencing the pathway to the 000 folder in Team PSD? Or, is there another place we are saving them? 

> * Grant meeting schedule: Let’s clarify with Savet and Andrew what we will cover at the 10/4 meeting first. Then, yes, let’s circulate an invite to the 10/4 meeting.

 - Got it, thanks! Should I reach out to them, or will you discuss the 10/4 meeting with them and relay the information to me?

**Comment by lzim** [comment]
@jessfroe

For the link, you are right re: 000 just want to make sure it has the full path not d:/ or something unique to your own server mapping.
-  If you’re still unsure, I’m trying to wrap up a call now and should be in my office in just a few minutes.

Let’s talk about the rescheduled meeting on the Monday A.M. work or leads meeting next week.
Since the email already went out, there is no need to rush this now, it can wait until next week.

**Comment by lzim** [comment]
**HQ**

- tt_teampsd: Our celebration should be the completion of the MTL 1.8 release milestone.
- We also need to start to circulate details about the Team PSD fall party. We will likely want to send out a separate invitation, but also may want a Calendar icon or some other way to denote upcoming events in the team.

**Comment by lzim** [comment]
**HQ:**

- [ ] Reschedule VAPOR for 9/24 separate from the Grants/Co-I meeting.

**Comment by staceypark** [comment]
Adobe Connect recording naming convention:
2 digit session number_teamname_topic (mm, w, ff)_date 

i.e. s06_t2_mm_2019_09_06

**Comment by staceypark** [comment]
- [ ] 8/30 adobe connect session needs to be backed up

**Comment by staceypark** [comment]
- [ ] could we add the video links to the team_tracker as well?

**Comment by ritahitching** [comment]
@ritahitching
- [ ] label inside and outside of the box (number and serial number) and take a photo - 16 monitors - create a spreadsheet.
- [ ] document ports for monitors - touch screen - requires a USB and video chord - check HTMI and SVGA 
- [ ] test all monitors with commensurate stations of mtl team
- [ ] use stations that are mapped consult with @staceypark

**Comment by staceypark** [comment]
gifs for next week
- [ ] update guides and update the cards as an example
- [ ] give example of how to do it, and try to do a gif (with new monitors) based on Jane's comments
- [ ] then train orient

hq training
- [ ] train @jessfroe & @ritahitching on OSF file check in/check out
- [ ] @jessfroe add hq manual to OSF 
- [ ] @ritahitching add/update training needs in the manual

**Comment by staceypark** [comment]
- [ ] 9/6 mtl facilitate f/u email w/ @ritahitching including the video link and reminder that next week meetings are cancelled
