### ISSUE TITLE
9/16/2019 Adding Rita Hitching, Jessilyn Froelich, & Ren Kramer headshots to team mtl.how website

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#669]
**1. Add description:** 

Add Rita Hithcing Bio to mtl.how website
<< Paste screenshots here>>
 
**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_

**Edit the due date (if necessary)**

**Comment by lzim** [comment]
Hi @jamesmrollins and @staceypark 

- Unfortuately, it looks like the issues I reviewed with @ritahitching yesterday were not addressed in the training yesterday.
- Over the last two weeks, I have repeatedly conveyed to @staceypark that e really need to NOT wait for training if the issues are public-facing. Training can occur separately later, with fixes implemented now.
- However, I was assured that these would be fixed during the training yesterday.

Specifically, 

**Use the Text from **TEAM**, which is Out-of-Date on **DEMO**
- [ ] 1. Fix the flowing semi-colon (it is fixed below) and add the HSRD grant (no hyper-link yet)
- [ ] 2. Add hyper-link for PI: "[Zimmerman](https://www.lindseyzimmerman.com)"
TEXT: "Funded by the National Institutes of Health and the Veterans Health Administration, scientific study of Modeling to Learn is underway to determine its effectiveness increasing delivery of evidence-based addiction and mental health care (NIDA R01DA046651 and R21DA042198; HSRD I01HX002521; PI: Zimmerman). The Modeling to Learn program supports multidisciplinary teams of frontline psychiatry, psychology, social work, nursing and certified peer support specialist providers in the Veterans Health Administration. This website supports the Modeling to Learn effort by introducing the facilitators, workgroup leads, key partners and co-investigators who learn with frontline staff from MTL data and simulation resources. Our team, “Team PSD,” is distributed across the United States. Read below to learn more about who we are and what we do.

- [ ] 3. Remove Correy Matthews, as he is no longer on our EES projects and we do not have a photo.
- [ ] 4: Add a photo of Ren Kramer ASAP.

- [ ] 5. I requested text for the "What we Do" sections

- [ ] 6. Add @ritahitching and @jessfroe 

Thanks!

Lindsey

**Comment by lzim** [comment]
@ritahitching @staceypark @staceypark 

**Cross-ref #669: The US map on TeamPTSD home page - speed of slides**

**Comment by ritahitching** [comment]
@lzim and @staceypark 
- notes of #intersessionprep - S07: Modeling to Learn base case - updated.
- will commence adobe back up as soon as session ends.

**Comment by ritahitching** [comment]
@lzim and @staceypark leaving now for VA Palo Alto.

**Comment by staceypark** [comment]
@lzim
- The "Zimmerman" hyperlink is updated in Demo but not Team. There is a new feature on the dashboard that allows us to add the hyperlinks with a 6 link limit per section. This feature is already in PROD for Demo but for Team @jamesmrollins said it will be pushed to PROD tonight.

- I updated the team website to have descriptions for all the workgroups, but we will need logos from you.

- I pingged Ren for his photo & bio.

**Comment by staceypark** [comment]
@jamesmrollins Rita, Jessilyn, & Ren's headshots are here: https://github.com/lzim/teampsd/tree/master/resources/headshots

Could you add them to the website please?
I added in the bio for @jessfroe and the bio for Ren is coming soon... to a theater near you

**Comment by staceypark** [comment]
@jamesmrollins updates on the photos? Especially since we pointing a lot of folks to this site following conferences, we want to make sure everything is up to date on this.

@lzim Lara also doesn't have a bio. I can try pinging her again but I doubt we're going to be able to get a hold of her for that given how she's been super busy. I did find the below on the world wide web though that I propose we add in the meantime:  

"Lara Dolin is the VHA Employee Education System's (EES) subject matter expert for all Section 508 (accessibility) issues. Though she manages Section 508 contracts as a Contracting Officer's Technical Representative (COTR), she also completes accessibility remediation of the agency's electronic media and coordinate formal reviews with the VHA Section 508 Office. She solidly believes in the work she does, because she has been given the chance to see firsthand how her knowledge and work make it possible for people with disabilities to interact with the electronic media that is vital to VHA's daily operations."

**Comment by jamesmrollins** [comment]
@staceypark - I am sorry, this has been low on the priority list for me.  I will get it done no later than Tuesday.  I didn't realize that you had made a commitment to get it done by a specific date and we didn't discuss it in the Thursday meeting.  

@lzim  - this one is on me, @staceypark has been gently pushing me to get this done, I just haven't had a chance.  Will get it done by Tuesday and likely earlier.  Thanks, Jame

**Comment by jamesmrollins** [comment]
@staceypark @ritahitching @lzim OK, up to date with latest information. Need Ren's bio. ~ James

**Comment by staceypark** [comment]
@jamesmrollins @lzim Ren is up and we can wrap!

**Comment by staceypark** [comment]
@jamesmrollins 
The short description for the VAPOR (Veterans Advisory Partnership for Operations and Research) board is slightly wrong for every member:
- Tammy Thompson & Leroy Edwards are missing the word "Research"
- DC Barlow and Erik Ontiveros are missing the word "Research" and the "p" in "Partnership" should be capitalized
- Ren Kramer's description should say "Veterans Advisory Partnership for Operations and Research" instead of "Peer Support Specialist" and his location should be "Menlo Park" as well instead of "Palo Alto"

**Comment by jamesmrollins** [comment]
@staceypark ok.  I take it this is the Map?

**Comment by staceypark** [comment]
whoops sorry. yes this is for the floating heads on the map

**Comment by staceypark** [comment]
@jamesmrollins just checked and looks good now.
thanks
