### ISSUE TITLE
Week of 9/16 #hqhuddle

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#705]
cross-ref #642 
@lzim 

**mtl facilitate materials**
- [ ]  s05 - #497 - SAY: No input from Tom, yet - Need s05_checklist - LZ will produce
- [ ]   s06 - $518 - SAY: Tom added Systems Stories - LZ will add fidelity intro - have a s06_checklist (LZ will rename the file)
- [ ]   s07 - #517 - SAY: Tom was supposed to add BC details, but hasn’t yet - LZ will add _fidelity_intro - have a s07_checklist

**r01 & iir protocol review:**
- [ ] R01 https://osf.io/8pzxu/
- [ ] IIR https://osf.io/p7g8f/
- [ ] Review checklist of what we have/don't have for the CONSORT-CRT Extension CONSORT Wiki: https://osf.io/z7y8m/wiki/consort/

**Dexter w/teampsd**
- [ ] Dexter's Demo Account deleted [again] set him up with course code, or talk with @staceypark about pros of adding him to one of our MTL Facilitate training teams.
- [x] Course Code: SIRC2019
- [ ] Once Dexter creates a free GitHub log-in; add him as a Team PSD Contributer
- [ ]  Have Dexter sign the NCPTSD Research Scope of Practice
- [ ] Test Data UI permissions at next meeting

- [x] add stevelindley to teampsd

@staceypark 
- [x] update team tracker template
- [x] populate the team_tracker with the updated template
- [x] populate the two team cards with team specific information
- [x] update new mtl 1.8 models at mtl.how
- [x] show @ritahitching how to populate REDCap fidelity survey
- [x] finish populating fidelity survey
- [ ]  **On hold until we get through 1) this week’s documentation (Tom), and this week’s top data priorities (Andrew) - Need before launch, will not incorporate in training: Coordinate with @TomRust and @holbrooa** to test **Team 4** on **9/5 prototype Data UI: Use PC diagnoses from Jodie for SP instead of using stop codes #596
- [ ] email Steve/Doug about the space in the server link - @lzim are we asking them to change it? that would mean everyone on TeamPSD needs to re-map, not to mention the link will break for the whole center.

@ritahitching 
- [x] add updated decisions on workflow to team SOP in OSF
- [ ] update team website with photo and bio

@staceypark @ritahitching 
ro1 & iir protocols:
- [ ] R01 CT.Gov and ART registration Cross-ref #606 and #607
- [ ] r21_r01_iir_procedures https://osf.io/z7y8m/

**HQ** Training to update [mtl.how/team](https://mtl.how/team)
- [x] Slow the slide rate for maps
- [ ] Add Rita and Jessilyn as HQ members, take appropriate new photos (that fit the circle and Team “look & feel” if necessary 
- [ ] Get a photo from Ren
- [x] Remove Correy from EES

_Missing Workgroup Descriptions_
- [x] HQ
- [x] Model
- [x] Quant
- [x] Qual
- [x] Co-I 

@jessfroe 
- [ ] update team website and github with photo and bio

**Comment by lzim** [comment]
Thanks @staceypark!

For after **Workgroup Leads:** 

- [ ] Touch base re: EBP Reach w/**quant_workgroup**

- [ ] I’d like to make sure the pre/post emails are included in the **document_tracker** schedule. 

- [ ] **team_tracker** demo - s07 group supervision today

**Comment by lzim** [comment]
@ritahitching

Good morning:

- [ ] SIRC travel remitted to PAVIR

**Comment by staceypark** [comment]
@ritahitching 
- [ ] tt report

**Comment by ritahitching** [comment]
> @ritahitching
> Good morning:
> 
>  SIRC travel remitted to PAVIR
please send me the costs for SIRC travel to submit to PAVIR

**Comment by staceypark** [comment]
- [ ] f/u with rachel kimerling for TeamPSD GitHub

**Comment by lzim** [comment]
> @lzim
> please send me the costs for SIRC travel for me to submit to PAVIR

@ritahitching Thanks!
The receipts are in Team PSD in the pavir_expenses folder under SIRC > post_sirc
- Just need to fill out the form with the Lyft Rides and the daily per diem for 9/11-9/15, which is already available on Issue #354 
- Then send it to me for signature and assignment of the account.

@staceypark can you please show Rita how do do this?

Thanks!

**Comment by lzim** [comment]
#hq huddle mid-day:

- [ ] @staceypark add t02 and t04 s06 details to the **team_tracker**
- [ ] @staceypark inventory the open issues that would fall to Tom/**model_workgroup**
- [ ] @staceypark & @ritahitching work to clear Lindsey’s schedule to focus on SAY and manuscripts w/Tom through Monday 9/30

@lzim today: 
- [ ] coordinate with Tom on S07 SAY file for tomorrow’s #375 #intersessionprep 
- [ ] prep for meeting w/Joey re: budget

**Comment by staceypark** [comment]
Issues inventory related to Tom/**model_workgroup**
Manuscripts:
#696 r21_sp_nejm 
#690 r21_psy_jccp
#688 r21_mm_jama
#686 r21_mbc
#685 r21_iop
#680 r21_cc_jgim
#678 r21_agg_ha

Issues:
#648 SP: floors and episode counts
#596 9/5 prototype Data UI: Use PC diagnoses from Jodie for SP instead of using stop codes

SAY guides: #601 metal detail; #497, #512 - #522 (s1-12)

**Comment by ritahitching** [comment]
@LZ @staceypark 
### **One off Meetings and Occasional Recurring**

**Week commencing Sep 16**
1. **Tuesday 9/17/2019**
-  8:00am OHT Tom Russ
- 3:00pm PAVIR Budget

2. **Wednesday 9/18/2019**
- 12:00pm VINCI Happy Hour

3. **Friday 9/20/2019**
- 8:00am Hospital Home Proposal
 
**Week Commencing 9/23/2019**

1. **Monday 9/23/2019**
- 1:00pm Stanford Quality Council 

2. **Tuesday 9/24/2019**
- 12:00pm Implementation Science
- 12:00pm _Ci2I Mental Health (cancelled)_
- 2:00pm VAPOR Workgroup

3. **Wednesday 9/25/2019**
- 8:00am TIDHIR Small Group - Option 1
- 11:00am MHC Staff Meeting
- 12:00pm MBC 

4. **Thursday 9/26/2019***
- 9:30am JIT F/U on Progress
12:00pm TIDIRH Small Group Option 2
- 2:00pm TIDIRH Small Group Option 3


### **Regular Meetings**
1. **Mondays**
- 8:00am  Workgroup Leads 
- 9:00am Manuscript Monday
- 11:00 am Optimize Business Operations
- 12:00pm VISN MH Lead Conference
- 12:30pm HQ Huddle
- 1:00pm Manuscript Monday
- 4:00pm HQ Huddle

**Tuesdays**
- 8:00am Qualitative Coding
- 8:00am OHT Tom Ross
- 9:30am Implementation Research Group (cancelled 9/19))_
- 10:00am Manuscript Workgroup
- 11:00am NCPTSD (every 3 weeks)
- 11:00am All staff meeting
- 11:00am Psychotherapy Tool
- 12:00pm Stanford Residency
- 1:00pm TeamPSD Lunch
- 4:00pm HQ Huddle 

** Wednesdays
- 8:00am Implementation
- 9:30am MTL Intersession Prep
- 10:00am Implementation Research Group (monthly)
- 12:30pm HQ Huddle
- 1:00pm PBI (every 3 weeks cancelled)_
- 4:00pm HQ Huddle

**Thursdays**
- 8:00am Workgroup Leads
- 9:00am Research Time 
- 10:00am Quantitative Workgroup
- 11:00am NC PTSD Research Series
- 12:00pm Bites
- 12:00pm HQ Huddle
- 1:00pm HQ Workgroup
- 2:00pm Site Selection
- 4:00pm HQ Huddle 
- 4:00pm HQ Huddle

**Fridays**
- 9:00am MTL Live Co-Facilitate
- 12:30pm HQ Tasks
- 4:00pm HQ Huddle

**Comment by lzim** [comment]
**#hq end of day huddle**

@lzim 
- [ ] Download final IIR to Team PSD
- [ ] Add residents to mtl.how/data Residents folder

@ritahitching @staceypark 
- [ ] Work with Lucid to try to recoup the **Manuscript Meetings**

@staceypark 
- [ ] Update OSF Cheatsheet to inlude PC Instructions; how to fix citekeys that aren't using Team PSD format
- [ ] Reschedule Ella on JIT until 10/3
- [ ] Schedule Joann K for end of Oct

@ritahitching 
_**R01** First_ 
- [ ] Consort table in OSF for R01
- [ ] Consort table in OSF for IIR
- [ ] R01 CT.gov see if anything is missing
- [ ] Add BetterBibtex to your Zotero Desktop Application
- [ ] R01 Protocol on OSF add CiteKeys from p.196 of the file "ZIM.RESUB.R01.4.10.18.AppImageDraft.Final"
- [ ] TeamPSD Training Manual

_**IIR** Second_
- [ ] Double-check IIR IRB  
- [ ] ART > CT.gov for IIR
- [ ] Preparing the Union Notification Letter

- [ ] Update weekly meeting calendar for who from HQ at each meeting

**Comment by lzim** [comment]
For the Reference Table:


**R01** |   |   |  
-- | -- | -- | --
Reference Number | CiteKey | Full Reference
1 | [@elbogen2013are] | Elbogen EB, Wagner HR, Johnson   SC, et al. Are Iraq and Afghanistan veterans using mental health     services? New data from a national random-sample survey. Psychiatr Serv.   2013;64:134–141.
  |   |   |  
  |   |   |  
**IIR** |   |   |  
Reference Number | CiteKey | Full Reference

**Comment by ritahitching** [comment]
@ritahitching - needs manual entry for each calendar date - does not auto populate 

### add link of https://github.com/lzim/teampsd/issues/303

- [ ] Manuscript Monday

- [ ] Wednesday intersession pre

**Comment by staceypark** [comment]
@lzim we haven't sent any video comments to ann yet according @jessfroe because you were going to look over the edits in the depend_column and make a decision on what is the best way to send them?

**Comment by jessfroe** [comment]
> @lzim we haven't sent any video comments to ann yet according @jessfroe because you were going to look over the edits in the depend_column and make a decision on what is the best way to send them?

@lzim last I remember, we informed Debbie that they did not need to do anything else with their comments in the depend column b/c you were going to look over their proposed edits and determine how to inform Ann.

So sorry if I missed something! If we come up with a system on how to consistently communicate the edits, I'm happy to continue to run point on that and relay the edits to the vid team. 

Missing my HQ buds this week!!

**Comment by staceypark** [comment]
@ritahitching 
when @lzim  was asking you to write updates on #619 earlier, she didn't mean for you to provide general updates, but updates specifically on that issue topic.  We are tracking the lucid meeting issue on the HQ #705 thread and the Demo/Team page changes on #619, so we want updates for each in their respective places. We can talk more about this tomorrow and on the SOP for our issue workflow.

**Comment by staceypark** [comment]
@lzim I'm in ART! 🎆

**Comment by staceypark** [comment]
@lzim 
James and I agreed that we wouldn't need much time during the 8am meeting tomorrow for overall issues. We will use the time to finish up the training and resolving of issues regarding #619 .

Also, according to the VA REDcap website, they meet every Thursday from 3-4Pm EST for open Q&A. I was thinking it might be a good idea to resolve my REDCap issue there as I have not figured out what's causing the error?

**Comment by ritahitching** [comment]
> @ritahitching
> when @lzim was asking you to write updates on #619 earlier, she didn't mean for you to provide general updates, but updates specifically on that issue topic. We are tracking the lucid meeting issue on the HQ #705 thread and the Demo/Team page changes on #619, so we want updates for each in their respective places. I'm also noticing updates unrelated to the issue on #669
> 
> I'm happy to talk more about our SOP for the issue workflow and clear up any questions you may have.

@staceypark and @lzim Got it. I'll be mindful to keep our weekly HQ thread issues separate from the other individual issues we create.

**Comment by staceypark** [comment]
@lzim Tom is asking to clarify exactly when you guys will meet on Friday. Should I book out 11am-2pm (since it's the third Friday, the meeting is 9-11am instead of 9:30-11:30a)?

**Comment by ritahitching** [comment]
@lzim and @staceypark 
- notes of #intersessionprep - S07: Modeling to Learn base case - updated.

**Comment by lzim** [comment]
> @lzim Tom is asking to clarify exactly when you guys will meet on Friday. Should I book out 11am-2pm (since it's the third Friday, the meeting is 9-11am instead of 9:30-11:30a)?

@staceypark and @TomRust 
With our time difference, I can meet with Tom at 7AM if it would help him to more readily get started on anything (I have an 8AM, Tom). Or, if Tom already knows what he needs to work on today, we can also touch base after the session 7 demos.

- [ ] **I would really like to record video for Team 04/SP, if we can teach Tom how to do it.** We keep having me record, but it would be great to get the other team.

_Writing_
I accepted Tom’s s07 BC details (PR) into the **TeamPSD repo**, but think we should NOT add it to mtl.how yet, as we promised the ICs we would not do that anymore. Rather, the minimum documentation goal now is to get s08 to mtl.how by COB tomorrow. **_But, I welcome you getting through s08, s09, s10 today/tomorrow, if at all possible, Tom, AND/OR writing up the same examples for **module_manuscripts**
- [ ] CC @staceypark & @ritahitching the **manuscript_tracker** is missing **r21_cc_jgim** https://osf.io/c24xz/
- [ ] MM #688
- [ ] PSY #690 
- [ ] AGG #678 
- [ ] SP #696 

- How is @ritahitching doing with the R01 and IIR reference tables, will we have that done by COB today/tomorrow, so that Tom and I can work with them?

**Comment by ritahitching** [comment]
@lz @staceypark 
### **Update** regarding Lucid and deletion of meeting series: 
- Any meeting deleted on Lucid cannot be reinstated.
- May be possible to go into a data backup to get some information (like meeting records).
- Once the meeting series is recreated (by HQ) Lucid can help in retaining the same conference, in the event that this does not happen automatically.

I have some thoughts on a possible remediation to my unintentional error - perhaps we can discuss at the next #hqhuddle.  My appologies again, as I'm aware that my Lucid issue reflects badly on all at HQ.

**Comment by staceypark** [comment]
@lzim that's my bad. it looked like there was a duplicate so I closed one. I reopned it.  https://github.com/lzim/teampsd/issues/679

>  CC @staceypark & @ritahitching the manuscript_tracker is missing r21_cc_jgim https://osf.io/c24xz/

**Comment by staceypark** [comment]
@lzim  I touched based with @TomRust who is going to be working on the S08 SAY file tomorrow morning. And then you two can connect after the facilitation meeting.

**Comment by ritahitching** [comment]
@lzim just a quick update on the references from the R01 for the manuscripts;

-  Created a spreadsheet with all 180 full references, and reference numbers. 

- Currently in the process of adding the commensurate cite keys.

**Comment by ritahitching** [comment]
@lzim 

- update on cite keys - I have completed 60/188 from R01 grant.  

- there are several errors in the way that the references were imported into Zotero - having to manually update - so process slower than anticipated.

- [ ] will complete by friday 9/20 am

**Comment by staceypark** [comment]
@lzim I was able to get my question answered at the REDCap office hours earlier 🎆 
REDCap is setup and ready to go for tomorrow's session

**Comment by ritahitching** [comment]
@lzim 

- completed the list of references and cite keys for R01 grant.

- unable to locate 5/188 in the list.

- want me put the list somewhere for you?

- shall I move on to IIR next?

**Comment by staceypark** [comment]
@lzim 
@ritahitching and I are both overdue on our online sexual harassment training so we're doing that right now

**Comment by staceypark** [comment]
#friday hqhuddle
- [ ] SIRC travel
- [ ] Evite for 10/4 TeamPSD potluck to include RSVP and item to be brought
- [ ] Cancellation of old manuscript meeting and send out new manuscript meeting invitation[ ] 
- [ ] update OSF cheatsheet with WIndows instructions

**Comment by lzim** [comment]
Thanks @staceypark and @ritahitching!

Did you upload the cite key table to the OSF profile projects?

Happy weekend! 😎

**Comment by staceypark** [comment]
@lzim yes I did! It’s missing ~20 or so refs though that weren’t in Zotero according to @ritahitching

**Comment by lzim** [comment]
Thank you, thank you, thank you!!!!

**Comment by lzim** [comment]
# #hq huddle 9/23/2019

**Good morning**!!
@staceypark and @ritahitching 

#### hq workflow
I believe we were going to update the next weeks' huddle by COB Friday, right?
I don't see it, yet. So, I'm posting here:

- [x] I moved s**08 say** and **say_checklist** to **mtl.how** 
- [ ] We did not yet take Tom's work on **s07 say** (and possibly s06 say) from **teampsd** to **mtl.how**, because it was not done by COB, and we promised the ICs we wouldn't change it mid-week. @staceypark will you please make sure mtl.how is current with **TeamPSD** for **s07?**
- [ ] @ritahitching or @staceypark Will you please update the **team2 and team 4 tables on issue #303** and **Jane's table** to all include last week's **s07** training, so we know who was there and who did what **_over the whole week_**?

#### workgroup leads
As we discussed, my plan is to be in a virtual writing retreat with Tom this week, to the greatest extent I possibly can. As a result, I will not be at workgroup leads this AM.
- [ ] Please make sure everyone knows the TeamPSD potluck will be 10/4 after work in RWC and that the invitation details will be coming out TODAY!
- [ ] Please review any late documentation

#### co-Is
- [ ] Please make sure to cover the adjusted 9/24 - > 10/1 schedule for the **co-I meeting.**
- [ ] Please make sure folks are moving manuscripts forward (e.g., David); and let them know about the reference table that @ritahitching updated 👍 
- [ ] David and I will need time to prep for the AHSR workshop - Let's let this up during the first or second week of October

#### co-Fs
- [ ] Please make we are all set up and ready to go at 10AM to record **group_supervision** via Adobe Connect.

Thanks!

**Comment by ritahitching** [comment]
@lzim - I hope this is clearer - let me know if you want any additional edits
@staceypark 



Monday | HQ Lead | HQ Attendees |   | Tuesday | HQ Lead | HQ Attendees |   | Wednesday | HQ Lead | HQ Attendees |   | Thursday | HQ Lead | HQ Attendees |   | Friday | HQ Lead | HQ Attendees
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
8:00am  to 9:00am Workgroup Leads |   | LZ RH SP |   | 8:00am  to  9:00am qual coding workgroup |   | LZ SP |   | 9:30am to 11:30am intersession prep |   | LZ SP RH |   | 8:00am to 8:55am support workgroups |   | LZ SP |   | 9:30 am to 11:30 am MTL Facilitate |   | LZ RH SP
9:00am  to  12:00pm Manuscript Monday |   | LZ RH SP |   | 10:00 to  10:55am manuscript group |   | LZ SP RH |   | 11:00am to 12:00pm all staff meeting |   | LZ RH SP SM SH |   | 10:00am to 10:55 am quant work groups |   | LZ SP RH |   | 12:00pm to 12:30pm HQ Huddle |   | LZ RH SP
12:30pm to 1:00pm HQ Huddle |   | LZ RH SP |   | 11:00am to 1:00pm psychotherapy tool |   | LZ SP RH |   | 12:00pm to 12:30pm HQ Huddle |   | LZ RH SP |   | 1:00am to 2:00pm HQ workgroup |   | LZ SP RH |   | 4:00 pm to 4:30pm HQ Huddle |   | LZ RH SP
4:00 pm to 4:30pm HQ Huddle |   | LZ RH SP |   | 1:00pm to 2:00pm TeamPSD Lunch |   | LZ RH SP SM SH |   | 4:00 pm to 4:30pm HQ Huddle |   | LZ RH SP |   | 12:00pm to 12:30pm HQ Huddle |   | LZ RH SP |   |   |   |  
  |   |   |   | 4:00 pm to 4:30pm HQ Huddle |   | LZ RH SP |   |   |   |   |   | 4:00 pm to 4:30pm HQ Huddle |   | LZ RH SP |   |   |   |  


- [ ] Can we discuss the afternoon and wednesday #hqhuddle timing at our next meeting please?
