### ISSUE TITLE
Week of 9/23 #hqhuddle

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#716]
@lzim 

- [ ] CC #679
- [ ]  MM #688 
- [ ]  PSY #690 
- [ ]  AGG #678
- [ ]  SP #696

**Dexter w/teampsd**
- [ ] Dexter's Demo Account deleted [again] set him up with course code, or talk with @staceypark about pros of adding him to one of our MTL Facilitate training teams.
- [ ] Once Dexter creates a free GitHub log-in; add him as a Team PSD Contributer
- [ ] Have Dexter sign the NCPTSD Research Scope of Practice
- [ ] Test Data UI permissions at next meeting

@staceypark 
- [x] Evite for 10/4 TeamPSD potluck to include RSVP and items to be brought - to send out today
- [x] move over updated mtl.how see/say guides
- [x] SIRC travel
- [ ] Please make sure folks are moving manuscripts forward (e.g., David); and let them know about the reference table that @ritahitching updated
- [ ] update OSF cheatsheet with WIndows instructions
- [ ] Cancellation of old manuscript meeting and send out new manuscript meeting invitation
- [ ] David and I will need time to prep for the AHSR workshop - Let's let this up during the first or second week of October
- [ ]  f/u with rachel kimerling for TeamPSD GitHub
- [x] get photo from Ren for team website 
email Steve/Doug about the space in the server link - @lzim are we asking them to change it? that would mean everyone on TeamPSD needs to re-map, not to mention the link will break for the whole center.

@ritahitching 

- [x] tt report 
- [x] Will you please update the team2 and team 4 tables on issue #303 and Jane's table to all include last week's s07 training, so we know who was there and who did what over the whole week?
- [ ] add psychometric properties to Measures for grants on GitHub: https://github.com/lzim/teampsd/tree/master/mtl_facilitate_workgroup/evaluation

 **R01 First**
- [ ]  Consort table in OSF for R01 https://osf.io/8pzxu/
- [ ]  Consort table in OSF for IIR https://osf.io/p7g8f/
- [ ]  R01 CT.gov see if anything is missing

**IIR Second**
- [ ]  Double-check IIR IRB
- [ ]  ART > CT.gov for IIR
- [ ]  Preparing the Union Notification Letter

@jessfroe 
- [x] update photo & bio in GitHub
- [x] update photo & bio in TeamPSD website

**Comment by staceypark** [comment]
@staceypark add gifs to adobe connect cheatsheet for facilitators to share screens
@ritahitching track on Issue #303 places where facilitators have switched teams

**Comment by lzim** [comment]
@staceypark Is there a way to export .md from Lucid?
😕❓ 

I was hoping I could plop the work we did today in the manuals...if it were in . md we could.

**Comment by staceypark** [comment]
@lzim oof I don't think so.... outside of just copy pasta.
I just spoke with Farrel & Doug, and yes the Lounsbury IPA $$ is use or lose by 9/30.

**Comment by ritahitching** [comment]
@lzim - I hope this is clearer - let me know if you want any additional edits
@staceypark 

Monday | HQ Lead | HQ Attendees |   | Tuesday | HQ Lead | HQ Attendees |   | Wednesday | HQ Lead | HQ Attendees |   | Thursday | HQ Lead | HQ Attendees |   | Friday | HQ Lead | HQ Attendees
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
8:00am  to   9:00am Workgroup Leads |   | LZ RH SP |   | 8:00am  to  9:00am   Qual Coding Workgroup |   | LZ SP |   | 9:30am to 11:30am   Intersession Prep |   | LZ SP RH |   | 8:00am to 8:55am   Support Workgroups |   | LZ SP |   | 9:30 am to 11:30   am MTL Facilitate |   | LZ RH SP
9:00am  to  12:00pm   Manuscript Monday |   | LZ RH SP |   | 10:00   to  10:55am Manuscript Group |   | LZ SP RH |   | 11:00am to 12:00pm   All Staff Meeting |   | LZ RH SP SM SH |   | 10:00am to 10:55   am Quant Work Groups |   | LZ SP RH |   | 12:00pm to 12:30pm   HQ Huddle |   | LZ RH SP
12:30pm   to 1:00pm HQ Huddle |   | LZ RH SP |   | 12:00pm to 12:30pm   HQ Huddle |   | LZ RH SP |   | 1:00am to 2:00pm HQ workgroup |   | LZ SP RH |   | 4:00 pm to 4:30pm HQ Huddle |   | LZ RH SP |   |   |   |  
4:00 pm   to 4:30pm HQ Huddle |   | LZ RH SP |   | 1:00pm to 2:00pm   TeamPSD Lunch |   | LZ RH SP SM SH |   | 4:00 pm to 4:30pm   HQ Huddle |   | LZ RH SP |   | 12:00pm to 12:30pm   HQ Huddle |   | LZ RH SP |   |   |   |  
  |   |   |   | 4:00 pm to 4:30pm   HQ Huddle |   | LZ RH SP |   |   |   |   |   |   |   |   |   |   |   |  


- [ ] Can we discuss the afternoon and wednesday #hqhuddle timing at our next meeting please?

**Comment by ritahitching** [comment]
@lzim - I hope this is clearer - let me know if you want any additional edits
@staceypark 

Monday | HQ Lead | HQ Attendees |   | Tuesday | HQ Lead | HQ Attendees |   | Wednesday | HQ Lead | HQ Attendees |   | Thursday | HQ Lead | HQ Attendees |   | Friday | HQ Lead | HQ Attendees
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
8:00am  to   9:00am Workgroup Leads |   | LZ RH SP |   | 8:00am  to  9:00am   Qual Coding Workgroup |   | LZ SP |   | 9:30am to 11:30am   Intersession Prep |   | LZ SP RH |   | 8:00am to 8:55am   Support Workgroups |   | LZ SP |   | 9:30 am to 11:30   am MTL Facilitate |   | LZ RH SP
9:00am  to  12:00pm   Manuscript Monday |   | LZ RH SP |   | 10:00   to  10:55am Manuscript Group |   | LZ SP RH |   | 11:00am to 12:00pm   All Staff Meeting |   | LZ RH SP SM SH |   | 10:00am to 10:55   am Quant Work Groups |   | LZ SP RH |   | 12:00pm to 12:30pm   HQ Huddle |   | LZ RH SP
12:30pm   to 1:00pm HQ Huddle |   | LZ RH SP |   | 12:00pm to 12:30pm   HQ Huddle |   | LZ RH SP |   | 1:00am to 2:00pm HQ workgroup |   | LZ SP RH |   | 4:00 pm to 4:30pm HQ Huddle |   | LZ RH SP |   |   |   |  
4:00 pm   to 4:30pm HQ Huddle |   | LZ RH SP |   | 1:00pm to 2:00pm   TeamPSD Lunch |   | LZ RH SP SM SH |   | 4:00 pm to 4:30pm   HQ Huddle |   | LZ RH SP |   | 12:00pm to 12:30pm   HQ Huddle |   | LZ RH SP |   |   |   |  
  |   |   |   | 4:00 pm to 4:30pm   HQ Huddle |   | LZ RH SP |   |   |   |   |   |   |   |   |   |   |   |  


- [ ] Can we discuss the afternoon and wednesday #hqhuddle timing at our next meeting please?

**Comment by ritahitching** [comment]
@lzim grant me access to

1. Consort table in OSF for R01 https://osf.io/8pzxu/

1. Consort table in OSF for IIR https://osf.io/p7g8f/

**Comment by staceypark** [comment]
@lzim I gave @ritahitching access to the IIR project but I don't have admin access to R01.

**Comment by ritahitching** [comment]
> @staceypark Is there a way to export .md from Lucid?
> 😕❓
> 
> I was hoping I could plop the work we did today in the manuals...if it were in . md we could.

**Comment by ritahitching** [comment]
@lzim @staceypark  lucid has the an option to select **record** and download as **pdf / html** and **word**

**Comment by ritahitching** [comment]
@lzim thanks for reopening the issue

**Comment by lzim** [comment]
> @lzim @staceypark lucid has the an option to select **record** and download as **pdf / html** and **word**

- Yes, I see those buttons. But, at one point I though they were going .md 
- It may be worth it to mention it to them 😺 
- I believe this is just a reminder to try to use as Markdown consistent formatting when we take notes as we can, _rather than rely on the Lucid formatting_ I can just as easily record using .md and then I can use what I write more easily in manuscripts and other documentation.

**Comment by lzim** [comment]
> @lzim grant me access to
> 
> 1. Consort table in OSF for R01 https://osf.io/8pzxu/
> 2. Consort table in OSF for IIR https://osf.io/p7g8f/

@ritahitching you now have access as a **contributer** to the **R01 protocol**🤗 
@staceypark you now have **admin** access to the **R01 protocol** 🤗 

Thanks!

**Comment by ritahitching** [comment]
@lzim 

1. Finished all the references for the IIR - pleaes update GitHub as I cannot upload from here
2. I need read/write or admin access to OSF as I currently cannot upload files and want to add the updated cit key list
3. I'll send screen shots to explain the missing references from the list 

thanks

**Comment by staceypark** [comment]
@lzim Made some updates regarding s08 to say checklist and team tracker. check out PR #721

**Comment by lzim** [comment]
###End of Day - hq huddle

@staceypark 
- [ ] 1. send potluck invite
- [ ] 2. send Lucid for EES on Thurs - Note: try to get an update from James about 508 before we meet.
- [ ] 3. Update Lucid Meeting template
- [ ] 4. Back-up the video 

#### First thing in the AM
- [ ] Email out the Lucid with the link to the video ASAP in the AM.
- [ ] Need to track how people navigate to the Text from within the small "Outputs and Text" Section
- If we change "Expand" to "Text" it's a lot of a rework, but less now than it will be in a few weeks when the videos and documentation are frozen. 

REMINDER @staceypark and @ritahitching 
- [ ] Track timestamps very carefully on Wed and during #fidelityfriday demo sesison
- This will be key for sessions 8,9,10

**Comment by lzim** [comment]
Hi @staceypark and @ritahitching 

- I can't seem to find an issue talking about the updates needed to mtl.how/team??

Anyway, I uploaded the photos for Ren and Jessilyn here: https://github.com/lzim/teampsd/tree/master/resources/photos

Let's be sure to get Rita's up too.

Lindsey

**Comment by lzim** [comment]
Morning #hq !!

- Had a call with Tom and James each so far this morning, to resolve Issue #709. I believe we are clear and have a plan.

- I am going to try to work remotely today, not just due to our writing deadlines, but also as I may be fighting something, and just in case I don't want to spread at the office 🤧 

- I'll be on my TIDIRH call on Adobe Connect at 8AM.
- Then, let's be ready to record our Intersession prep at 9:30AM.

Thanks!

Lindsey

**Comment by lzim** [comment]
Oh, and I should add, Tom and I are going to touch base about the CC manuscript at my 1PM.

- Please let me know if there are any EBPharm/OSF updates from Savet and Andrew that need my attention.
- Or, anything on the R01/IIR protocol work.

Thanks!

**Comment by staceypark** [comment]
@lzim all of our headshot photos are here including Rita's: https://github.com/lzim/teampsd/tree/master/resources/headshots
> Hi @staceypark and @ritahitching
> 
> * I can't seem to find an issue talking about the updates needed to mtl.how/team??
> 
> Anyway, I uploaded the photos for Ren and Jessilyn here: https://github.com/lzim/teampsd/tree/master/resources/photos
> 
> Let's be sure to get Rita's up too.
> 
> Lindsey

Everything is ready to go for our 9:30a. I sent out Monday's notes + recording and updated today's agenda.

**Comment by ritahitching** [comment]
@lz thanks for your flexibility this morning. Back at HQ.

**Comment by lzim** [comment]
#### #hq mid-day huddle

Hello Everyone!

Are we clear on afternoon priorities for the mid-day huddle?

@lzim 
- [ ] #709 w/Tom and James
- [ ] #462 #476 EBPharm for Andrew and Savet
- [ ] #679 CC manuscript call w/Tom
- [ ] Facilitation principles from this morning's prep - currently revising these on Lucid, so they can go out with the f/u email and video link.

Note:
- [ ] Adobe Connect issues - I had several today while remote working. I think we need to get to the bottom of this

What about you two 😄 ?

**Comment by staceypark** [comment]
@ritahitching is going to continue working on the CONSORT table items.
- [ ] prep for Quant meeting tomorrow

@lzim 
Can you be more specific about your Adobe Connect issues? I'm wondering what happened and if I've encountered them before. 

@staceypark 
- [ ] Backup prep recording and send lucid followup - Video is still backing up for today's session and I'll send out the email with the link once that's done.
- [ ] send out potluck evite: @lzim I sent you an updated evite for the potluck. If it's good to go, then I can send it out to the folks we talked about yesterday.
- [ ] Prep for leads meeting tomorrow
- [ ] finish Zotero cheatsheet: it's almost done!

**Comment by ritahitching** [comment]
@LZ working on the R01 consort table - do you want to keep the cite keys within the text and table references for the references or delete them?

**Comment by ritahitching** [comment]
@lzim will you take a quick look to see if you like the progress thus far: https://osf.io/8pzxu/wiki/consort_checklist/

**Comment by lzim** [comment]
#hq COB

@ritahitching I’ll look at your progress on the OSF so you have my comments in the AM.
I hope the talk went well today!

Let me know if you all need anything else to be ready for the AM.

Thanks!

**Comment by ritahitching** [comment]
@lzim thanks,

-  I'll look for comments tomorrow morning, address issues, complete and then pivot to IIR table.

- @staceypark and I had a lunchtime #hqhuddle regarding tomorrow's quant meeting.  I will discuss with the team:

1. Progress reports - the breakdown of tasks into micro-tasks 
3. Update due dates on micro and macro tasks - costs/time
4. Provide scope of  micro and macro deliverables by COB daily

HQ to model appropriate clarification, communication and reflection.

**Comment by staceypark** [comment]
@lzim I took a first pass with Savet on the slide deck.

**Comment by lzim** [comment]
For Friday: 
@staceypark 
- [ ] Need to update pre/post checklist locations w/links 

We noticed today that the checklists would benefit from being updated to reflect what goes in the **team_tracker,** what goes in Lucid, what goes in **issue_tracker,** and what is in VA TedCap

**Comment by lzim** [comment]
Morning #hq 

@lzim now:
- [ ] Asking clarifying questions on #462 #476 of Andrew and Savet
- [ ] Then, will turn to feedback for Rita
- [ ] Then, will turn to Slide deck.

Plan to focus on manuscripts w/Tom afterward.

**Comment by ritahitching** [comment]
@lzim and @staceypark 

1. Andrew and Savet will be putting together a ranked list of decisions they need for the 10:00am Quant meeting. 
2. We'll update asap / ideally before the meeting to enable triage at the start

**Comment by lzim** [comment]
@ritahitching @staceypark 

re: Quant meeting.
> 2. We'll update asap / ideally before the meeting to enable triage at the start

Please see my email and my OSF comment (an abbreviated version).
I will not be meeting with Andrew and Savet until they have documentation that can be used to answer their questions.

No decisions can be made from the documentation as it is now.
I spent the last hour asking the questions I have based on the current documentation.

If all the questions are answer and documentation cleaned up, then I can meet with them.
Please see if you can carve out time to get their documentation consistent enough to answer the questions that they have.

> 1. Andrew and Savet will be putting together a ranked list of decisions they need for the 10:00am

**Comment by lzim** [comment]
#hq mid-day huddle

@staceypark and @ritahitching 
The #hq huddle starts in a couple of minutes.

Are you able to update me on how the morning went, and list out any other tasks that you’ll prioritize this afternoon?

I can take a brief call if it would be helpful.

Thanks!

**Comment by lzim** [comment]
> @lzim will you take a quick look to see if you like the progress thus far: https://osf.io/8pzxu/wiki/consort_checklist/

@ritahitching You are doing great work on this!  It really looks great, thank you! 👏

**Comment by staceypark** [comment]
@lzim we're just now wrapping up the quant meeting

**Comment by lzim** [comment]
Thanks for the update, let me know if you need me.

Lindsey

**Comment by staceypark** [comment]
@ritahitching
- [ ] continue working on CONSORT table for r01 and then iir

@staceypark
- [ ] add myself and Rita to manuscript sim world (which hopefully exists)
- [ ] need to update pre/post checklist locations w/links
- [ ] update Friday agenda and make sure fidelity survey is setup 

@lzim did you want me to record again tomorrow?

**Comment by lzim** [comment]
> @lzim did you want me to record again tomorrow?

@staceypark yes, please.

- I will try to get to the bottom of what was happening with Adobe Connect, but I don’t actually know. I’d like to try it remotely again tomorrow, because I was having issues that I don’t when I’m at my VA machine, and many _MTL_ Co-Facilitators will have to remote in regularly.

**Comment by lzim** [comment]
Hello #hq 

We have our end of day huddle in about 10 minutes, will you please each take a look at my questions for Savet and Andrew on Issue #462 and I updated OSF too with questions here: https://osf.io/z7y8m/wiki/Data%20Definition/

I’d like to quickly touch base with you both, so that you’re clear about coaching them effectively.
Thanks!

**Comment by lzim** [comment]
Substantive Issues **Under Development** that could impact _MTL Facilitate Training_ on **#fidelityfriday**
- [ ] #709 
- [ ] #727

**Comment by lzim** [comment]
For Friday AM

If we do need to update the calculations described on #462 and #476  

Then,@staceypark and @ritahitching we’ll want to
- [ ] email Co-Is tomorrow morning and try to reschedule for 10/8
- [ ] set up the new manuscript meetings to include all co-Is, etc. _indicating that we’ll let folks know when to attend the meeting for specific manuscripts, and that in general, we’d still like all co-Is to protect the 4th Tuesday of the month.

Thanks!

**Comment by staceypark** [comment]
@lzim can you check my pull request for the pre and post before the meeting?

**Comment by lzim** [comment]
> @lzim can you check my pull request for the pre and post before the meeting?

Yes @staceypark I just approved it.

Thanks!

**Comment by ritahitching** [comment]
@lzim  send a screen shot of the fidelity ratings for Team 2 for session 8 to @staceypark

**Comment by staceypark** [comment]
@lzim started the 000 backup.
@ritahitching can you add this week's details to the two tables on #303 tracking attendance and practice.

**Comment by lzim** [comment]
@staceypark and @ritahitching 

- Y’all at #hq ready to huddle? 🏉

**Comment by ritahitching** [comment]
@lzim 

1. Completed as much as I could of the Consort Table for the R01. https://osf.io/8pzxu/wiki/consort_checklist/
2. Will pivot to IIR

**Comment by staceypark** [comment]
@lzim 
Sent out today's Facilitate notes with the video link, schedule the 10am quant meeting for tuesday, sent the cancellation for the co-I meeting on Tuesday, and set up agenda for Monday's WL meeting.

also side note on the below point: Between prep on Wednesday & facilitation today, I didn't notice anyone getting confused about this. To be fair, I was the team lead for our team today, but I did "play dumb" a few times and ask how to zoom in/out through the Text > Outputs & Text > Expanded Outputs & Text and folks seemed to know how to do it.

> Need to track how people navigate to the Text from within the small "Outputs and Text" Section

@lzim @ritahitching  New huddle issue opened for next week at #732
