### ISSUE TITLE
Week of 9/30 HQ Huddle

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#732]
@lzim 
Monday will be Tom's official "last day" with TeamPSD so @lzim  will still be full speed ahead on getting documentation finished.
- [x] Make sure Session 09 SAY & Say checklist are on mtl.how before manuscript meeting (the SEE guide is already there)

Open Issues related to @TomRust:
#729 
#726 
#596 

Dexter w/teampsd
- [ ]  Dexter's Demo Account deleted [again] set him up with course code, or talk with @staceypark about pros of adding him to one of our MTL Facilitate training teams.
- [ ]  Once Dexter creates a free GitHub log-in; add him as a Team PSD Contributer
- [ ]  Have Dexter sign the NCPTSD Research Scope of Practice
- [ ]  Test Data UI permissions at next meeting

@ritahitching 
- [x] update Issue #303 with Session 08 info and note where facilitators switched teams
- [x] add psychometric properties to Measures for grants on GitHub: https://github.com/lzim/teampsd/tree/master/mtl_facilitate_workgroup/evaluation

R01 First
- [x]  Consort table in OSF for R01 https://osf.io/8pzxu/
- [x]  Consort table in OSF for IIR https://osf.io/p7g8f/
- [x]  R01 CT.gov see if anything is missing

IIR Second

- [ ]  Double-check IIR IRB
- [ ]  ART > CT.gov for IIR
- [x]  Preparing the Union Notification Letter

@staceypark 
- [x] Expand R01/IIR Grants meeting to be weekly and include manuscript meeting. Accompany with email for everyone to make sure to delete old Manuscript Meeting off their calendars.
- [x] Schedule AHSR prep with LZ and DWL for 2nd week of October
- [ ]  update OSF cheatsheet with WIndows instructions
- [ ]  f/u with rachel kimerling for TeamPSD GitHub again

**Comment by staceypark** [comment]
@lzim Should I be ready to record again tomorrow or will you be in to record?

**Comment by lzim** [comment]
Good Morning!🍳

> @lzim Should I be ready to record again tomorrow or will you be in to record?
@staceypark Yes, will you please record today?

1. Debbie made additional See edits in PR #733.
- Would you accept them and get mtl.how current?

2. I’m still tweaking Say for 9 this morning and will have it up soon. 

3. Tom, will be late at 9AM.
- He and I are going to meet at 1PM & we can gameplan for the open issues you list.

**Comment by staceypark** [comment]
@lzim Ok I updated the s09 & s10 SEE guides at mtl.how.
And I added the link to s09 SAY guide to the s09 resources meta card.
I/you also need to add the s09 SAY checklist link to the s09 resources meta card as soon as that's done

**Comment by ritahitching** [comment]
@lzim @saveth will review/edit/contribute to my completed first pass of the consort table of the R01.

**Comment by staceypark** [comment]
@lzim  I haven't closed the meeting because it looked like you were editing. Are you done editing?
Also you and Tom are recording in Adobe Connect right?

**Comment by staceypark** [comment]
@lzim  I created two pull requests - one for the team tracker and one with edits on the s09 say checklist

**Comment by staceypark** [comment]
@lzim 
@ritahitching put together the tt report and I just sent it off

**Comment by staceypark** [comment]
@lzim Lara will be joining us Thursday. I just sent her the Lucid.

**Comment by staceypark** [comment]
@lzim 
@ritahitching sent the email asking folks to cancel their Manuscript meetings.
We'll send another reminder tomorrow to cancel and send the invitation Wednesday.

I saw you accepted my pull request and updated the session 09 checklist on t02 & t04. 

Did you want to huddle?

**Comment by staceypark** [comment]
@lzim Hope you're feeling better! 🤒 
- The recording from this morning is still getting backed up. I can send that out tomorrow morning when it finishes.
- Not sure if you're well enough to be in tomorrow, but Mark won't be joining the seminar (re: his email). I can help @swapmush make sure we're setup in the conference room if you're joining remote.
- It'll be Andrea's first day as qual lead tomorrow. Will @jessfroe as the qual HQ point, be taking point on getting her setup for TeamPSD (team website, github, lucid, etc.) or should I reach out to her? And she will be joining the Monday Leads meetings from now on yes?

**Comment by swapmush** [comment]
Hey Stacey 

I’m on my way to San Diego for a conference. I will be remoting in to qual and manuscript and not attending Stanford. 

-Swap

**Comment by lzim** [comment]
@staceypark 

- [ ] Will you please be sure to back up the very short video that Tom and I made in Adobe during our meeting, and add it to 000?  It goes with the change that we made in Issue #739, now in DEV.
We’ll want that update for Wednesday

- Yes, I will be in tomorrow for Stanford and other meetings.
- @jessfroe will continue to be the HQ point for the meetings, but we may need some extra HQ help gettin her set up, in general. @staceypark are you able to join us for just the first 30 minutes tomorrow as we orient Andrea?
- I am not sure whether Andrea will be joining the Monday meetings, yet. We need to get her up and running, in general, first.

- Tomorrow I have the post doc seminar at 2PM.
- I will also be meeting with Tom on Wednesday afternoon about the CC and MM manuscripts.

**Comment by ritahitching** [comment]
@lzim completed the first pass of the consort table for the IIR.

**Comment by ritahitching** [comment]
@lz 
1. The psychometric properties for the grants are already in Github.  
2. I will start on CT registration next.

FYI @staceypark

**Comment by staceypark** [comment]
@lzim 
- [ ] create a CT account for @ritahitching

**Comment by jessfroe** [comment]
Hi @staceypark 
I emailed Andrea about setting up GitHub & OSF accounts. I'll keep you in the loop when we have her bio and photo up for the tt_report

@lzim Just to keep you in the loop, I did send the first batch of video edits to Ann via new excel file in the mtl_video_review project 🤓

**Comment by ritahitching** [comment]
@lzim @staceypark 
R01 CT.gov draft submission looks good.

**Comment by staceypark** [comment]
@lzim on the action items from the qual meeting:

I think you guys opened up the wrong version. We're at 3.6.1 now. I archived the other ones so it's more clear. You can also find it here: https://github.com/lzim/teampsd/blob/master/qual_workgroup/r/r_setup/r_library_setup_3.6.1.pdf
> 1. For on your VA machine/Inside the VA:Re-format the r_library_setup_3.6 document 

Did you want this for RQDA specifically? And if so, don't we want it in the qual_workgroup folder instead? If not for RQDA specifically, not sure what packages you're talking about.
> 2. For outside the VA/Personal machine: Create an install script of the list of Team PSD R packages here: https://github.com/lzim/teampsd/t ree/master/resources/r/packages

**Comment by staceypark** [comment]
@lzim @ritahitching hey hq heads up I'm feeling increasingly sniffly 🤧 .  not sure if its season change allergies, or the flu shot.... 
Will keep you updated!

**Comment by ritahitching** [comment]
@staceypark hope you are feeling better.
@lzim Planning to focus on IRB & ART/CT.gov for IIR today. Let me know if I should focus on anything else.

**Comment by lzim** [comment]
Morning #hq 

Glad you are feeling okay @staceypark ! thanks for keeping us posted too :😺
FYI @ritahitching

#### facilitate_workgroup
- [ ] I’m catching up on the Team 2 **team_tracker** details, which were not properly recorded last week. I want to get that squared away before we move forward today.
- I still need to decide what to do about Team 4, without Tom: Right now, we only have Debbie on deck, whereas we have David and Jane for Team 2, so I may do some sort of trade with you, Stacey. Perhaps spend a bit of my time with each team to help them to prepare.
- [ ] Will you please plan to record today? 

#### quant_workgroup
- [ ] I see that on #462 Andrew is answering questions, but hasn’t yet updated OSF - although he says he is turning to that now.
**Please use the OSF documentation to make sure that you can get your questions answered there, it will be consistent with what we discussed yesterday and helpful for Andrew and all of us, if we make sure that all the details are in the documentation.**

#### video back-up 
- [ ] Video from Qual - put this in qual_workgroup in TeamPSD folder, I believe
- [ ] Extra Video from #manuscriptmonday that Tom and I recorded

#### writing today
- Tom and I plan to review our progress after **intersession prep** 
And, since I’m still trying to get caught up on writing, and was in back-to-back meetings yesterday from 8AM-5:30PM, I plan to work from home today and try to get as much done as I possibly can. 
- Let me know if/when you want or need to huddle to make sure we’re all on track with our top priorities.

#### workshop for AHSR w/David
- [ ] When are David and I meeting to prepare our workshop for AHSR?

**Comment by lzim** [comment]
> @staceypark hope you are feeling better.
> @lzim Planning to focus on IRB & ART/CT.gov for IIR today. Let me know if I should focus on anything else.

Thanks @ritahitching that sounds good to me! 

- [ ] Also, @staceypark will you also make sure that your PR edits on the session09_say_checklsit are not only on TeamPSD, but are also on mtl?

Thanks!

**Comment by ritahitching** [comment]
@lzim I updated OSF with my query - for documentation purposes.

**Comment by staceypark** [comment]
@lzim David & I penciled in 1hour slots before and after the Facilitate meeting next Wednesday for AHSR prep. He tentatively has another call, so we'll know closer to date.

**Comment by ritahitching** [comment]
@lzim @staceypark Will you please reactivate my SuNetID so that I can work on the IRB submission - my SuNetID is **hitching**

**Comment by ritahitching** [comment]
@lzim @staceypark 
Is the Union Notification Letter for the American Federation of Government Employees (AFGE)?

**Comment by staceypark** [comment]
@lzim 
- [ ] can you add Jay to the TeamPSD repo (JayLCohen)

**Comment by lzim** [comment]
> @lzim
> 
> * [x]  can you add Jay to the TeamPSD repo (JayLCohen)

@staceypark Yes, I’ve added @jaylcohen He needs to accept the invite.

> @lzim @staceypark
> Is the Union Notification Letter for the American Federation of Government Employees (AFGE)?

@ritahitching There is an example, I’m not sure. But, we need to follow the JIT instructions for this.

> @lzim @staceypark Will you please reactivate my SuNetID so that I can work on the IRB submission - my SuNetID is **hitching** a Sponsored Personal SUNet ID should suffice - I believe they are no cost request.
> 
> https://adminguide.stanford.edu/chapter-6/subchapter-4/policy-6-4-1

@staceypark and @ritahitching Craig sponsors these for us.

@staceypark Anything you need to huddle about before you leave for the day?

**Comment by staceypark** [comment]
@lzim re: jay 
great I'll follow up with him again and make sure he accepts that.

re: SUNetID
I'll email Craig then cc'ing all of us

Don't think I need to huddle about anything. Video is still backing up from the session, so hopefully I can send that out tomorrow.

**Comment by ritahitching** [comment]
@lzim please confirm that the Union Letter and accompanying paperwork is for the R01?

**Comment by staceypark** [comment]
@ritahitching 
- [ ] reach out to OSF support/helpdesk on issue of "disappearing comments"

**Comment by ritahitching** [comment]
@lzim @staceypark do you know if the  Organizational Assessment Sub-Committee (**OASC**) Review has **signed off** on the **surveys** we are planning to administer to the VA clinicians? 

**Surveys**:
- Patient Aligned Care Team (PACT): Survey-Burnout
- Learning Organization Survey (LOS-27)
- Team Decision Making Questionnaire (TDMQ)
- Pragmatic Measures (AIM/IAM/FIM)

According to the recommendations we **need** **approval** by **OASC** **before** we can **submit** to the **Union**.

- Details: https://www.research.va.gov/resources/oasc.cfm

**Comment by ritahitching** [comment]
@ritahitching 

- [ ] update table of screens with new details from Pavir and attach stickers to screens

**Comment by staceypark** [comment]
@staceypark 
- [ ] email Yogita about recurring expenses for ReqLogic (Rebrandly, Adobe Illustrator, Zotero, Basecamp, R Shiny, GitHub private team tracker, SpeedScriber)
- [ ] R01 & IIR IRB's - add Andrea, double check that Rita & Jessilyn are added, remove Erica
- [ ] look at excel on the email related to #742 
- [ ] Need Andrew to scope #642 & #598 
- [ ] Video review and popup edits --- inventory the "must have" adds (we can have Jane & Debbie review videos instead rather than 
- [ ] Email Anastasia Villefranco to remove Alexandra from RDIS

@ritahitching 
- [ ] cc Lindsey in PIV email
- [ ] update tables on #303 for tracking who facilitated, what got recorded, etc.
- [ ] update schedule tables at the top of team specific cards in team_tracker

**Comment by ritahitching** [comment]
@lzim reached out to PAVIR (regarding badge) and OSF (regarding missing comments) will update you as I hear more.

FYI @staceypark

**Comment by ritahitching** [comment]
@lzim @staceypark checkethged RDIS and PSD vs AF project is listed and editable.

**Comment by ritahitching** [comment]
Week | Session | #manuscriptmondays | Wed Intersession Prep | Fri Co-Facilitation Practice
-- | -- | -- | -- | --
Sept 30   Oct 2 4 | S09 | TS MH out | TS, JK MH out | TS JF MH out

**Comment by ritahitching** [comment]
@staceypark @lzim
Finished the first pass on the IIR notice for OASC and the Union - it's in TeamPSD in the IIR final folder under JIT.
