### ISSUE TITLE
Week of 10/7 HQ Huddle

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#750]
cross ref last week's huddle - #732 

@lzim 
- [x] s10 say on teampsd and mtl.how
- [ ] DAP & ART for JIT 
- [x] #742 

Wednesday w/Dexter
- [ ]  Dexter's Demo Account deleted [again] set him up with course code, or talk with @staceypark about pros of adding him to one of our MTL Facilitate training teams.
- [ ]  Once Dexter creates a free GitHub log-in; add him as a Team PSD Contributer
- [ ]  Have Dexter sign the NCPTSD Research Scope of Practice
- [ ]  Test Data UI permissions at next meeting

@ritahitching  
- [x] send this week's tt report
- [ ] Double-check IIR IRB 
- [ ]  ART > CT.gov for IIR
- [x] update table of screens with new details from Pavir and attach stickers to screens
- [ ] RDIS IIR complete form
- [ ] Badge push
- [ ] OSF missing comments
- [x] Get CT account

@staceypark 
- [x] email out #fidelityfriday recording
- [x]  look at excel on the email related to #742
- [x] s10 team tracker checklist on teampsd and team_tracker
- [x] Andrea TeamPSD folder access - Doug granted access and sent her mapping instructions
- [x]  email Yogita about recurring expenses for ReqLogic (Rebrandly, Adobe Illustrator, Zotero, Basecamp, R Shiny, GitHub private team tracker, SpeedScriber)
- [ ]  R01 & IIR IRB's - add Andrea, double check that Rita & Jessilyn are added, remove Erica
- [ ]  Need Andrew to scope #642 & #598
- [x]  Email Anastasia Villefranco to remove Alexandra from RDIS
- [ ] update OSF cheatsheet with WIndows instructions
- [ ]  f/u with rachel kimerling for TeamPSD GitHub again
- [ ] add Casey to TeamPSD platforms (bio, photo, GH account)

**Comment by staceypark** [comment]
@lzim #726 & #729 need your attention before group supervision

**Comment by lzim** [comment]
Morning #732 

@staceypark can you update me on #726 and #729 ?

Jane, Tom, David and I are all working on #manuscriptmonday tasks before supervision. I'm on audio.

Can we make sure @ritahitching records today? So that she has practice?

**Comment by staceypark** [comment]
@lzim @staceypark updated monitor tracking table with PAVIR details

Box   Number | Serial Number | User Name | Tower Code | Tested | Port Type | PAVIR Code
-- | -- | -- | -- | -- | -- | --
1 | K1LMTF136062 | LZ | WS148673 | Yes | VGA | 1851
2 | K1LMTF136061 | LZ | WS148673 | Yes | VGA | 1852
  |   |   |   |   |   |  
3 | K1LMTF135441 | SP | WS148674 | Yes | VGA | 1853
4 | K1LMTF135404 | SP | WS148674 | Yes | VGA | 1854
  |   |   |   |   |   |  
5 | K1LMTF135442 | SM | WS136429 | Yes | VGA | 1855
14 | K1LMTF135471 | SM | WS136429 | Yes | VGA | 1864
  |   |   |   |   |   |  
6 | K1LMTF135444 | RH | WS160966 | Yes | HMDI | 1856
8 | K1LMTF135414 | RH | WS160966 | Yes | HDMI | 1858
  |   |   |   |   |   |  
7 | K1LMTF135421 | SH | WS136412 | Yes | VGA | 1857
9 | K1LMTF1 35454 | SH | WS136412 | Yes | VGA | 1859
  |   |   |   |   |   |  
10 | K1LMTF135457 | JF | WS148141 | Yes | VGA | 1860
12 | K1LMTF135437 | JF | WS148141 | Yes | VGA | 1862
  |   |   |   |   |   |  
11 | K1LMTF135434 | TBC | TBC | Yes | TBC | 1861
13 | K1LMTF135980 | TBC | TBC | Yes | TBC | 1863

**Comment by staceypark** [comment]
@lzim #742 the attachment didn't get included in your reply

**Comment by staceypark** [comment]
@lzim we're ready to huddle when you are

**Comment by ritahitching** [comment]
@lzim @staceypark 

- I have exchanged several emails with OSF's technical support team. 
- They don't see any obvious problems on their end but they'll continue to investigate. 
- I'll update as I know more.

**Comment by lzim** [comment]
@staceypark and @ritahitching 

- I think we can take the workstation details off the thread. I assume you'll have a back-up somewhere, but I didn't want to delete unless I was sure that you did.

> @lzim #742 the attachment didn't get included in your reply

- Thanks!

**Comment by ritahitching** [comment]
@lzim 

- [ ] Review draft PD for AH position - it's in our shared drive under Pavir.
- [ ] I'll draft another PD for the Business Analyst and add to same location

**Comment by staceypark** [comment]
@lzim Kera says that SWS team monitors were directed to OI&T to be tagged with a barcode once they arrived. Then they were sent to the team for the PAVIR tagging.

**Comment by ritahitching** [comment]
@lzim - I can meet with Natalia at HR tomorrow and discuss the proposed new hires in person, as I'll be at the VA Palo Alto.  Once we've discussed the job descriptions, classification options etc. we can dial you for a decision. What are your thoughts on this?

FYI @staceypark

**Comment by lzim** [comment]
> Shall I proceed with getting ours double tagged as well?

@staceypark yes

**Comment by staceypark** [comment]
w/Savet
- [ ] update authorship app 
- [ ] clarify ebp equations & definitions before quant meeting

**Comment by ritahitching** [comment]
@lzim 
@staceypark add any others item you are aware of

- [ ] Review PD for 3 positions

- [ ] Get @ritahitching a CT account

- [ ] Review notice OASC and union letter 

- [ ] SuNetId for @ritahitching 

- [ ] Review consort tables on OSF for IIR & R01

**Comment by ritahitching** [comment]
@staceypark 
I started backing up the qual_fidelity_2019_10_8 to the TeamPSD drive

FYI @lzim

**Comment by ritahitching** [comment]
@lzim and @staceypark 
- heading to VAPA ping me if you need anything.

**Comment by staceypark** [comment]
@ritahitching thanks for starting the list for @lzim. I did some editing.

**Comment by ritahitching** [comment]
@lzim @staceypark 
Reached out to Ruth at PAVIR regarding our proposed PDs, left v/m & emailed. Will continue to follow up and update as I have more news.

**Comment by ritahitching** [comment]
@lzim @staceypark 
Badge update - latest: folks have all my paperwork again, as they had lost previously file, sigh... they just need to process it - a week to 10 days is the latest estimate.

**Comment by lzim** [comment]
> @lzim @staceypark
> Badge update - latest: folks have all my paperwork again, as they had lost previously file, sigh... they just need to process it - a week to 10 days is the latest estimate.

Sorry to hear that @ritahitching !

**Comment by lzim** [comment]
> - [ ] Review notice OASC and union letter

@ritahitching this was in Team PSD > Grants, right? Do you have a back-up anywhere? Or do we have to wait until Steve retrieves that folder?

**Comment by ritahitching** [comment]
> > * [ ]  Review notice OASC and union letter
> 
> @ritahitching this was in Team PSD > Grants, right? Do you have a back-up anywhere? Or do we have to wait until Steve retrieves that folder?

Yikes, sorry no. I saved both the OSAC and Union Letter in there. I was under the impression that's the only place to save.

**Comment by ritahitching** [comment]
@lzim @staceypark 

- Spoke on the phone with Ruth at PAVIR regarding 3 hires and discussed the PDs at length.

- Positions 90% of the way there - some final decisions by Lindsey needed

**Ruth will** 

- Send a resume to TeamPSD that she has in hand that may be suitable for Andrew's position

- Call Lindsey to discuss budgets for each position and clarify a couple of issues on the Lead Data Scientist and Research Assistant positions,

**Comment by lzim** [comment]
> @lzim @staceypark
> 
> * Spoke on the phone with Ruth at PAVIR regarding 3 hires and discussed the PDs at length.
> * Positions 90% of the way there - some final decisions by Lindsey needed
> 
> **Ruth will**
> 
> * Send a resume to TeamPSD that she has in hand that may be suitable for Andrew's position
> * Call Lindsey to discuss budgets for each position and clarify a couple of issues on the Lead Data Scientist and Research Assistant positions,

Thanks @ritahitching I would be good to talk with Natalia on my cell this afternoon if at all possible.

- [x] R01 Annual Safety Update

@staceypark 
- [ ] Clarifying r21_manuscripts data file - May need to rename to be consistent with our conventions...Need to know where Tom is with syncing to _MTL Videos_ for use in R21 Module Manuscripts
- [ ] Update DEMO MM Data and need "ahsr2019" course code
- [ ] Where has everything landed since yesterday with the **quant_workgroup** regarding #476 and #462 - Is Savet clear enough about everything to commence? Are there any updates on these two issues based on the meetings yesterday?

**Comment by lzim** [comment]
> > > * [ ]   Review notice OASC and union letter
> > 
> > 
> > @ritahitching this was in Team PSD > Grants, right? Do you have a back-up anywhere? Or do we have to wait until Steve retrieves that folder?
> 
> Yikes, sorry no. I saved both the OSAC and Union Letter in there. I was under the impression that's the only place to save.

@ritahitching Yes, that is the correct location. Hopefully, we'll get it back next week.

**Comment by staceypark** [comment]
@lzim ahsr course code uploaded

**Comment by lzim** [comment]
@staceypark 

Re: Running point on #339 - There are instructions online about how to create a "Code of Conduct" and "Contribution Guidelines" for the mtl.how repo "MTL Community" Wiki for Q&A and upvoting.

**Comment by lzim** [comment]
@staceypark or @ritahitching 

@branscombj posted this on **OSF idc_2019** https://osf.io/rt9qz/wiki/home/ ISDC is issuing last call for updating conference materials in the 2019 Conference Record. All co-authors should have gotten emails; if you need me to send more details I'll forward mine.

Can we confirm that everyone uploaded the final version of their materials, which will live on the web forever after as the 5 Team PSD presentations at the 2019 meeting?

- [ ] Tom
- [ ] Andrew
- [ ] Jane
- [ ] David
- [ ] Lindsey

**Comment by jessfroe** [comment]
@lzim @ritahitching @staceypark 
Looks like the Grants folder is BACK!! 🍾 🍾 🍾

**Comment by staceypark** [comment]
@lzim MM data updated for DEMO model file

**Comment by ritahitching** [comment]
@lzim now that the grants folder is back - I'll work on the IIR update in RDIS - unless you have something else you'd like me to focus on.

FYI @staceypark

**Comment by ritahitching** [comment]
> @staceypark or @ritahitching
> 
> @branscombj posted this on **OSF idc_2019** https://osf.io/rt9qz/wiki/home/ ISDC is issuing last call for updating conference materials in the 2019 Conference Record. All co-authors should have gotten emails; if you need me to send more details I'll forward mine.
> 
> Can we confirm that everyone uploaded the final version of their materials, which will live on the web forever after as the 5 Team PSD presentations at the 2019 meeting?
> 
> * [ ]  Tom
> * [ ]  Andrew
> * [ ]  Jane
> * [ ]  David
> * [ ]  Lindsey


@lzim @staceypark Will you please grant me access and I'll try and follow up.

**Comment by ritahitching** [comment]
@lzim I sent Ruth and Natalia and email letting them know that you are available to speak on the phone this afternoon regarding the new hires.

**Comment by lzim** [comment]
FYI @ritahitching and @staceypark  My slide upload is the FINAL _ I've checked myself off above.

>@branscombj posted this on OSF idc_2019 https://osf.io/rt9qz/wiki/home/ ISDC is issuing last call for updating conference materials in the 2019 Conference Record. All co-authors should have gotten emails; if you need me to send more details I'll forward mine.

>Can we confirm that everyone uploaded the final version of their materials, which will live on the web forever after as the 5 Team PSD presentations at the 2019 meeting?

**Comment by ritahitching** [comment]
@lzim I'm not able to edit our project on RDIS: ZIMNEW_0002 - are you able to double check my user access on the project?

**Comment by lzim** [comment]
@staceypark and @ritahitching 

>@lzim I'm not able to edit our project on RDIS: ZIMNEW_0002 - are you able to double check my user access on the project?
- I emailed Anastasia, which I'm hoping will do the trick 🤞 

Files that I was editing that I cannot save to Team PSD or any other drive 🙄 

Will be working on a work around.

**JIT**
- [ ] PI Assurance
- [ ] OASC 
- [ ] Union letter

**Hires**
- [ ] PDs that require minor edits
- Ruth is going to look for another PD for one of the positions.

**Comment by staceypark** [comment]
@lzim on the ISDC slides: What do you want to do about Andrew's slides? I can make sure that the last slide of acknowledgements is up to date on his as well as others.

**Comment by lzim** [comment]
> @lzim on the ISDC slides: What do you want to do about Andrew's slides? I know there were a lot of changes you wanted.
> I can at least make sure that the last slide of acknowledgements is up to date on his as well as others.

- Let me check on the OSF slidedeck
- I think that there were two things I noticed on the acknowledgements that may still have been missing, I'm not sure (maybe on mine too):
- Adding the R01 Co-Is who weren't on the R21
- Adding the R21 and R01 grant details at the bottom:
Research Funding from NIDA to PI: Zimmerman 1R01DA046651 and 1R21DA04219801
Can you see if we have that 

- Otherwise, re: Andrew's lack of references/acknowledgement, I think we can let this go as we have bigger 🐟 to fry

**Comment by lzim** [comment]
@staceypark Yes, my "final" on OSF named "zimmerman_sds_2019_health_final.pdf" and "zimmerman_sds_2019_health_final.pptx" are FINAL and what I uploaded and presented at the meeting.
- So, folks can make sure they have the same acknowledgements

For this stuff - It's okay, that we didn't have the R01 co-Is because we were presenting R21 work. 

I'll be sure to include these updates for AHSR and ISTSS.
> I think that there were two things I noticed on the acknowledgements that may still have been missing, I'm not sure (maybe on mine too):

> Adding the R01 Co-Is who weren't on the R21

> Adding the R21 and R01 grant details at the bottom:
Research Funding from NIDA to PI: Zimmerman 1R01DA046651 and 1R21DA04219801
Can you see if we have that

**Comment by lzim** [comment]
@staceypark UPDATE re: SDS

If you go to http://proceedings.systemdynamics.org/2019/ you can see that they only include our abstract and our link (for some reason), not our slides.

I checked and the only one with a broken link is David.
Let's get him to update his link to https://mtl.how and call it a day on this. 
I've checked the others off above.
