### ISSUE TITLE
Week of 10/15 HQ Huddle 

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#761]
**Week of 10/15 HQ Huddle** cross ref #750 
 
@lzim 

**Co-I meeting and Trial registration**
- [ ] Review Data Definition in wiki r21_r01_iir procedures
(https://osf.io/z7y8m/wiki/Data%20Definition/)
**R01**
- [ ]  Review consort tables on OSR for R01 (https://osf.io/8pzxu/wiki/consort_checklist)
- [ ]  Review updates to ct.gov for R01 - Responded to all 10 comments including re-updating a study protocol with cover page; Updated study time period to 01/01/2019 - 12/31/2024 (added an extra year since 5 year study); What should our "Primary Completion Date be? - defined as last date of data collection
**IIR**
- [ ]  Review ART > CT.gov for IIR
- [ ] If you can give me the **login information** and **cost** for each of the accounts, I can put in the Req orders.
- [ ]  Review notice OASC 
- [ ]  Review union letter
- [ ]  Review consort tables on OSF for IIR (https://osf.io/p7g8f/wiki/consort_checklist/)

**PAVIR HR & Expenses**
- [ ]  Review PD for 3 positions & finalize PDs - @ritahitching following guidance on call today, then Lindsey will review again.
- [ ] Give Stacey the login information and cost for each of the accounts, to put in the Req orders.

**Misc**
- [ ] Prep slides and update related information for WRJ visit (re: SWS's email)
- [ ] add Dexter to teampsd GitHub - @staceypark do we have a username for Dexter yet?

**Done**
- [x] MacBook or iPad property stickers for @ritahitching to send to PAVIR
- [x] PI Disclosure for IIR

@staceypark 
- [x] Meet w/Mark on query permissions for providers
- [ ] Work with Andrew to document & train on his work (@lzim I'm planning to meet with Andrew for an hour each day every day next week for: 1) splashpage; 2) data UI; 3) session 2 & 3 documentation; 4) pchart. I've asked him to document prior to the meeting and train during the meeting).
- [x] Follow up w/Savet on #462 
- [ ] Clarifying r21_manuscripts data file - May need to rename to be consistent with our conventions...Need to know where Tom is with syncing to MTL Videos for use in R21 Module Manuscripts
- [ ] #339 - There are instructions online about how to create a "Code of Conduct" and "Contribution Guidelines" for the mtl.how repo "MTL Community" Wiki for Q&A and upvoting.
- [ ] Help Dexter get setup again on Demo
- [ ] graphics for David's paper
- [x]  R01 & IIR IRB's - add Andrea in personnel
- [ ]  update OSF cheatsheet with Windows instructions
- [ ]  f/u with rachel kimerling for TeamPSD GitHub again
- [ ]  add Casey to TeamPSD platforms (bio, photo, GH account)
- [ ] f/u with June on VA OIT tag of monitors
- [ ] f/u with Chris & James on 1x meeting for psychotx tool

@ritahitching 
- [ ] HR and PD hires
- [x]  send this week's tt report
- [x]  Double-check IIR IRB
- [x]  RDIS IIR complete form
- [x]  Badge push
- [x]  ART > CT.gov for IIR
- [x]  SuNetId for @ritahitching (@ritahitching Ping Craig again if nothing comes through soon)

**JIT ASAP items (now on @lzim)**
- [ ] PI Assurance
- [ ] RDIS
- [ ] DAP
- [ ] Union Letter

1) Check with OMB on veteran work (Our project does not work directly with veterans/patients at all).
2) Check with Randy on potential single-site vs. multisite issue in regards to Andrea Nevedal

**Comment by lzim** [comment]
@ritahitching ans @staceypark 

Re: ISDC just need David to fix his link, I believe - see my post on #750 #hqhuddle

**Comment by lzim** [comment]
@staceypark 
- I meant to reminder you about tt2 and tt3 reports for Team 2 and Team 4

**Comment by ritahitching** [comment]
@lzim @staceypark 
Followed up with 

1. RDIS and inability to edit  our HSRD IIR Merit Award

1. My lack of badge

**Comment by ritahitching** [comment]
@lzim 
VA Inventory Management want a copy of the purchase order for the monitors.  Do you have it?

**Comment by staceypark** [comment]
@lzim relevant staff meeting updates:
- earliest upstairs move date Jan 22, 2020
- 7 grants going from NCPTSD this cycle, so Ella will be swamped.

**Comment by ritahitching** [comment]
@lzim @staceypark 
I completed a first pass on the RDIS forms for the IIR.

**Comment by ritahitching** [comment]
@lzim @staceypark 
I have taken a ART > CT.gov for IIR as far as I can - would welcome some feedback

**Comment by staceypark** [comment]
## **@lzim decisions needed:**
PR #762 
Issue #476

**Comment by staceypark** [comment]
- [ ] @staceypark re-upload outdated cheatsheets at mtl.how outside of VA

**Comment by staceypark** [comment]
- s11 & s12 SEE guides updated at mtl.how
- #ff video finally backed & sent to IC

**Comment by lzim** [comment]
Hi 👋🏼 #hq 

Arrived at AHSR & plan to try to get some work done, shortlist 

- [ ] s11 & s12 SAY guide and checklist for AM
- [ ] call w/James
- [ ] Review outstanding PR and Issues
- [ ] Prep for workshop tomorrow

**Comment by ritahitching** [comment]
@lzim IRB submission for IIR (protocol 52116) almost complete, with only the following issues pending. Once these are dealt with we can submitt. 

- **Competing financial interests on IIR IRB**

- Lindsey Zimmerman

- Steven Lindley 

**Missing Documents** - Looked everywhere, not luck Any ideas where it is? 
- VA Research Consent form
- HIPPA IRB waiver    
- Scientific Protocol waiver
- VA Required Questions 

FYI @staceypark

**Comment by staceypark** [comment]
@ritahitching 
- [ ] update 2 tables in #303 on Co-F & recordings

**Comment by staceypark** [comment]
@lzim 
We are also implementing my recommendation on PR #762 in line with goal of pointing to useful places.

> Need to make sure all mtl.how SEE and SAY guide links are pointing to useful places - some still point to out-dated guides on the Team PSD Repo

**Comment by staceypark** [comment]
@lzim Confirmed the change to 8am Pacific on Friday w/Craig. He's asking that you call him (number is in email).

**Comment by staceypark** [comment]
## Andon alert: 
Adobe Connect got removed from Kathryn's computer as a non-VA approved software. I thought we used Adobe Connect through VA EES, which means it should be fine. 
For the short run:
- I've just emailed Mike Truong (who removed it) to try and get more details.
- We could use Skype as a backup for Friday. I can alert everyone to the issue, depending on what Mike says tomorrow.

Did we have a specific EES contact or group we went through for the Adobe Connect account that I can reach out to?

**Comment by staceypark** [comment]
@lzim Permissions test for #429 w/Mark and they failed. Alerted Andrew.

**Comment by lzim** [comment]
> By the way, did you know you can pin up to 3 issues at the top of the issues page? (like how you pin tweets on Twitter). For example, pinning #303 during this entire training would have made it easier for the facilitators & saves emailing time wondering how to find it...

Nice!

**Comment by lzim** [comment]
@staceypark and @ritahitching 

- [ ] Recurrent expenses w/Yogita

Was there any progress on this? A response from Yogita?

**Comment by lzim** [comment]
> Re: Our EES Adobe Connect account.

- Can you email Elizabeth to ask her about who the best point of contact is about this?
She’s our project manager for _MTL Live_

**Comment by staceypark** [comment]
@lzim 
Re: MTL Learning objectives update, they want 30 days turnaround for resubmitting. I think if we can get all the documentation done by end of month - specifically the SAY guides for you, then we can give it to her beginning of November and have it ready by December. I don't expect we'll be starting with sites before then anyways.

Re: Yogita & expenses. They can just add the PAVIR credit card to these different accounts but would need us to submit requisitions for them with the login information.
- [ ] If you can give me the login information for all the accounts, I can put in the Req orders.

**Comment by staceypark** [comment]
@lzim Savet updated slides 1-70 (not all of them but just the parts within that range that needed updating) and you can find it in the Analyses folder on TeamPSD. @ritahitching and I went through most of it with her and gave her some feedback.

**Comment by staceypark** [comment]
@lzim I think it could be worth @ritahitching and I trying to run the Splashpage updates at the beginning of November instead of Savet. We would need to ask IT to download the SQL application for us to do so.

**Comment by staceypark** [comment]
@staceypark 
- [ ] schedule AH, TR, & LZ for floors
- [ ] schedule LZ & TR for ISTSS prep

**Comment by lzim** [comment]
> @lzim Savet updated slides 1-70 (not all of them but just the parts within that range that needed updating) and you can find it in the Analyses folder on TeamPSD. @ritahitching and I went through most of it with her and gave her some feedback.

Awesome News!  @staceypark and @ritahitching 
I just got off the line w/Craig and I’m in a session now.
Would you be willing to email the slide deck to my personal email to check out in the background during the meeting? 👩🏻‍💻

Thanks!

**Comment by lzim** [comment]
Also...@ritahitching & @staceypark 

- I’m going to be in a session until 9:45AM 
- So, David and I plan to _only join for the team meeting_ from 10-11AM.
- He’ll join PSY Team 2 (Lucid and Breakout 1) and I’ll join SP Team 4 (Adobe Main Room & VANTS)
- In other words, the teams can prep on their own and debrief on their own. 

Will you two be ready to go and set up the team

**Comment by ritahitching** [comment]
@lzim @staceypark Teams all organized - see you at 10:00am

**Comment by ritahitching** [comment]
@jessfroe @staceypark @lzim 
keep close check on team stamps today - to address facilitator concerns

**Comment by ritahitching** [comment]
@staceypark facilitate say guides 6 to 12 pulls done.

FYI @lzim

**Comment by ritahitching** [comment]
@lzim if you have Andrew's PD please forward - planning to reach out to HR shortly

**Comment by staceypark** [comment]
@lzim following up on the Adobe Connect issue - according to Elizabeth, we are supposed to use the browser version not the downloaded application. Kathryn's got deleted as part of a region check for software not secure for VA use. I think the browser version needs Flash though which we can't enable on our own... still investigating

**Comment by staceypark** [comment]
@lzim 
- Scheduled in for Ptool monthly checkin, ISTSS prep with Tom, & I've asked Tom & Andrew to join Monday Workgroup leads meeting to talk about the SP Floors and to update the GH issue prior to joining.

**Comment by staceypark** [comment]
- [ ] @ritahitching & @staceypark read and rate hires as CV's come in

**Comment by ritahitching** [comment]
@lzim @staceypark update on hires:

- Spoke with Ruth at length today
1. Finalized the RAI position
1. Updated the data analyst position - it's 95% there (f/u with Craig (no response) & Dough (on annual  leave) to get Andrew's PD) 
1. Discussed salary bands for both - she'll discuss with Maricela grant budgets
1. She'll circle back with you for final confirmation
1. Objective to finalize & approve by Monday 10/21
1. Post positions Tuesday/Wednesday October 22-23

**Comment by ritahitching** [comment]
@lzim added the laptop and ipad images to Pavir_expenses file
