### ISSUE TITLE
Week of 10/21 HQ Huddle

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#770]
# Week of 10/21 HQ Huddle (cross ref #761)
 🍁🍂🎃 👻 

### Co-I meeting
- [x] Review Data Definition in wiki r21_r01_iir procedures
(https://osf.io/z7y8m/wiki/Data%20Definition/)
- Reviewing for inclusion in R01 & IIR protocol manuscript.
- [x] Savet has updated the entire slidedeck #476 for the co-I meeting.
- Lindsey sending Lucid invite for Co-I meeting tomorrow. 

### IIR JIT
- [ ]  Review notice OASC 
- [ ]  Review union letter
- [ ]  Review RDIS 
- [x] PI Assurance - In JIT folder
- [ ] DAP
- Ella double checked on the multisite issue regarding Andrea N. and we are still single site with everyone under VAPAHCS. For the OMB notice, we are likely exempt as we are not surveying any non-VA employees re: email
- Right. That was my expectation for each.

### HR & Hiring
- [x]  Review PD for 3 positions & finalize PDs - @ritahitching following guidance on call today, then Lindsey will review again.
- Lindsey provided edits for each and discussed with Ruth, Rita and Stacey via email.

### R01 & IIR Trial registration
- [ ]  Review consort tables on OSR for R01 (https://osf.io/8pzxu/wiki/consort_checklist)
- [ ]  Review updates to ct.gov for R01 - Responded to all 10 comments including re-updating a study protocol with cover page; Updated study time period to 01/01/2019 - 12/31/2024 (added an extra year since 5 year study); What should our "Primary Completion Date be? - defined as last date of data collection
- [ ] Review CT for R01 (@ritahitching and @staceypark also recommend we go ahead and re-submit as they will let us know again if there needs to be more info)
- [ ]  Review consort tables on OSF for IIR (https://osf.io/p7g8f/wiki/consort_checklist/)
- [ ] Review IRB for IIR - almost complete, with only the following issues pending: 

 **Confirm that there are no Competing financial interests on IIR IRB**
- [x] Lindsey Zimmerman - mine is completed.

**Missing Documents** - Looked everywhere, not luck Any ideas where it is? 
- VA Research Consent form
- HIPPA IRB waiver    
- Scientific Protocol waiver
- VA Required Questions 

### EES-related Updates
- Learning Objectives: Elizabeth needs 30 day turnaround for updating LO's. Let's aim for end-of-October, when Documentation should be wrapping up as well.
- Adobe Connect: Kathryn's got deleted due to a regional check on non-VA approved software. The answer from Elizabeth & co so far has been that we are supposed to use the browser not app version. However, @staceypark 's testing has shown issues revolving around that - still pursuing more details.

### Other Upcoming:
- [ ] WRJ site visit updates (re: SWS email)
- [ ] November Splashpage - @staceypark thinks it would be good idea for @ritahitching & @staceypark to try November Splashpage update based on Andrew's training instead of Savet. Need to ask IT to download the SQL application to do so.

## @staceypark 
- [x] send out teampsd tt report
- [ ] f/u with Tom on manuscripts & data for CC/MM/PSY
- [ ] update cheatsheets & propagate
- [x] MTL Facilitator Epicenter & Data UI training
- [ ] #339 - There are instructions online about how to create a "Code of Conduct" and "Contribution Guidelines" for the mtl.how repo "MTL Community" Wiki for Q&A and upvoting.
- [x] get Dexter GitHub account and reset on Demo
- [ ] graphics for David's paper
- [ ] update OSF cheatsheet with Windows instructions
- [ ] f/u with rachel kimerling for TeamPSD GitHub again
- [ ] Lindsey Recurring expenses - LZ added login information & charge amount for all accounts as individual Req orders @staceypark can finish the additional Req details, then PAVIR can add their credit card (FYI: they prefer  a year's subscription purchase over monthly charges. If we do monthly charges, we have to forward receipts every month.)

## @ritahitching 
- [x] HR and PD hires
- [x] Lack of badge
- [x]  read and rate hires as CV's come in
- [x] Review SEE, SAY, and SAY checklists for mis-alignment over session #'s or typos
- [ ] Align Done/Do review in SEE & SAY session guides with pre/post emails aligns
- [x] f/u with Casey to add to TeamPSD platforms (bio, photo, GH account)
- [x] VA Inventory Management needs a copy of the PO for the monitors. Do you have it?
- [x] Email Steven Lindley to request that he complete his IIR IRB COI disclosures

**Comment by staceypark** [comment]
@lzim 
For facilitator training next week, I think the main items to cover are below. I reduced it to what I believe is the most relevant. Please let me know if I missed anything 😅 

1. GitHub
- Review overall difference between mtl.how and mtl.how/teampsd
- How to create issues
- Where to find team_tracker, SAY, SEE, checklist, & cheatsheets 
- How to use basic markdown, issue commenting, etc.

**Notes:** I think we should create a "resources" folder on mtl.how that doesn't require facilitators/learners to try to sift for it in a specific session folder. They could go to the TeamPSD repo, but I don't think it's a good idea for them to have to sift through it just for that. Along those lines, I think we should not have facilitators generally go to mtl.how/teampsd. Did you know you can "move" issues from one project to another. What if they interacted only with the private GitHub repo for both issues & the team tracker? What if they could get to everything they need from a combination of mtl.how & mtl.how/team_tracker.

2. mtl.how/facilitate
- Activate/inactivate user (see note on #756 about attendance test)
- How to use Dashboard & assume Facilitator roll
- Clarify difference between groups & worlds and how to assign oneself to them
- Review how to upload data from data UI to Epicenter

**Notes:** I recommend we don't teach the facilitators any functions beyond the above, including "i" information management, adding end users, creating new groups. It's too complex. They will forget. And realistically they will never need to do it. In line with the idea that we only teach them what they will use, I think I should divide the Facilitate/Meta cheatsheet into two pieces - Admin/HQ tasks & Facilitator tasks.

3. mtl.how/data (after the floors meeting with Tom & Andrew, which instead of a separate meeting I recommended they bring proposals to the Monday Workgroups)
- Review difference between Get Patient Level Data & Model Params buttons and expected behaviors
- Review difference in data and functions between each of the Excel workbook tabs (both in Excel workbook functions & in how to facilitate the data sessions)
- Review Splashpages
- Review folder structure/naming convention between data UI & sim params 

**Notes:** I recommend we do this on Wednesday with a combination of you, me, and Andrew to cover all of the clinical, administrative, and technical pieces that are involved with this. Then we spend Friday's session doing #2. Like in #2, I recommend we do not cover how to create teams and folders, etc. as I think we should have a dedicated HQ person doing this as that reduces error and confusion.

**Comment by ritahitching** [comment]
@lzim 
2 PD hires (RA I and Data Analyst) are ready to go and approved by Maricela as soon as you give the green light 

FYI @staceypark

**Comment by ritahitching** [comment]
@lzim @staceypark Reviewed resumes sent by PAVIR -  recommend initial interview by SP & RH for both positions

- **Jyoti Bhat** - suitable for **Data Analyst** position -
- **Hsin May Tsiang** - suitable for **SQL Programmer** position

**Comment by staceypark** [comment]
@ritahitching I took the names off. I don't think we should put in applicant names on this since it is public.

**Comment by staceypark** [comment]
@lzim 
- [ ] Can you add Rita to the mtl repo please?

**Comment by staceypark** [comment]
@staceypark @lzim 
Reviewed SEE, SAY, and SAY checklists for mis-alignment over session #'s or typos

**Comment by lzim** [comment]
> @lzim
> 
> * [x]  Can you add Rita to the mtl repo please?

Done!

**Comment by lzim** [comment]
> @lzim @staceypark Reviewed resumes sent by PAVIR - recommend initial interview by SP & RH for both positions
> 
> * one applicant - suitable for **Data Analyst** position -
> * another applicant - suitable for **SQL Programmer** position

Great, please do get going with interviews with applicants, but we need to see the standard interview for each position first, to make sure that the process is fair and fruitful.

And, yes, please do keep names private.

**Comment by lzim** [comment]
> @lzim
> 2 PD hires (RA I and Data Analyst) are ready to go and approved by Maricela as soon as you give the green light
> 
> FYI @staceypark

I edited and approved 2 of them. Turning to the third now.

**Comment by lzim** [comment]
@staceypark 

- [x] I linked Shiny Server App to the Team PSD Repository on Github
- [ ] Need this code from Savet to host Authorship App on Team PSD Shiny IO Account instead
```
rsconnect::deployApp('path/to/your/app')
```
- [x] Started Individual Reqs in Reqlogic for all recurrent expenses, please work with Yogita to complete these.
1. Speedscriber transcription
2. Adobe Creative Cloud
3. Basecamp Project Tracking
4. Rebrandly for mtl.how links
5. Zotero for reference management
6. GitHub PRO account for Private team_tracker 

@ritahitching 
>  VA Inventory Management needs a copy of the PO for the monitors. Do you have it?
- This should be something that can be gotten from Yogita. Unless you have it from the boxes when you unpacked them.

**Comment by lzim** [comment]
Morning!

@staceypark some things we need to turn to this week
- [ ] tt3 reports for Team 2 and Team 4 
- [ ] update on the #303 tables who has co-facilitated and who attended, etc.
- [ ] download the fidelity ratings data for s6-s11 for analysis

**Comment by ritahitching** [comment]
> > VA Inventory Management needs a copy of the PO for the monitors. Do you have it?
> 
> * This should be something that can be gotten from Yogita. Unless you have it from the boxes when you unpacked them.

@lzim contact Yogita regarding POs - will circle back

**Comment by ritahitching** [comment]
@lzim @staceypark 
- The latest resume seems more suitable for a senior/lead data-position (PhD.) - suggest we reserve for later.
- I'll discuss scheduling interviews with HR and update standard interview questions and ranking spreadsheet for RAI and SQL Progammer.
- Are you comfortable with the first screen by @staceypark and @ritahitching?

**Comment by staceypark** [comment]
@lzim 
I sent the tt3 when I sent the tt2 with the email linking to the recording Friday afternoon.
> * [ ]  tt3 reports for Team 2 and Team 4

**Comment by lzim** [comment]
> @lzim
> I sent the tt3 when I sent the tt2 with the email linking to the recording Friday afternoon.
> 
> > * [ ]   tt3 reports for Team 2 and Team 4

I totally missed that, I'm sorry. So, I should get it from Lucid then? Or fish out of my email?

####Co-I Meeting Help
- [ ] Print the updated slide deck for me for today's meeting (print 2 slides per _horizontal_ page,_ and print on both sides, please to save paper.
- [ ] Add the Team PSD link to the Slide Deck in the Lucid meeting, I tried to upload it, but it is too large.

**Comment by staceypark** [comment]
> @ritahitching and @staceypark
> 
> > The latest resume seems more suitable for a senior/lead data-position (PhD.) - suggest we reserve for later.
> 
> * Strongly disagree, please interview now.  We need to begin a relationship now or this person will take another job.
> * The standard interview questions go in Lucid and I can take a look there before you interview.
> * I think we should briefly touch base about recruiting today, because strong candidates need to be wooed 💃 But, yes, I am okay with you working on this and updating me.\

- ok - i'll reach out to all and schedule a time for an initial interview.  Do you want to be on that or Stacey and I first?

**Comment by ritahitching** [comment]
@lzim @staceypark 
Speaking on the phone to HR. Are we huddling today?

**Comment by ritahitching** [comment]
@lzim 
Ruth update: 
- The 2 positions - **RAI** and **Data Analyst - SQL Programmer** - will be **posted** later today or tomorrow.
- Confirm **budget** with Maricela upon her return and confirm PD for **Lead** **Data** **Analyst** with @lzim then **post** - likely **Friday Oct 25**

FYI @staceypark

**Comment by staceypark** [comment]
@lzim 
- sent VA Inventory Management POs they requested.

**Comment by staceypark** [comment]
@lzim 

-  Emailed SL to request confirmation of any competing interests/disclosures for the IIR IRB submission. I'll circle back once I hear.

**Comment by staceypark** [comment]
@staceypark 

- f/u with CG requesting bio, photo, GH account - will update once I hear more.

FYI @lzim

**Comment by lzim** [comment]
> @lzim
> Ruth update:
> 
> * The 2 positions - **RAI** and **Data Analyst - SQL Programmer** - will be **posted** later today or tomorrow.
> * Confirm **budget** with Maricela upon her return and confirm PD for **Lead** **Data** **Analyst** with @lzim then **post** - likely **Friday Oct 25**
> 
> FYI @ritahitching 
- The miscommunications about the PDs persist. Perhaps due to having a separate thread between Ruth & I, and a separate thread between Ruth and Rita. The two threads are necessary to discuss salary bands. But, pease read my last email carefully.
- We should use the midday HQ huddle to further clarify on the phone. 

- Please do not work on recruiting or interviewing candidates until we speak. It is a serious problem for there to be lack of clarity about which position is which in the quantitative workshop, while the search is underway.

**Comment by ritahitching** [comment]
> > @lzim
> > Ruth update:
> > 
> > * The 2 positions - **RAI** and **Data Analyst - SQL Programmer** - will be **posted** later today or tomorrow.
> > * Confirm **budget** with Maricela upon her return and confirm PD for **Lead** **Data** **Analyst** with @lzim then **post** - likely **Friday Oct 25**
> > 
> > FYI @ritahitching
> 
> * The miscommunications about the PDs persist. Perhaps due to having a separate thread between Ruth & I, and a separate thread between Ruth and Rita. The two threads are necessary to discuss salary bands. But, pease read my last email carefully.
> * We should use the midday HQ huddle to further clarify on the phone.
> * Please do not work on recruiting or interviewing candidates until we speak. It is a serious problem for there to be a lack of clarity about which position is which in the quantitative workgroup, while the search is underway.

@lzim - No problem. Let's discuss and clarify.

**Comment by ritahitching** [comment]
@staceypark @lzim back at my desk. thanks for the time to visit with my daughter's school

**Comment by ritahitching** [comment]
@staceypark @lzim 
- Bio from Casey received - will add to this week's tt_report.

**Comment by ritahitching** [comment]
> @staceypark
> 
> * [x]  I linked Shiny Server App to the Team PSD Repository on Github
> * [ ]  Need this code from Savet to host Authorship App on Team PSD Shiny IO Account instead
> 
> ```
> rsconnect::deployApp('path/to/your/app')
> ```
> 
> * [x]  Started Individual Reqs in Reqlogic for all recurrent expenses, please work with Yogita to complete these.
> 
> 1. Speedscriber transcription
> 2. Adobe Creative Cloud
> 3. Basecamp Project Tracking
> 4. Rebrandly for mtl.how links
> 5. Zotero for reference management
> 6. GitHub PRO account for Private team_tracker
> 
> @ritahitching
> 
> > VA Inventory Management needs a copy of the PO for the monitors. Do you have it?
> 
> * This should be something that can be gotten from Yogita. Unless you have it from the boxes when you unpacked them.

@lzim @staceypark - done and forwarded to Robert.

**Comment by ritahitching** [comment]
> @staceypark @lzim
> 
> * Bio from Casey received - will add to this week's tt_report.

@staceypark created a pull request please review

**Comment by ritahitching** [comment]
@lzim  @staceypark SUNetID active -able to log in to eprotocol

**Comment by ritahitching** [comment]
@lzim @staceypark 
- Additional Lead Data Scientist I contacted yesterday, is interested in discussing/hearing more about TeamPSD and the position. 
- Let's discuss how to respond

**Comment by staceypark** [comment]
@lzim 
James needs your eye on #339 & #757.
Also, Dev is out next week for Diwali.

**Comment by staceypark** [comment]
@lzim I sent yesterday's mtl facilitate recording out and started fleshing out tomorrow's agenda. Should we teach folks how to create issues? Or should we wait until the Button design is fully fleshed out to tackle that?

**Comment by ritahitching** [comment]
@lzim 
Badge / PIV ready to collect - first available appointment is Friday 25 at 3:20pm. I reserved the spot - let me know if there's a conflict.
Need PIV sponsorship from you prior.

**Comment by staceypark** [comment]
@lzim I just got off the phone with Elizabeth about the Adobe Connect issue.
Officially, AC is not VA approved, but it's also not officially disapproved. VA recognizes that AC has functions Skype does not and cannot tell us not to use it. So it's in a weird grey area.
As such, what happened to Kathryn (where there was a regional sweep and uninstallation of software not officially approved) could happen again to anyone at any point. However, as far as we know now, if the uninstallation does happen, folks can always redownload the add-on.

The add-on only really comes into play when people want to Share Screens. Everything else functions without the add-on. However, a core principle of our program is having the learners "drive" so ScreenSharing is the most important function for us.

There may come a point where VA officially decides no, we will not let people install this or may but up an Admin block to installation. And this could happen to us mid-trial.

We could either a) Keep running with AC since it will likely be fine, b) use Skype, c) explore third option.

**Comment by ritahitching** [comment]
- No agenda notes - suggests a cancellation of a meeting - should be confirmed the day before
- Cancellation or decision to cancel - should factor in the DEV team in Asia
- Work-group leads should make those decisions

**Comment by ritahitching** [comment]
- SOP for Monday's Workgroup Leads meetings - is the ONLY all-hands meeting 
- Proxies need to be established
- Sticking closely to SOPs 
- Support Stacey meetings and learn to manage meetings

**Comment by ritahitching** [comment]
@lzim @staceypark 

Morning QH. 
- Following up with Ruth on hires:
- [ ] RA I - potential candidates / interest so far
- [ ] SQL Programmer /Data Engineer - Posting update and wider circulation of position (Idealist / r-Ladies, SQL, LinkedIn, e.t.c.) - as it's our **top** priority
- [ ] Data Analysts / Technical Writer position - PD / Posting update
- [ ] Ask PAVIR to reach out to our potential candidate via LinkedIn - will send separate email

- Sent today's candidate a LucidMeeting invite yesterday scheduled for 12:00 pm today

**Comment by ritahitching** [comment]
@lzim @staceypark 
- I**RB Protocol**: for "A Cluster Randomized Trial of Mechanisms of Implementation Change to Expand Reach of Evidence-Based Addiction and Mental Health Care"  **expires** 11/30/2019 - we need to renew - let me know if I should go ahead and do this or if we should incorporate any changes prior.
