### ISSUE TITLE
Week of 12/23 & 12/30 #hqhuddle

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#839]
Cross Reference #824

### 12/23
- [ ] IIR Budget 
- [ ] IIR DAP 
- [ ] IIR Slides
- [ ] IIR Union
- [ ] IIR OASC
- [ ] Double check IIR on ct.gov by HSRD
- [ ] R01 ct.gov
- [ ] R01 DART
- [ ] IIR DART
- [ ] R01 protocol to send to co-I's 12/26

### 1/2 -1/3
- [ ] IIR protocol
- [ ] finalize & submit GMB manuscript
- [ ] finalize & submit VAPOR manuscript
- [ ] finalize & submit Mentee manuscript
- [ ] close all SAY documentation
- [ ] publish MTL manual online (Blue & Red)

### By COB 1/2
- [ ] new intro video at mtl.how/quick_overview for Red/Blue arms

### 12/23:
- [x] Send out r01 OSF to co-I's signed up & provide training/review meetings as requested.
- [x] Issue #830: mtl.how migration
- [x] update/review cheatsheet to send to co-I's
- [x] Flesh out GitHub Wiki FAQ #747
- [x] Test and close and remaining "done" but not "closed" items in trackers
- [x] email Jennifer for bio to put in 1/6 tt report & mtl.how/team 

### 12/26, 12/27, 12/30: 
- [x] document_tracker - document_team - come up with training, triage and prioritization plan
- [x] Create detailed training manual guide in OSF and quick checklists on GitHub for topics below. SOP & Training needs more documentation of orientation & the "WHY", Delegation lists!

@ritahitching @staceypark 
### 1/2, 1/3: 
- [x] Send out r01 OSF to co-I's signed up & provide training/review meetings as requested
- [x] Review & test training documents and checklists created, then create short training videos; Splashpage propagation update in the background for December
- [x] Issue #433: Setup certificates, tt reports, swag for r21 wrap up with MPD staff\
- [x] PCSPD update
- [x] Graphics for David's paper - Consistent look and feel using VHA style
- [x] Add Jennifer to website / photo and bio

**Comment by lzim** [comment]
@staceypark 

I'm going to edit the list above a bit now. I'll let you know when I'm done.
Were you still working on the ct.gov for the R01?

**Comment by lzim** [comment]
done with my edit above.

**Comment by staceypark** [comment]
@lzim 
- IIR & R01 protocol changes listed here. I will move them to ART or CT upon approval. Thought it might easier to see all in one place: https://osf.io/z7y8m/wiki/protocol_registration_changes/
- RDIS done for analyst hire
