### ISSUE TITLE
Week of 1/13 #hqhuddle 

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#889]
Cross ref #840 
### 1. Manuscripts
- [ ]  Review R01 consort tables on OSF (https://osf.io/8pzxu/wiki/consort_checklist)
- [ ]  Work with Stacey to re-submit VAPOR
- [ ]  Work with Swap to submit Mentor
- [ ]  Work to edit/finalize the graphics for GMB w/Stacey & David
- [ ]  R21 preliminary findings

### 2. MTL National Launch
- [ ]  Review SAY guides & close documentation cards
- [ ]  Bookdown format for the Manual

### 3. Manuscripts 
- [ ]  Review IIR consort tables on OSF for IIR (https://osf.io/p7g8f/wiki/consort_checklist/)
- [ ]  CC Intro & Discussion
- [ ]  MM Intro & Discussion
- [ ]  Psy Intro & Discussion
- [ ]  SP Intro & Discussion

### 4. Other Upcoming
- [ ] 1. NCPTSD website update - who handles this at NCPTSD 

## Delegate to #hq for handling:
- [ ] Email Dan O'Brien Mazza to update on MTL Launch before retirement 
- [ ] Set up local VAPOR meetings with Jill Hudson and Ben Marks, etc.

### Tuesday
- [ ] r01 Annual progress report
- [x] Double check w/Jane & Debbie on instructions for mtl.how/red
- [ ] Ping across team to help seed questions for Community of Practice.
- [x] Email Tom about SP
- [x] Talk to Savet about re-randomization procedures - need decision on how to re-randomize a HCS that cannot participate 
- [ ] Review MTL facilitate launch meeting notes from Monday w/ @ritahitching  and @lijenn 
- [x] Work w/@lijenn on PLDR button admin changes
- [x] Review @lijenn pull request for updating SAY guides on the done/do alignment
- [x] reschedule PAVIR budget meeting currently on 1/20

### Wednesday
- [ ] PCSPD to Ella w/ @lijenn  (need info from @lzim)
- [ ] Review MTL facilitate launch meeting notes w/ @ritahitching  and @lijenn 
- [ ] review any SOP questions w/ @lijenn after her review
- [ ] review slides/updates from Savet #674 
- [ ] Inventory for 8am Thurs meeting w/Savet all open items and training/documentation needed to be trained on and reviewed throughout week of 1/20
- [ ] R01 protocol w/ @lzim

### Thursday
- [ ] co-I manuscript review schedule
- [ ] work with @lijenn to submit Rebrandly expense monthly
- [ ] new monthly meeting time with Chris Crowe 
- [ ] new monthly meeting time with Kelly Maieritsch
- [ ] CRM Instance and User Request forms w/ @lzim 
- [ ] during 1pm HQ meeting: review training_tracker proposal by James & Stacey for training all new team members

### Friday
- [ ] Review MTL facilitate launch meeting notes w/ @ritahitching  and @lijenn 
- [ ] Review GitHub open issues left from James for him to further clarify/work on when return the next week
- Draft further training materials and plan to review with James week of 1/20

### Other
- [ ] Finish inventory of monitor & webcam needs to submit ReqLogic order #890
- [ ] Setup meeting invitation for MTL kickoff calls
- [ ] CFA meeting with David & Jessilyn in Feb
- [ ] Quarterly MTL presentation call - first one end of Feb

## @ritahitching 
**Monday Jan 13**
- [x] Back up Adobe and send follow up email for Jan 1/10 - MTL Launch meeting 
- [x] OI&T details for TeamPSD move for Steve Woodward

**Tuesday Jan 14**
✅  Edit notes and send follow up email for Jan 1/13 #manuscriptmonday meeting
✅ Email - Tom Rust cc Lindsey. 
- [ ]  Close out issues
✅  #793 (Andrea headshot - awaiting pull request approval from Stacey)
- #853 (John's title - awaiting changes by James)
✅ Update on Microsoft CRM / Teams for Debbie, Jane, David
✅ Schedule Juan and Ivy call

**Wednesday Jan 15**
- [ ] Schedule 1:1 meetings between Lindsey, Stacey, Rita, Jenn in early Feb in preparation for the March Pavir annual review. 
✅  Updates for tt_report email
- [ ] Review with Stacey - #825 (SEE & SAY Guides and Master Brochure Comparisons - for EES Elizabeth back 1/15)
- [ ] ReqLogic purchase for MS Teams & Lindsey account

**Thursday Jan 16**
✅ Send out follow up notes for MTL Launch 1/15 and update agenda for 1/17
✅Send invitation for teamPSD for  4th Tuesday / 9 am all hands (HQ, Quant, QIICS, Co-Is - virtual) (check with Stacey)
- [ ] Graphics for GMB / David's paper manuscript (#866)
- [ ] Pavir - Create list /calendar dates of manual requisitions (#885) -  Create an internal TeamPSD schedule for each vendor that will need manual requisition submissions each year and with due dates for the subscriptions. Perhaps we could create a yearly Outlook reminder that will ping us a few weeks before the deadline as well.
✅ Update HQ Meeting agenda with my questions/updates 

- [ ] Book TeamPSD dinner with David / Andrea

**Friday Jan 17**
- [ ] Send tt_report via autosend
- [ ] Claire, Gayle and Theresa requested an web camera. 
- [ ] Review and incorporate Savet's comments on the Consort tables in OSF

### Other

- [ ] Send hardcopy materials & swag to facilitators #890
- [ ] VAPOR videos in pre/post emails (issue #870) 
- [ ] VAPOR - Scheduling - Lessons learnt for 3 Veteran engagement groups. 
- Travis Runnels at VAPAHCS.
- Nathaniel Moffet form the Ascend Project in Colorado.
- Leah Wendleton does Veteran-engagement groups for VA researchers.

### Training
- [ ] Finish & get a copy of SOP (OSF Account for online copy of SOP) **DUE: End of 1/15/20**
- [x] Ensure all transfers from Lucid (Oct 2019-Nov 2019) to Basecamp are completed **DUE: End of 1/13/20**
- [ ] Go through trial/registration/process of putting projects onto OSF (#871) **DUE: 1/17/20**
- [ ] Ensure all Lucid Meeting audios starting from Aug. 2019 are transferred into TeamPSD Meeting Audio folder  **DUE: 1/17/20**
- [ ] VAPOR? **DUE: TBA**
- [ ] (Optional) Reformat Table of Contents for SOP **DUE: TBA**
Deadline for all Training issues: by the end of this week (1/17/20)

### MTL (UI/etc. issues)
- [x] #891 & Review SAY Guides to match SEE Guides in Master 
- [ ] Fix typos on 'We use cookies' pop-up on MTL UI **DUE: TBA needs training**
- [ ] Fix email signature from MTL (dynamic --> dynamics) **DUE: TBA needs training**
- [ ] Get info./account for mtl.how/test to participate in giving James feedback for any UI related issues **DUE: TBA needs training*
Deadline for all MTL issues: by the end of this week (1/17/20)

**Comment by ritahitching** [comment]
@staceypark @lzim @lijenn 
Good morning. I closed out our HQ thread #840 for week 1/6, deleted completed tasks,  started a new HQ issue thread #889 for 1/13, and cross-referenced.  Please review, thanks!

**Comment by ritahitching** [comment]
@lzim @staceypark @lijenn 

**By end of day 1/13**
- [ ]  Send MTL Launch follow up email for Jan 1/10 meeting
- [ ] Send #manuscriptmonday follow up email for Jan 1/13 meeting
- [ ] Start and scope out time needed to complete technology inventory Steve Woodward 

Calendar
- [ ] Send calendar invitation for teamPSD for 4th Tuesday / 9 am all hands (HQ, Quant, QIICS, Co-Is - virtual) (review instructions with Stacey)

**Comment by ritahitching** [comment]
@lzim @staceypark @lijenn

✅ OI&T move information done. 
- Details of all team members added to move list - Lindsey, Stacey, Rita, Jenn, Savet, Ash, and Anthony. 
- Spoke with Steve Woodward and he confirms that he has all the information he needs from TeamPSD for the move.
- Mary will be responsible for tagging workstations, screens, and phone.

**Comment by staceypark** [comment]
@lzim I did a sketch of my priorities above. Please let me know if I'm missing something and then I'll populate it in outlook.

**Comment by ritahitching** [comment]
@lzim I received email confirmation from Steve Woodward that he would reserve 10 desks in a cluster for TeamPSD for the move to upstairs office space.

**Comment by ritahitching** [comment]
@lzim @staceypark Update on Microsoft CRM & Teams for Facilitators:

1. I submitted an IT HelpDesk ticket escalation for Microsoft CRM & Team for Debbie, Jane, and David's.  In the process they informed me they do not use VA machines but use VPN in with their laptops. 
2.  I emailed Mary asking for guidance on how we could install software for the Facilitators on their own laptops.  
3. Mary came by to explain that IT will not be able to install software in non-VA machines.  She recommended Facilitators get their own license or remote login to a VA machine.

**Comment by ritahitching** [comment]
@lzim @staceypark 

Updated on the **cost** of monthly  ATT WiFi hotspot - **$37 monthly** 

_________________
From HQ #840    WiFi hotspot used by Shannon's team:

Use the ATT 2TE model (https://www.att.com/buy/connected-devices-and-more/att-unite-express-2-black.html).
Purchased through ReqLogic an unlimited data plan with ATT - estimated cost of $100 monthly which included the WiFi hardware.
Data plan offers a main and guest plan. Main plans has a fixed password login that can support 8 devices simultaneously. The guest plan has a daily changing password and can support 3 devices concurrently.
Benefits: Hotspot does not block websites the VA typical does, can be moved to improve bandwidth and is relatively reliable for general web access.
Drawbacks: Hotspot coverage poor when downloading and uploading files.
