### ISSUE TITLE
1/24 #hqhuddle

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#907]
Cross ref #903 
# HQ Friday Jan 24

### Milestones 
- [x] **Jenn** OSF milestone registration guide 
- [ ] **Rita and Jenn** PAVIR Requisitions (Jenn: waiting for Nga's response)
- [x] **Rita** EES Learning Objectives

### Action Items (in Lucid)
- [x] **Stacey** record and document training with Anthony & Savet 
- [x] **Stacey** review SOP edits in preparation for Tuesday's all hands meeting
- [ ] **Stacey** Facilities document for SAMHSA grant
- [ ] **Stacey** Self-evaluation for PAVIR
- [x] **Rita** Finalize PAVIR requisitions table
- [ ] **Jenn** Finalize Rebrandly monthly reimbursement request and put doc into TeamPSD folder 
- [x] **Rita** send Elizabeth finalized Learning Objectives document for MTL Blue
- [x] **Rita** update SEE, SAY, and Master Brochure Learning Objectives on mtl.how/teampsd to match the set provided to Elizabeth
- [x] **Rita** Self evaluation for PAVIR

### Emergent Issues (2 hours/day Stacey & Lindsey; 1 hour/day Rita and Jen)
- [x] **Stacey** PCSPD - outstanding issue until Ella receives clarification
- [x] **Stacey** Schedule time with Andrea/IRB
- [ ] **Stacey** Schedule meeting w/Darcy
- [x] **Rita** tt report including instructions for updating RSVP
- [x] **Rita** submit IT helpdesk ticket for Savet's old machine in Lindsey's office for R, R Studio, and Microsoft SQL Server Management Studio
- [x] **Jenn** Consort - Edit TAS to QIIC
