### ISSUE TITLE
1/27 #hqhuddle 

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#911]
Cross ref #907 
# HQ Monday Jan 27

### Milestones 
- [x] **Rita and Jenn** PAVIR Requisitions (Jenn: waiting for Nga's response)
- [x] **Rita** - finish graphics for GMB paper - David in town and planning to finish writing with Lindsey this week.

### Action Items (in Lucid)
- [x] **Lindsey** SAMSHA Budget Justification
- [x] **Lindsey** MHOC Crosswalk & Matt Boden Check-in
- [ ] **Lindsey** Statistician Position Description
- [ ] **Lindsey** R01 Protocol
- [x] **Stacey** Facilities document for SAMHSA grant
- [x] **Stacey** Self-evaluation for PAVIR
- [x] **Rita** Finalize PAVIR requisitions table
- [x] ~~**Jenn** upload the TeamPSD SOP to the mtl.how/teampsd Wiki~~  Reassigned to Anthony
- [x] **Stacey** and **James** will link any relevant training documents to the Wiki as well
- [x] **Rita** crosswalk table - iir sites waves 1 - 6  and criticality score

### Emergent Issues (2 hours/day Stacey & Lindsey; 1 hour/day Rita and Jen)
- [x] **Stacey** Schedule meeting w/Darcy
- [x] **Rita** follow up with IT helpdesk on ticket submitted (#RITM1407475)  Friday Jan 24 for Savet's old machine in Lindsey's office for R, R Studio, and Microsoft SQL Server Management Studio
- [x] **Rita** follow up with LucidMeeting helpdesk 
- [x] **Rita** back up audio for #manuscriptmonday and send follow up email
- [x] **Rita** Ash bio and photo + website + pull request

**Comment by lijenn** [comment]
# HQ Tuesday Jan 28

### Milestones 
- [ ] **Rita and Jenn** PAVIR Requisitions (Jenn: waiting for Nga's response)
- [ ] **Rita** - finish graphics for GMB paper - David in town and planning to finish writing with Lindsey this week.

### Action Items (in Lucid)
- [ ] **Lindsey** SAMSHA Budget Justification
- [ ] **Lindsey** MHOC Crosswalk & Matt Boden Check-in
- [ ] **Lindsey** Statistician Position Description
- [ ] **Lindsey** R01 Protocol
- [ ] **Stacey** Facilities document for SAMHSA grant
- [ ] **Stacey** Self-evaluation for PAVIR
- [ ] ~~**Jenn** upload the TeamPSD SOP to the mtl.how/teampsd Wiki~~  Reassigned to Anthony
- [ ] **Stacey** and **James** will link any relevant training documents to the Wiki as well



### Emergent Issues (2 hours/day Stacey & Lindsey; 1 hour/day Rita and Jen)
- [ ] **Stacey** Schedule meeting w/Darcy
- [ ] **Rita** follow up with IT helpdesk on ticket submitted (#RITM1407475)  Friday Jan 24 for Savet's old machine in Lindsey's office for R, R Studio, and Microsoft SQL Server Management Studio
- [ ] **Rita** follow up with LucidMeeting helpdesk 
- [ ] **Rita** back up audio for #manuscriptmonday and send follow up email
- [ ] **Rita** Ash bio and photo + website + pull request

**Comment by lijenn** [comment]
# HQ Wednesday Jan 29

### Milestones 


### Action Items (in Lucid)



### Emergent Issues (2 hours/day Stacey & Lindsey; 1 hour/day Rita and Jen)

**Comment by lijenn** [comment]
Cross ref #913
# HQ Thursday Jan 30

### Milestones 


### Action Items (in Lucid)



### Emergent Issues (2 hours/day Stacey & Lindsey; 1 hour/day Rita and Jen)

**Comment by lijenn** [comment]
# HQ Friday Jan 31

### Milestones 


### Action Items (in Lucid)



### Emergent Issues (2 hours/day Stacey & Lindsey; 1 hour/day Rita and Jen)

**Comment by lzim** [comment]
@ritahitching @lijenn @ritahitching 

#hq tips 😺 

- Let's take 5 minutes first thing AM tomorrow to make sure Jenn can schedule in Outlook, okay?
- Please note that my schedule is full tomorrow with the only exception of 2-2:30PM. If you're going to try to schedule someone, then put it in my Outlook calendar right away to protect the time. Otherwise it will be gone.
- Also, I need to be cc'd on anything that is a "PAVIR Requisition/Check Requests" 

Thanks!

**Comment by staceypark** [comment]
@lzim Below is the delegation plan & implications we discussed:

For each workgroup, this will be the point person:
1. HQ - Stacey
2. Quant - Anthony
3. Sim/Model - Anthony
4. Facilitate - Rita & Jenn
5. VAPOR - Jenn
6. EES - Rita & Jenn
7. Co-I/Manuscript - Stacey
8. Qual - Jessilyn
9. Support WG - Anthony
10. Workgroup Leads - Stacey

Each point person is responsible for:
A. Meeting Management
1. 48 hours in advance of their respective meetings (in business hours, meaning for a Monday meeting, this is by Thursday), the point will:
- Setup the agenda (We noted that the point person may not always have all the info necessary to flesh out the full agenda & attachments, but they need to proactively reach out to others for help if that is the case)
- Send the meeting reminder from Lucid including asking for RSVP's

2. During the meeting, the point will:
- Facilitate the agenda 
- Scribe decisions, action items, and issues in Lucid using the appropriate buttons and into related GitHub issues (We noted that the point person may not always be able to scribe if they are the main person sharing screens/driving/etc., but it is their responsibility to proactively "tap" someone if needed to help scribe if that is the case)

3. After the meeting, the point will:
- Final lookover to make sure notes are in order 
- Publish notes to BaseCamp
- Send follow-up email 
- Download Lucid audio into TeamPSD drive (and mtl.how/live video as necessary)

B. Workflow Management
The point person will:
- Follow-up on any items posted to GitHub from Lucid meeting if not responded to within 24 hours
- Keep track of their workgroups' interim deliverables and major milestones for the month, and follow-up on GitHub to make sure work is moving forward.
- Alert workgroup leads prior to Monday/Thursday Leads and Support meetings to any cross-cutting issues or dependencies that they may need reminding to take to these meetings
- Serve as Proxy to Workgroup Lead In Monday/Thursday meetings when Lead is absent

**Comment by staceypark** [comment]
@lzim Plan for tomorrow's first hour of MTL Facilitate meeting:
1. Present questions on #747 for Feedback
2. Show where the Wiki will be at mtl.how: https://github.com/lzim/mtl/wiki
3. Demonstrate the search function in the Wiki
