### ISSUE TITLE
1/28 #hqhuddle

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#912]
Cross ref #911
# HQ Tuesday Jan 28

### Milestones 
- [ ] **Rita and Jenn** PAVIR Requisitions (Jenn: waiting for Nga's response)
- [ ] **Rita** - finish graphics for GMB paper - David in town and planning to finish writing with Lindsey this week.

### Action Items (in Lucid)
- [x] **Lindsey** SAMSHA Budget Justification
- [ ] **Lindsey** MHOC Crosswalk & Matt Boden Check-in
- [ ] **Lindsey** Statistician Position Description
- [ ] **Lindsey** R01 Protocol
- [ ] **Stacey** Facilities document for SAMHSA grant
- [ ] **Stacey** Self-evaluation for PAVIR
- [ ] ~~**Jenn** upload the TeamPSD SOP to the mtl.how/teampsd Wiki~~  Reassigned to Anthony
- [ ] **Stacey** and **James** will link any relevant training documents to the Wiki as well

### Emergent Issues (2 hours/day Stacey & Lindsey; 1 hour/day Rita and Jen)
- [ ] **Stacey** Schedule meeting w/Darcy
- [ ] **Rita** follow up with IT helpdesk on ticket submitted (#RITM1407475)  Friday Jan 24 for Savet's old machine in Lindsey's office for R, R Studio, and Microsoft SQL Server Management Studio
- [ ] **Rita** follow up with LucidMeeting helpdesk 
- [ ] **Rita** back up audio for #manuscriptmonday and send follow up email
- [ ] **Rita** Ash bio and photo + website + pull request
