### ISSUE TITLE
2/3 #hqhuddle

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#928]
Cross ref #911 
Week of 2/3 - 2/7

**Comment by staceypark** [comment]
# HQ Monday February 3

### Milestones 
- [ ] **Jenn** SOP Project Registration: Transfer at least 1/3 of Guide onto GitHub TeamPSD Resources

### Action Items (in Lucid)
- [ ] **Jenn** Test dashboard & common functionality

### Emergent Issues (2 hours/day Stacey & Lindsey; 1 hour/day Rita and Jen)
- [ ] **Jenn** Schedule call Thad w/ LZ, SP, AP, AN

**Comment by staceypark** [comment]
# Tuesday February 3

### Milestones 

### Action Items (in Lucid)

### Emergent Issues (2 hours/day Stacey & Lindsey; 1 hour/day Rita and Jen)

**Comment by staceypark** [comment]
# Tuesday February 3

### Milestones 

### Action Items (in Lucid)

### Emergent Issues (2 hours/day Stacey & Lindsey; 1 hour/day Rita and Jen)

**Comment by staceypark** [comment]
# Thursday February 3

### Milestones 

### Action Items (in Lucid)

### Emergent Issues (2 hours/day Stacey & Lindsey; 1 hour/day Rita and Jen)

**Comment by staceypark** [comment]
# Friday February 3

### Milestones 

### Action Items (in Lucid)

### Emergent Issues (2 hours/day Stacey & Lindsey; 1 hour/day Rita and Jen)

**Comment by ritahitching** [comment]
@lzim 
I added reviewing Steve’s moving spreadsheet to our HQ meeting agenda for today.

**Comment by ritahitching** [comment]
**Update** 
I followed up again with IT helpdesk on the ticket we submitted Jan 24 to install R, R Studio, and Microsoft SQL Server Management Studio - ticket remains open and without a triage a date. Sent Mary an email asking if she can request to have the ticket expedited.

**Comment by ritahitching** [comment]
**Update**
Purchase WiFi hotspot for teamPSD
PAVIR does not provide support for phone line requisitions.  The recommendation is the PI purchase a line directly from a carrier (e.g. AT&T).  The PI is then reimbursed monthly through their paycheck up to the value of $50.  I have the forms for the paycheck reimbursement.

**Comment by ritahitching** [comment]
> **Update**
> I followed up again with IT helpdesk on the ticket we submitted Jan 24 to install R, R Studio, and Microsoft SQL Server Management Studio - ticket remains open and without a triage a date. Sent Mary an email asking if she can request to have the ticket expedited.

**Update** I submitted a request to expedite our IT helpdesk ticket #RITM1407475 with Mary's approval.  I'll  provide updates as I hear more.

**Comment by ritahitching** [comment]
> **Update**
> I followed up again with IT helpdesk on the ticket we submitted Jan 24 to install R, R Studio, and Microsoft SQL Server Management Studio - ticket remains open and without a triage a date. Sent Mary an email asking if she can request to have the ticket expedited.

Update on WiFi purchase provided in #931 - data plans in shared drive.

**Comment by ritahitching** [comment]
**Interview Data Scientist Position**
- Attendees Lindsey, Stacey, Ash, Anthony
-Time needed 1 hour 
- Possible times 


**Wednesday Feb 19**  1pm to 2pm or 2pm to 3pm 
**Thursday Feb 20** 2pm to 3pm  or 3 to 4pm.

**Monday Feb 24** 1:30pm to 2:30pm
**Wednesday Feb 26**  1pm to 2pm or 2pm to 3pm
