### ISSUE TITLE
pre/post emails across MTL Blue & MTL Red

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#987]
# Pre/Post Emails 

## 1. Link to the document, add relevant team members to the card, and add workflow decisions.
- [x] Add the link the current draft of the documentation for the issue
- [pre_email template](https://github.com/lzim/teampsd/edit/rita_2020_03_19_email_template_issue_1176/mtl_facilitate_workgroup/pre_post_emails/pre_emails/mtl_live_pre_session01_template.md)
- [post_email template](https://github.com/lzim/teampsd/blob/rita_2020_03_19_email_template_issue_1176/mtl_facilitate_workgroup/pre_post_emails/post_emails/mtl_live_pre_session01_template.md)
- [x] Add all related workflow decisions here:
- Use https://www.tms.va.gov/SecureAuth35/ for CMUs with EES

## 2. Link to issues that must be edited in the document in the **issue_tracker** and **feature_tracker.** _(use the # for the link to the issue)_
- [x] Issue #870 - VAPOR videos
- [x] Issue  #1256 - VAPOR Week 3 Video Selection and Upload
- [x] Issue #1033 - Create new logos for MTL Red Comparator Arm to use in emails, videos, and guides 
- [ ] Issue #983  - TBD: Pre/Post Emails - Add specific dates & co-facilitators
- [x] Issue #1120 - MTL Blue Replace Header logo for S1 - S12 for Pre and Post Email 
- [x] Issue #1278 - 4/3 Replace Broken Links in Do and Done Logos in Pre and Post Emails
- [ ] Issue #1219 - MTL Red Replace Header logo for Pre/Post Emails
- [ ] Issue #1176 - Pre/Post Email Template MTL Blue
- [ ] Issue #1293 -  Pre/Post Email Template MTL Red

# 3. Team Review
- [ ] Fidelity - check with Lindsey
- [ ] Data UI - check quant_workgroup
- [ ] Sim UI - check with model_workgroup and/or sim_workgroup

## 4. Review and Open Pull Requests _(use the # for the link to the pull request)_
- [ ] Check the draft for typos
- [ ] Check or open a pull request for the document edits

## 5. Review and/or Update Graphics
- [ ] Screenshots
- [ ] Gifs
- [x] Logos/Icons
- [x] Links

## 6. Dependencies
- [ ] Make sure that any edits you make that need to be added to **depend_product** are tracked (e.g., _MTL Video_)

## 7. Close Pull Requests
- [ ] Request review and/or close open pull requests for the document

**Comment by staceypark** [comment]
For each version of *Modeling to Learn*, we need to update the "Modeling to Learn" logo to...

R01 "Red" email logos:
- [ ] pre/post session 1: "mtl part over data UI" (Dependency on @lzim to create these first)
- [ ] pre/post session 2: "mtl part 2 over data UI" (Dependency on @lzim to create these first)
- [ ] for remaining 20 emails, we will just use the "mtl red" logo found [here](https://github.com/lzim/teampsd/blob/master/resources/logos/mtl_how_red.png)

IIR "Red" email logos:
- [ ] pre/post sessions 1-6: "mtl session 1... session 6 over data UI" Dependency on @lzim to create these first)
- [ ] pre/post sessions 7-12: "mtl session 7...session 12 over team data" Dependency on @lzim to create these first)

R01 & IIR "Blue" email logos:
- [ ] for all 24 emails, use the title slides logo found [here](https://github.com/lzim/teampsd/tree/master/resources/title_slides)

**Comment by lijenn** [comment]
#983 I am still working on the EES Program details to get in these as well
#870 VAPOR Video Youtube links needed - Need Lindsey to get all the links public

**Comment by ritahitching** [comment]
Update on remaining tasks


Task | Assignee | Issue
-- | -- | --
Create MTL Red Logos | Lindsey | #1033
Vapor Videos to be made public on YouTube | Lindsey | #870
Integrate EES into Pre and Post emails | Jenn | #983
MTL Blue Replace Header logo for S1 - S12 for Pre and Post Email  (currently tracked within #870 | Rita | #1120

Once the MTL Red logos are ready, we will delegate the Red logo tasks

**Comment by lzim** [comment]
@lijenn and @ritahitching all the videos are up and #870 and #1033 are closed.

As a next step, It would be great to see a template for approval before you do too much work to create the 24 MTL Blue emails and the 24 MTL Red emails.

Thanks1

**Comment by ritahitching** [comment]
- [ ] Cross ref #1176  template 24 MTL Blue emails 
- [ ] Create issue card 24 MTL Red emails
